dockerfiles/Dockerfile_linux_glibc
dockerfiles/Dockerfile_linux_glibc_arm64
dockerfiles/Dockerfile_linux_glibc_arm64_from_amd64

Checklist
---------
* yes: ok
What
----
Change docker image tags to 'latest'.
References
----------
N/A
Test & Review
-------------
N/A

Relabel docker tags

---

mk-files/release.mk

Checklist
---------
* yes: ok
What
----
We have removed those leading `v`s and they should be removed from checksum filenames and path names as well. This PR was accidentally reverted before.
References
----------
Test & Review
-------------

Remove the leading v from checksum file names in release.mk

---

SECURITY.md

Update SECURITY.md email reference from bugbounty@confluent.io to security@confluent.io email address.
Checklist
---------
* yes: ok
What
----
References
----------
Test & Review
-------------

Update SECURITY.md email reference

---

internal/cmd/iam/command_rbac.go
internal/cmd/iam/command_rbac_role_describe.go
internal/cmd/iam/command_rbac_role_list.go
test/fixtures/output/iam/rbac/role/describe-invalid-role-cloud.golden
test/fixtures/output/iam/rbac/role/list-cloud.golden
test/fixtures/output/iam/rbac/role/list-json-cloud.golden
test/fixtures/output/iam/rbac/role/list-yaml-cloud.golden
test/test-server/cloud_mds_handlers.go

Revert "[DGS-5745, CIAM-2563] Add Stream Catalog roles to CLI"

---

.github/pull_request_template.md

Checklist
---------
* yes: ok
What
----
This PR needs to be in-use for a week before https://github.com/confluentinc/cli/pull/1719 is merged.

Add release notes to PR template [ci skip]

---

internal/cmd/api-key/command_list.go

Release Notes
-------------
Bug Fixes
- Resolve a panic that could occur in ``confluent api-key list``
Checklist
---------
* yes: ok
What
----
Change from direct access of User.ResourceId and User.Id to get functions.
References
----------
n/a
Test & Review
-------------
Ran unit tests

Fix panic in api-key list

---

test/byok_test.go

Release Notes
-------------
New Features
Bug Fixes
Checklist
---------
* yes: ok
What
----
Apply new changes to new file.
References
----------
n/a
Test & Review
-------------
Ran all tests locally

Switch from bincover to built in test coverage for `byok_test`

---

Jenkinsfile

Checklist
---------
* yes: ok
What
----
Migrating off of the v3 branch now that v3 changes have been pulled in to 7.4.x. Hoping that this fixes test stability.

Use 7.4.x branch for CP system tests

---

internal/cmd/admin/command_payment_describe.go
internal/pkg/config/v1/feature_flags.go
internal/pkg/errors/error_message.go

Release Notes
-------------
New Features
Bug Fixes
Jira ticket: https://confluentinc.atlassian.net/browse/CPG-2902
Slack thread: https://confluent.slack.com/archives/CG6BW233L/p1675460350801609
- Fflag used in the PR: https://app.launchdarkly.com/default/prod/features/cloud_growth.marketplace_linking_advertisement_experiment.enable/targeting
- Tests ran:
prod_already_has_payment
```
% dist/confluent_darwin_amd64_v1/confluent login
Enter your Confluent Cloud credentials:
Email: ryoshida@confluent.io
Password: *********
% dist/confluent_darwin_amd64_v1/confluent admin payment describe
visa ending in 8729
```
prod_no_payment_on_file
```
% dist/confluent_darwin_amd64_v1/confluent login                 
Enter your Confluent Cloud …
```

[CPG-2902] Conditionally advertise Marketplace payment option

---

mk-files/release-notes.mk
mk-files/release.mk

Checklist
---------
* yes: ok
What
----
If the docs team makes us fix the release notes, we will no longer have to download from S3, modify, and re-upload.
Test & Review
-------------
Will give this a try during tomorrow's release.

Publish release notes to S3 after docs review

---

CONTRIBUTING.md

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
`int-test` and `INT_TEST_ARGS` are now `integration-test` and `INTEGRATION_TEST_ARGS`; this PR updates `Contributing.md` to reflect this.
References
----------
Test & Review
-------------

Update Contributing.md wording

---

internal/cmd/asyncapi/account_details.go
internal/cmd/asyncapi/command_export.go
internal/cmd/asyncapi/command_export_test.go

Release Notes
-------------
Bug Fixes:
- Skip Protobuf schemas in `confluent asyncapi export` 
Checklist
---------
Yes
What
----
Fixes the error message comparison in case of Protobuf schemas and produces an AsyncAPI spec with skipping all the protobuf topics. 
References
----------
Follow-up PR to https://github.com/confluentinc/cli/pull/1761
Test & Review
-------------
Tested locally against a Devel cluster

AsyncAPI fixing Protobuf Errors

---

mk-files/cc-cli-service.mk

Checklist
---------
* yes: ok
What
----
The regular expression was treating "." as a wildcard, not a period. They needed to be escaped.
Test & Review
-------------
Tested on `dry-run` branch!

Fix regex in `make promote`

---

mk-files/cc-cli-service.mk

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Fix a typo.
References
----------
Test & Review
-------------

Fix typo in `cc-cli-service.mk`

---

mk-files/release.mk
scripts/update_Dockerfile_linux_glibc.sh
scripts/update_Dockerfile_linux_glibc_arm64.sh
scripts/update_Dockerfile_linux_glibc_arm64_from_amd64.sh

https://confluent.slack.com/archives/C038ZJ00P/p1679368991765529

Adjust Makefiles to use AWS SSO instead of gimme-aws-creds

---

mk-files/docs.mk
mk-files/release-notes.mk

Checklist
---------
* yes: ok
What
----
Removed the trailing `&&` and fixed `if` statement notation. Validated with `DRY_RUN=true`

Fix `make release-notes` target

---

mk-files/docs.mk

What
----
Fix branch name, and open PR even if there are no changes (the release notes and command reference are combined into the same PR now)
Test & Review
-------------
Ran during the last release.

Fix `make publish-docs`

---

internal/pkg/auth/sso/auth_state.go
internal/pkg/auth/sso/auth_state_test.go

Checklist
---------
* yes: ok
What
----
Used the function created in #1855 to fix another instance of trailing slashes breaking SSO login. This code was likely copy-and-pasted.
Test & Review
-------------
Manually tested, tests still pass

Fix SSO state generation for URL with trailing slash

---

internal/cmd/price/command_list_test.go
test/fixtures/output/price/list-json.golden
test/fixtures/output/price/list-legacy.golden
test/fixtures/output/price/list.golden
test/price_test.go
test/test-server/ccloud_handlers.go
test/test-server/ccloudv1_handlers.go

Checklist
---------
* yes: ok
What
----
Use the integration testing framework instead of mocking Cobra commands for `confluent price list`. Made sure not to sacrifice any test coverage.
References
----------
Required for #1862
Test & Review
-------------
Wrote new integration tests where applicable

Use integration testing framework for `price list`

---

internal/cmd/api-key/command.go
internal/cmd/api-key/command_create.go
internal/cmd/audit-log/command_describe.go
internal/pkg/cmd/flags.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix service account error in `confluent api-key create` when audit logs are disabled
Checklist
---------
* yes: ok
What
----
References
----------
Test & Review
-------------

Check for audit-log sa id and env id to ensure it's enabled

---

internal/pkg/auth/auth_token_handler.go
internal/pkg/auth/sso/auth0_utils.go
internal/pkg/auth/sso/auth_sso_flow.go
internal/pkg/auth/sso/auth_state.go
internal/pkg/auth/sso/auth_state_test.go

What
----
We need to call the correct realm endpoint to determine the IDP (connection) ID for the user's org.
Test & Review
-------------
Manual testing, still running into complications

Fix FEDRAMP SSO

---

cmd/lint/main.go
go.mod
go.sum
internal/cmd/asyncapi/command_import.go
internal/cmd/schema-registry/command.go
internal/cmd/schema-registry/command_cluster_test.go
internal/cmd/schema-registry/command_cluster_update.go
internal/cmd/schema-registry/command_config_describe.go
internal/cmd/schema-registry/command_schema_create.go
internal/cmd/schema-registry/command_schema_create_onprem.go
internal/cmd/schema-registry/command_schema_test.go
internal/cmd/schema-registry/command_subject_update.go
internal/cmd/schema-registry/command_subject_update_onprem.go
internal/cmd/schema-registry/schema_utilities.go
test/fixtures/input/schema-registry/schema-metadata.json
test/fixtures/input/schema-registry/schema-ruleset.json
test/fixtures/output/schema-registry/cluster/update-help.golden
test/fixtures/output/schema-registry/config/describe-global-json.golden
test/fixtures/output/schema-registry/config/describe-global-yaml.golden
test/fixtures/output/schema-registry/config/describe-global.golden
test/fixtures/output/schema-registry/config/describe-subject.golden
test/fixtures/output/schema-registry/subject/update-help.golden
test/schema_registry_test.go
test/test-server/schema_registry_handlers.go

Release Notes
-------------
New Features
- Add `--metadata` and `--ruleset` to `confluent schema-registry schema create`
- Add `--compatibility-group`, `--metadata-defaults`, `--metadata-overrides`, `--ruleset-defaults`, and `--ruleset-overrides` to `confluent schema-registry subject update`
Checklist
---------
* yes: ok
What
----
References
----------
Test & Review
-------------

[DGS-5490] Add metadata/ruleset to register, update config

---

go.mod
go.sum
internal/cmd/schema-registry/command_cluster_update.go
internal/cmd/schema-registry/command_config_describe.go
internal/cmd/schema-registry/command_schema_create.go
internal/cmd/schema-registry/command_schema_create_onprem.go
internal/cmd/schema-registry/command_schema_describe.go
internal/cmd/schema-registry/schema_utilities.go
test/fixtures/output/schema-registry/config/describe-global-json.golden
test/fixtures/output/schema-registry/config/describe-global-yaml.golden
test/fixtures/output/schema-registry/config/describe-global.golden
test/fixtures/output/schema-registry/config/describe-subject.golden
test/fixtures/output/schema-registry/schema/describe-with-ruleset.golden
test/schema_registry_test.go
test/test-server/schema_registry_handlers.go

Checklist
---------
* yes: ok
What
----
Fix bug in https://github.com/confluentinc/cli/pull/1837 to allow optional `Metadata` and `Ruleset` when registering schema and updating config. 
References
----------
Test & Review
-------------
Added some integration tests. 
Also did manual test:
- Essential package: 
```
xli@Xiaoya-Li-MBP16 ~/git/go/src/github.com/confluentinc/cli
% ./dist/confluent_darwin_amd64_v1/confluent schema-registry schema create --subject payments --schema ./test/fixtures/input/schema-registry/schema-example.json --metadata ./test/fixtures/input/schema-registry/schema-metadata.json
Enter your Schema Registry API key: M44GMXNDEWXJ6X4Y
Enter your Schema Registry API secret: …
```

DGS-5490: Show `Metadata` and `Ruleset` in schema describe

---

Makefile
debian/patches/standard_build_layout.patch

Checklist
---------
* yes: ok
What
----
On many platforms `make` is GNU Make, but not on all. On FreeBSD it isn't. As the `Makefile` is GNU Make specific let's use `gmake` to allow this to work on more platforms.
References
----------
Issue: #1674
Test & Review
-------------
Manually, see issue

Explicitly use GNU Make

---

internal/cmd/flink/command.go
internal/cmd/flink/command_compute_pool.go
internal/cmd/flink/command_shell.go
internal/pkg/ccloudv2/flink_gateway.go
internal/pkg/ccloudv2/identity_provider.go
internal/pkg/cmd/flags.go
internal/pkg/cmd/prerunner.go
internal/pkg/flink/components/interactive_input.go
internal/pkg/flink/config/env_variables.go
internal/pkg/flink/config/results.go
internal/pkg/flink/config/sql_split_tokens.go
internal/pkg/flink/internal/history/history.go
internal/pkg/flink/internal/store/store.go
internal/pkg/flink/internal/store/store_utils.go
internal/pkg/flink/internal/store/store_utils_test.go

Checklist
---------
* yes: ok
What
----
Fix feature flag, typos in error messages, and data plane auth token.
Test & Review
-------------
Manually tested

[CLI-2519] Post-release Flink fixes

---

cmd/docs/main.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
References
----------
Test & Review
-------------

[internal] Not include flink docs at `make publish-docs`

---

internal/cmd/api-key/command_create.go
internal/cmd/api-key/command_describe.go
internal/cmd/audit-log/command_config_edit.go
internal/cmd/audit-log/command_config_update.go
internal/cmd/flink/command_compute_pool.go
internal/cmd/flink/command_compute_pool_create.go
internal/cmd/flink/command_compute_pool_list.go
internal/cmd/iam/command_rbac_role_describe.go
internal/cmd/iam/command_service_account_update.go
internal/cmd/kafka/command_cluster_describe.go
internal/cmd/kafka/command_topic_update.go
internal/pkg/ccloudv2/cdx.go
internal/pkg/ccloudv2/cli.go
internal/pkg/ccloudv2/flink.go
internal/pkg/ccloudv2/flink_gateway.go
internal/pkg/ccloudv2/ksql.go
internal/pkg/ccloudv2/org.go
test/fixtures/output/flink/compute-pool/list-after-use.golden
test/fixtures/output/flink/compute-pool/list-help.golden
test/fixtures/output/flink/compute-pool/list-region.golden
test/fixtures/output/flink/compute-pool/list.golden
test/flink_test.go
test/test-server/fcpm_handlers.go

Checklist
---------
* yes: ok
What
----
Filter compute pools by region
Test & Review
-------------
Manual testing, integration tests

Add `flink compute-pool list --region`

---

cmd/lint/main.go
internal/cmd/kafka/command_topic_consume.go
internal/cmd/kafka/command_topic_consume_onprem.go
internal/cmd/kafka/command_topic_produce.go
internal/cmd/kafka/command_topic_produce_onprem.go
internal/cmd/local/command_kafka_start.go
internal/cmd/local/command_kafka_topic_consume.go
internal/cmd/local/command_kafka_topic_produce.go
internal/cmd/secret/command_file.go
internal/cmd/secret/command_file_add.go
internal/cmd/secret/command_file_decrypt.go
internal/cmd/secret/command_file_encrypt.go
internal/cmd/secret/command_file_remove.go
internal/cmd/secret/command_file_update.go
internal/pkg/cmd/flags.go
test/local_test.go

Checklist
---------
* yes: ok
What
----
Address comments from last pr. improve code stability.
Hardcoded ports for tests (assuming ports > 3000 won't work). Shortened wait time. Ran ~10 times and they all passed.
References
----------
Test & Review
-------------

[internal] [confluent local] phase 1 patch: code quality and stability of tests

---

internal/pkg/flink/internal/controller/input_controller.go

Checklist
---------
* yes: ok
What
----
Currently, the CLI print “Statement ID” after submission.
> SHOW TABLES;
Statement ID: 8c02a22f-d3ec-45c7-a
Statement successfully submitted.
Fetching results...
This should instead be Statement name: ...

feat: change output message to "Statement name: %s"

---

internal/pkg/auth/login_credentials_manager.go
internal/pkg/errors/strings.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Got one complain where user changed his password and not updated in keychain, and couldn't log in using that saved password. Our login handler can't really tell if the password has been updated but we could tell where we're getting the creds from.
References
----------
https://confluent.slack.com/archives/C010Y0EP5MZ/p1686659584367629
Test & Review
-------------

[internal] debugf information about getting creds from keychain

---

.goreleaser-linux-amd64.yml
.goreleaser-linux-arm64.yml
scripts/build_linux.sh

Checklist
---------
* yes: ok
What
----
This will make the automated release process a bit easier, since our binaries will already be present in a directory named "prebuilt/"

Build directly in `prebuilt/` directory

---

docker/Dockerfile_linux_amd64
docker/Dockerfile_linux_arm64
docker/Dockerfile_linux_arm64_from_amd64

Checklist
---------
* yes: ok
What
----
Missed a few instances of the rename from #1986

Rename dist/ to prebuilt/ for Linux release

---

internal/cmd/ksql/command.go
internal/cmd/ksql/command_cluster_delete.go
internal/pkg/auth/auth.go
internal/pkg/cmd/authenticated_cli_command.go
internal/pkg/cmd/kafka_rest_test.go
internal/pkg/cmd/prerunner.go

Checklist
---------
* yes: ok
What
----
Use the same function for all dataplane token requests. This sets us up for storing and refreshing the dataplane token in a later PR.

Consolidate dataplane token code

---

internal/pkg/secret/encryption_windows.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Changed the call to GenerateSaltAndNonce() for mac and linux, but didn't update the methods in windows build file. Update the file in here to resolve 'methods not declared' error for windows,
References
----------
Test & Review
-------------

Update nonce/salt generating methods in windows build

---

internal/cmd/local/command_kafka_topic_produce.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
For beginners who don't understand producers, print out a help info to prompt them for input after producer is started.
References
----------
Test & Review
-------------

[confluent-local] print help info when producer is started

---

internal/cmd/flink/command.go
internal/cmd/flink/command_iam_binding.go
internal/cmd/flink/command_iam_binding_create.go
internal/cmd/flink/command_iam_binding_delete.go
internal/cmd/flink/command_iam_binding_list.go
internal/pkg/ccloudv2/flink.go
internal/pkg/resource/resource.go
test/fixtures/output/flink/help.golden
test/fixtures/output/flink/iam-binding/create-environment.golden
test/fixtures/output/flink/iam-binding/create-help.golden
test/fixtures/output/flink/iam-binding/create.golden
test/fixtures/output/flink/iam-binding/delete-help.golden
test/fixtures/output/flink/iam-binding/delete.golden
test/fixtures/output/flink/iam-binding/help.golden
test/fixtures/output/flink/iam-binding/list-cloud.golden
test/fixtures/output/flink/iam-binding/list-help.golden
test/fixtures/output/flink/iam-binding/list-identity-pool.golden
test/fixtures/output/flink/iam-binding/list-region.golden
test/fixtures/output/flink/iam-binding/list.golden
test/flink_test.go
test/test-server/ccloudv2_router.go
test/test-server/fcpm_handlers.go

Checklist
---------
* yes: ok
What
----
Adds the missing commands to create, delete and list IAM bindings. All IAM binding commands are available under `confluent flink iam-binding` and are hidden behind the open-preview feature flag.

feat: add create, delete and list IAM binding commands

---

internal/cmd/flink/command.go
internal/pkg/flink/app/application.go
internal/pkg/flink/components/interactive_input.go
internal/pkg/flink/components/interactive_output.go

Release Notes
-------------
Bug Fixes
- This fixes a semantic merge conflict introduced in #2006 and replaces some non utf8 whitespaces
Checklist
---------
* yes: ok
What
----
Upon running the build on master I've noticed that some things do not build anymore.
References
----------
Test & Review
-------------

chore: fix lint problems

---

internal/pkg/flink/internal/autocomplete/.snapshots/TestSetAutoCompletionSnapshot
internal/pkg/flink/internal/autocomplete/set_completer.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
References
----------
Test & Review
-------------

fix: remove runtime mode autocompletion

---

internal/pkg/flink/internal/results/result_converter.go

Checklist
---------
* yes: ok
What
----
Remove the logs that were added in #2033

chore: remove log on result parse error

---

internal/cmd/login/command.go
test/fixtures/output/login/help-onprem.golden
test/fixtures/output/login/help.golden

Checklist
---------
* yes: ok
What
----
This flag should be considered in EA for the time being. We're unable to use a feature flag here since the user is unauthenticated.

Hide `--us-gov` flag

---

internal/cmd/flink/command_statement.go
internal/cmd/flink/command_statement_list.go
internal/pkg/ccloudv2/flink_gateway.go
internal/pkg/flink/test/mock/gateway_client_fake.go
internal/pkg/flink/test/mock/gateway_client_mock.go
internal/pkg/flink/test/mock/table_controller_mock.go
test/fixtures/output/flink/statement/list.golden
test/test-server/flink_gateway_router.go

Checklist
---------
* yes: ok
What
----
Currently the backend does not return the statement list in sorted order, so we have to sort the list in the CLI. We want the latest statement to be displayed at the bottom of the table.

[KFS-973/FLINKCC-103] order statement list by creation time

---

internal/pkg/flink/internal/store/store.go
internal/pkg/flink/internal/store/store_test.go

Checklist
---------
* yes: ok
What
----
The token refresh function is not synchronized, but we potentially access it concurrently (e.g. a user clicks fetch next page, while auto refresh is running)
Test & Review
-------------
Added a test case that should trigger the Go race detector (and should also fail in standard test mode)

fix: sync access to token refresh function

---

internal/cmd/flink/command_shell.go

Checklist
---------
* yes: ok
What
----
This has multiple problems:
- it panics when there is concurrent access
- it could potentially load a wrong token (if a user logs into another org from a different window, after the original token is expired)
- it slows requests down
So I'd say we ignore the case when a user refreshes correctly from another window and just let the user log back in

fix: do not load config file again on every token refresh

---

debian/Makefile
debian/patches/standard_build_layout.patch

Checklist
---------
* yes: ok
What
----
Re-attempting to package linux/arm64 for CP, reverts https://github.com/confluentinc/cli/pull/1533
References
----------
https://confluentinc.atlassian.net/browse/CLI-2573

[CLI-2573] Package linux/arm64 binary for CP

---

debian/Makefile
debian/patches/standard_build_layout.patch

Revert "[CLI-2573] Package linux/arm64 binary for CP"

---

internal/cmd/flink/command_shell.go
internal/pkg/config/v1/context.go
internal/pkg/config/v1/environment_context.go
internal/pkg/flink/config/local_statements.go
internal/pkg/flink/internal/store/.snapshots/TestProcessSetStatement-should_return_all_keys_and_values_from_config_if_configKey_is_empty
internal/pkg/flink/internal/store/.snapshots/TestProcessSetStatement-should_return_all_keys_and_values_from_config_if_configKey_is_empty_after_updates
internal/pkg/flink/internal/store/.snapshots/TestProcessSetStatement-should_update_config_for_valid_configKey
internal/pkg/flink/internal/store/store.go
internal/pkg/flink/internal/store/store_test.go
internal/pkg/flink/internal/store/store_utils.go
internal/pkg/flink/internal/store/store_utils_test.go
internal/pkg/flink/types/application_options.go

Checklist
---------
* yes: ok
What
----
References
----------
Test & Review
-------------

feat: persist results of `USE` statements in configs

---

internal/pkg/flink/internal/store/user_properties_test.go

Checklist
---------
* yes: ok
What
----
Whenever the getRandomKey function selected the default key, the RemoveNonDefaultKey test failed (which is to be expected). Changed the function now to only return a non-default key (which was the original purpose of the function)

test: fix flaky test in case default key is picked

---

internal/pkg/errors/error_message.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Noticed a few unused strings in the `error_message.go` file earlier in the week, so I went did a pass through this file and removed all the ones I could find.
References
----------
Test & Review
-------------

Remove unused strings

---

internal/pkg/flink/components/.snapshots/TestTableViewTestSuite-TestTableHighlightsNewRows
internal/pkg/flink/components/.snapshots/TestTableViewTestSuite-TestTableRemovesHighlightAfterDuration
internal/pkg/flink/components/table_view.go
internal/pkg/flink/components/table_view_test.go
internal/pkg/flink/internal/controller/interactive_output_controller.go
internal/pkg/flink/internal/controller/interactive_output_controller_test.go
internal/pkg/flink/test/mock/table_view_mock.go

Checklist
---------
* yes: ok
What
----
Highlights new table rows for a short amount of time, to make it easier for the user to spot which rows have changed 
https://github.com/confluentinc/cli/assets/37211050/04200e3b-5120-4c2c-ad51-4904e02029bd

feat: add highlighting for new rows

---

internal/cmd/api-key/command.go
internal/cmd/api-key/command_create.go
internal/cmd/api-key/command_list.go
internal/cmd/api-key/command_store.go
internal/cmd/api-key/command_use.go
internal/cmd/iam/command_service_account_create.go
internal/pkg/errors/README.md
internal/pkg/errors/error_message.go
internal/pkg/errors/typed.go
test/fixtures/output/api-key/create-resource-autocomplete.golden
test/fixtures/output/api-key/store-help.golden
test/fixtures/output/iam/service-account/create-help.golden
test/fixtures/output/kafka/client-config/no-keypair.golden
test/fixtures/output/login/err-no-api-key.golden

Checklist
---------
* yes: ok
What
----
* `--resource cloud` should not be suggested for `confluent api-key store`
* `--resource` should not be suggested for `confluent api-key use`

Fix API key documentation

---

internal/cmd/command.go
internal/cmd/kafka/command_topic_produce.go
internal/cmd/kafka/command_topic_produce_onprem.go
internal/cmd/schema-registry/command.go
internal/cmd/schema-registry/command_cluster_describe.go
internal/cmd/schema-registry/command_cluster_update.go
internal/cmd/schema-registry/command_compatibility_validate.go
internal/cmd/schema-registry/command_config_describe.go
internal/cmd/schema-registry/command_exporter_create.go
internal/cmd/schema-registry/command_exporter_delete.go
internal/cmd/schema-registry/command_exporter_describe.go
internal/cmd/schema-registry/command_exporter_getconfig.go
internal/cmd/schema-registry/command_exporter_getstatus.go
internal/cmd/schema-registry/command_exporter_list.go
internal/cmd/schema-registry/command_exporter_pause.go
internal/cmd/schema-registry/command_exporter_reset.go
internal/cmd/schema-registry/command_exporter_resume.go
internal/cmd/schema-registry/command_exporter_update.go
internal/cmd/schema-registry/command_schema_create.go
internal/cmd/schema-registry/command_schema_create_onprem.go
internal/cmd/schema-registry/command_schema_delete.go
internal/cmd/schema-registry/command_schema_describe.go
internal/cmd/schema-registry/command_schema_list.go
internal/cmd/schema-registry/command_subject_describe.go
internal/cmd/schema-registry/command_subject_list.go
internal/cmd/schema-registry/command_subject_update.go
internal/cmd/schema-registry/credentials.go
internal/cmd/schema-registry/schema_utilities.go
internal/pkg/dynamic-config/dynamic_context_test.go
internal/pkg/errors/strings.go

Checklist
---------
* yes: ok
What
----
Setting up the Schema Registry code to be easier to work with.

Schema Registry refactors

---

internal/cmd/kafka/command_topic.go

Release Notes
-------------
Bug Fixes
- Improve error message when no API secret is provided to `confluent kafka client-config create`
Checklist
---------
* yes: ok
What
----
Caught by system tests, lost some error message coverage in #2115.
Test & Review
-------------
Validated that system tests pass

Error if missing secret in `kafka client-config create`

---

internal/pkg/featureflags/feature_flags.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
`"WARNING: Failed to fetch feature flags."` shows up multiple times when running `lint` or `docs`, and occasionally causes flakiness in the integration tests.
This PR just skips reporting the warning and suggestion if `cfg.IsTest` is true.
References
----------
Test & Review
-------------

[CLI-2564] Remove misleading feature flag warning when running test/lint/docs

---

cmd/lint/main.go
internal/cmd/local/command_service.go
test/fixtures/output/local/services/kafka/start-help-onprem.golden
test/fixtures/output/local/services/kafka/start-help.golden

… local kafka
Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
What it says in the title.
References
----------
Test & Review
-------------

Add long description to `confluent local services kafka start` suggesting that users use the new local kafka

---

go.mod
go.sum
internal/cmd/flink/command_compute_pool_update.go
test/fixtures/output/flink/compute-pool/update-help.golden

Release Notes
-------------
Checklist
---------
* yes: ok
What
----
Name of a flink compute pool is now editable
References
----------
Test & Review
-------------

feat: compute pool name is editable

---

internal/cmd/kafka/command_acl.go
internal/cmd/kafka/command_acl_create.go
internal/cmd/kafka/command_acl_create_onprem.go
internal/cmd/kafka/command_acl_delete_onprem.go
internal/cmd/kafka/command_acl_list.go
internal/cmd/kafka/command_acl_list_onprem.go
internal/cmd/kafka/kafka_api.go
internal/pkg/acl/acl.go
internal/pkg/acl/acl_test.go
internal/pkg/errors/error_message.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Undoing the last reversion while we sort out how we want to proceed here.
References
----------
Test & Review
-------------

Revert "Revert ACL changes to handle integer IDs (#2181)"

---

internal/cmd/plugin/command_install.go
test/fixtures/output/plugin/help-onprem.golden
test/fixtures/output/plugin/help.golden
test/fixtures/output/plugin/install-help-onprem.golden
test/fixtures/output/plugin/install-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Mention that this command can be used to update a plugin. This came up because a user needed to reinstall after we fixed a bug in one of the plugins.
References
----------
Test & Review
-------------

Update documentation for `confluent plugin install`

---

cmd/docs/main.go
mk-files/docs.mk
mk-files/release-test.mk

Checklist
---------
* yes: ok
What
----
Typos in make targets, and docs generation improvements!

Release fixes

---

internal/pipeline/command_activate.go
internal/pipeline/command_deactivate.go
internal/pipeline/command_update.go
internal/schema-registry/command_exporter_delete.go
pkg/ccloudv2/stream_designer.go
test/fixtures/output/schema-registry/exporter/delete-help-onprem.golden
test/fixtures/output/schema-registry/exporter/delete-help.golden

Checklist
---------
* yes: ok
What
----
* Fix call style for pipeline SDK
* Fix usage of `schema-registry exporter delete`
Test & Review
-------------

Post-release fixes

---

debian/Makefile
debian/control
debian/patches/standard_build_layout.patch

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Improvements in platform support
Reverts confluentinc/cli#2219

Revert "Try adding linux/arm64 support for CP" for CP 7.5 release

---

internal/plugin/command.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug causing `confluent plugin search` and `confluent plugin install` to fail
Checklist
---------
* yes: ok
What
----
URL accidentally got changed at some point.
References
----------
Test & Review
-------------
I'll be adding system tests as a followup.

Fix plugin repo url typo

---

mk-files/release.mk

Checklist
---------
* yes: ok
What
----
Introduce a new target to update the packaging repo with the current CLI version after every release.
Test & Review
-------------
Tested with `DRY_RUN=true`.

[CLI-2710] Update packaging during release

---

pkg/ccloudv2/flink_gateway.go
pkg/ccloudv2/utils.go

Release Notes
-------------
Checklist
---------
* yes: ok
What
----
- Make sure that flink gateway client can follow redirection from Flink gateway. 
- Modify the underlying retryable HTTP client used in construction of Flink gateway client to make sure that we follow redirects correctly including all headers.
References
----------
Test & Review
-------------
Sample redirect
```
{"api_version":"sql/v1alpha1","kind":"Statement","metadata":{"created_at":"2023-08-31T21:21:21Z","self":"https://flink.eu-west-1.aws.devel.cpdev.cloud/sql/v1alpha1/environments/env-xx5q1x/statements/2ee6d357-3e8f-40aa"},"spec":{"compute_pool_id":"lfcp-devcc5dvoj8","identity_pool_i …
```

[FCP-919] Handle redirection from flink gateway endpoints

---

mk-files/release.mk

Checklist
---------
* yes: ok
What
----
As of CP 7.5, two new files were added: https://github.com/confluentinc/muckrake/pull/2100/files

Add new files to `make update-muckrake` target

---

cmd/docs/main.go

Checklist
---------
* yes: ok
What
----
Requested by @JimGalasyn, approved by @kasher-confluent. Will make a follow-up docs PR in a few minutes to get these added.

Un-hide Flink docs

---

cmd/lint/main.go
go.mod
go.sum
internal/organization/command_describe.go
internal/organization/command_list.go
internal/organization/command_update.go
test/fixtures/output/organization/describe-json.golden
test/fixtures/output/organization/describe.golden
test/fixtures/output/organization/list-json.golden
test/fixtures/output/organization/list.golden
test/fixtures/output/organization/update-help.golden
test/fixtures/output/organization/update-json.golden
test/fixtures/output/organization/update.golden
test/test-server/org_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Add `--jit-enabled` to allow customer to toggle the JUST-IN-TIME for SSO enabled organization
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
References
----------
Test & Review
-------------

Identity-2952 add jit_enabled to organization CLI

---

internal/network/command.go
internal/network/command_transit_gateway_attachment.go
internal/network/command_transit_gateway_attachment_describe.go
internal/network/command_transit_gateway_attachment_list.go
pkg/ccloudv2/networking.go
test/fixtures/output/network/help.golden
test/fixtures/output/network/transit-gateway-attachment/describe-autocomplete.golden
test/fixtures/output/network/transit-gateway-attachment/describe-help.golden
test/fixtures/output/network/transit-gateway-attachment/describe-invalid.golden
test/fixtures/output/network/transit-gateway-attachment/describe-json.golden
test/fixtures/output/network/transit-gateway-attachment/describe-missing-id.golden
test/fixtures/output/network/transit-gateway-attachment/describe.golden
test/fixtures/output/network/transit-gateway-attachment/help.golden
test/fixtures/output/network/transit-gateway-attachment/list-help.golden
test/fixtures/output/network/transit-gateway-attachment/list-json.golden
test/fixtures/output/network/transit-gateway-attachment/list.golden
test/network_test.go
test/test-server/ccloudv2_router.go
test/test-server/networking_handlers.go

What
----
* Add `confluent network transit-gateway-attachment list`
* Add `confluent network transit-gateway-attachment describe`
* Add `confluent network tgw-attachment` alias 
References
----------
Test & Review
------------- …

[TRAFFIC-9323][TRAFFIC-9324] - Add `confluent network transit-gateway-attachment list|describe` commands

---

internal/plugin/command_list.go
pkg/featureflags/feature_flags.go
test/fixtures/output/plugin/list-disabled.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Since we now have a `confluent configuration update` command, we should no longer suggest direct modification of `config.json` in our suggestions.
References
----------
Test & Review
-------------

Remove suggestions to directly modify config.json

---

internal/iam/command_rbac.go
internal/iam/command_rbac_role_describe.go
internal/iam/command_rbac_role_list.go
test/fixtures/output/iam/rbac/role/list-cloud.golden

Checklist
---------
* yes: ok   * no: DO NOT MERGE until the required features are live in prod  
What
----
References
----------
Test & Review
-------------

added workload namspace to be loaded using flink OP flag

---

pkg/flink/internal/store/store_test.go
pkg/flink/internal/store/store_utils.go
pkg/flink/internal/store/store_utils_test.go

Checklist
---------
* yes: ok
What
----
- require catalog to be set before setting a database
- require user to set the catalog and the database with USE/disallow setting those props with SET command
- remove the database when the catalog is changed or reset

[KFS-1171][KFS-1172] local statement fixes

---

pkg/flink/internal/results/converter.go
pkg/flink/internal/results/result_formatter_test.go
pkg/flink/internal/store/store_utils.go
pkg/flink/test/mock/gateway_client_mock.go
pkg/flink/types/result_fields.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
References
----------
Test & Review
-------------

bugfix: fix confusing import names

---

internal/flink/command_compute_pool_create.go
test/fixtures/output/flink/compute-pool/create-help.golden

Checklist
---------
* yes: ok
What
----
Updating the suggestion was missed when changing CFUs to be a multiple of 5.

fix: change CFU suggestion from 2 to 5

---

internal/flink/command_compute_pool_update.go
test/fixtures/output/flink/compute-pool/update-after-use.golden
test/fixtures/output/flink/compute-pool/update-help.golden
test/fixtures/output/flink/compute-pool/update.golden
test/flink_test.go

Small doc detail we forgot here https://github.com/confluentinc/cli/pull/2287

docs: update examples for default max cfu

---

internal/flink/command_shell.go
test/fixtures/output/flink/shell-help.golden

Checklist
---------
* yes: ok
What
----
- removed the identity pool flag, which we no longer need 
- also removed the output flag which is not used by the flink shell command

chore: remove identity pool and output flag

---

pkg/cmd/flagsets.go
test/fixtures/output/kafka/acl/create-help-onprem.golden
test/fixtures/output/kafka/acl/delete-help-onprem.golden
test/fixtures/output/kafka/acl/list-help-onprem.golden
test/fixtures/output/kafka/broker/delete-help-onprem.golden
test/fixtures/output/kafka/broker/describe-help-onprem.golden
test/fixtures/output/kafka/broker/get-tasks-help-onprem.golden
test/fixtures/output/kafka/broker/list-help-onprem.golden
test/fixtures/output/kafka/broker/update-help-onprem.golden
test/fixtures/output/kafka/link/configuration/list-help-onprem.golden
test/fixtures/output/kafka/link/configuration/update-help-onprem.golden
test/fixtures/output/kafka/link/create-help-onprem.golden
test/fixtures/output/kafka/link/delete-help-onprem.golden
test/fixtures/output/kafka/link/describe-help-onprem.golden
test/fixtures/output/kafka/link/list-help-onprem.golden
test/fixtures/output/kafka/partition/describe-help-onprem.golden
test/fixtures/output/kafka/partition/list-help-onprem.golden
test/fixtures/output/kafka/partition/reassignment/list-help-onprem.golden
test/fixtures/output/kafka/replica/list-help-onprem.golden
test/fixtures/output/kafka/replica/no-flags-error.golden
test/fixtures/output/kafka/topic/create-help-onprem.golden
test/fixtures/output/kafka/topic/create-negative-partitions.golden
test/fixtures/output/kafka/topic/create-negative-replication-factor.golden
test/fixtures/output/kafka/topic/delete-help-onprem.golden
test/fixtures/output/kafka/topic/describe-help-onprem.golden
test/fixtures/output/kafka/topic/list-help-onprem.golden
test/fixtures/output/kafka/topic/update-help-onprem.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Some grammar changes.
References
----------
Test & Review
-------------

v3.34.0 Docs review

---

pkg/cmd/token_validator.go

Release Notes
-------------
Bug Fixes
- https://confluentinc.atlassian.net/browse/FLINKCC-364
Checklist
---------
* **yes**: ok
What
----
https://confluentinc.atlassian.net/browse/FLINKCC-364
References
----------
Test & Review
-------------

[FLINKCC-364] Add a time buffer to the token validator

---

cmd/lint/main.go
go.mod
go.sum
internal/network/command.go
internal/network/command_ip_address.go
internal/network/command_ip_address_list.go
pkg/ccloudv2/client.go
pkg/ccloudv2/networking_ip.go
test/fixtures/output/network/help.golden
test/fixtures/output/network/ip-address/help.golden
test/fixtures/output/network/ip-address/list-help.golden
test/fixtures/output/network/ip-address/list-json.golden
test/fixtures/output/network/ip-address/list.golden
test/network_test.go
test/test-server/ccloudv2_router.go
test/test-server/networking_handlers.go

What
----
* Add `confluent network ip-address`
* Add `confluent network ip-address list`
References
----------
Test & Review
-------------

[TRAFFIC-9336]: Add `confluent network ip-address list` command

---

internal/ksql/command_cluster_configureacls.go
test/fixtures/output/ksql/cluster/configure-acls-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Adding an example per user's ask.
References
----------
Test & Review
-------------

[CLI-2563] add example in confluent ksql cluster configureacls

---

internal/flink/command.go
internal/flink/command_compute_pool.go
internal/flink/command_compute_pool_create.go
internal/flink/command_compute_pool_delete.go
internal/flink/command_compute_pool_use.go
internal/flink/command_region_list.go
internal/flink/command_region_use.go
test/fixtures/output/flink/compute-pool/create-cloud-autocomplete.golden
test/fixtures/output/flink/compute-pool/create-region-autocomplete.golden
test/fixtures/output/flink/compute-pool/delete-autocomplete.golden
test/fixtures/output/flink/compute-pool/list-region-autocomplete.golden
test/fixtures/output/flink/region/list-help.golden
test/fixtures/output/flink/region/use-autocomplete.golden
test/fixtures/output/flink/region/use-help.golden
test/fixtures/output/flink/shell-help.golden
test/fixtures/output/flink/statement/create-database-autocomplete.golden
test/fixtures/output/flink/statement/create-help.golden
test/flink_test.go

Checklist
---------
* yes: ok
What
----
Certain Flink commands had been written to autocomplete with the wrong resource, or were broken (returned no results). Fixed and tested all instances, and added additional autocompletion for `--database`.
Test & Review
-------------
Integration tests, manual testing

Fix and test Flink autocomplete

---

internal/connect/command_custom_plugin.go
internal/kafka/command_quota.go
internal/stream-share/command_consumer_redeem.go
internal/stream-share/command_consumer_share_describe.go
test/fixtures/output/connect/custom-plugin/describe-with-sensitive-properties.golden
test/fixtures/output/kafka/quota/create.golden
test/fixtures/output/kafka/quota/describe.golden
test/fixtures/output/kafka/quota/list.golden
test/fixtures/output/kafka/quota/update.golden
test/fixtures/output/stream-share/consumer/redeem-private-link.golden
test/fixtures/output/stream-share/consumer/share/describe.golden

Checklist
---------
* yes: ok
What
----
Delimit all lists with ", " instead of "," in all human output, will wait until v4 to fix serialized output
Test & Review
-------------
Integration tests

Delimit lists in human output with ", " instead of ","

---

internal/flink/command.go
internal/flink/command_shell.go
test/fixtures/output/flink/shell-help.golden

Release Notes
-------------
Checklist
---------
* yes: ok
What
----
We've hidden a debugging mode we use behind a local const instead of cfg.isTest so it's not shown in the docs.
References
----------
Test & Review
-------------

fix: put --fake-gateway behind local const

---

internal/flink/command_statement_list.go
test/fixtures/output/flink/statement/list-help.golden

Release Notes
-------------
Bug Fixes
- fixes typo
Checklist
---------
What
----
fix typo
References
----------
Test & Review
-------------

fix typo in `confluent flink statement list` example

---

internal/stream-share/command_consumer_redeem.go
internal/stream-share/command_consumer_share.go
internal/stream-share/command_consumer_share_describe.go
internal/stream-share/command_consumer_share_list.go
test/fixtures/output/stream-share/consumer/redeem-private-link.golden
test/fixtures/output/stream-share/consumer/redeem.golden
test/fixtures/output/stream-share/consumer/share/describe.golden

Checklist
---------
* yes: ok
What
----
Follow up to https://github.com/confluentinc/cli/pull/2351, this time with the "Resources" and "Network Zonal Subdomains" fields of the `confluent stream-share` commands.
Test & Review
-------------

Use comma delimited string for human stream share output

---

cmd/docs/main.go

Checklist
---------
What
----
These commands are EA, so we should unhide docs.

Enable `iam group-mapping` docs

---

.github/pull_request_template.md
internal/api-key/command_create.go
internal/api-key/command_list.go
internal/context/command_update.go
internal/iam/command_rbac_role_binding.go
internal/kafka/utils.go
internal/ksql/command_cluster_create.go
internal/local/command_kafka.go
pkg/ccloudv2/iam.go
pkg/ccloudv2/kafka_quotas.go
pkg/ccloudv2/kafkarest.go
pkg/ccloudv2/service_quota.go
pkg/ccloudv2/srcm.go
pkg/ccloudv2/sso.go
pkg/ccloudv2/stream_designer.go
pkg/config/config.go
pkg/config/context.go
pkg/config/context_state.go
pkg/dynamic-config/dynamic_context.go
pkg/featureflags/feature_flags.go
test/fixtures/output/ksql/cluster/create-help.golden
test/fixtures/output/ksql/cluster/create-result-missing-credential-identity.golden
test/test-server/iam_handlers.go

Checklist
---------
What
----
Remove some user-facing panics, add example for `confluent ksql cluster create`, formatting fixes
Test & Review
-------------

Remove panics, add missing examples, and more

---

internal/flink/command_compute_pool_unset.go
test/fixtures/output/flink/compute-pool/unset-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
What it says in the title
References
----------
Test & Review
-------------

Fix typo in `flink compute-pool unset` description

---

debian/Makefile
debian/control
debian/patches/standard_build_layout.patch

Checklist
---------
What
----
Support packaging linux/arm64 for Debian and RPM in CP

[CLI-2573] Package linux/arm64 for DEB/RPM in CP

---

debian/Makefile
debian/control
debian/patches/standard_build_layout.patch

Revert "[CLI-2573] Package linux/arm64 for DEB/RPM in CP"

---

service.yml

What
----
Required that we add this before #2455 can pass tests

Enable Semaphore

---

internal/flink/command_compute_pool.go
internal/flink/command_compute_pool_create.go
internal/flink/command_compute_pool_describe.go
internal/flink/command_compute_pool_list.go
internal/flink/command_compute_pool_update.go
test/fixtures/output/flink/compute-pool/create.golden
test/fixtures/output/flink/compute-pool/describe-after-use.golden
test/fixtures/output/flink/compute-pool/describe.golden
test/fixtures/output/flink/compute-pool/list-after-use.golden
test/fixtures/output/flink/compute-pool/list-region.golden
test/fixtures/output/flink/compute-pool/list.golden
test/fixtures/output/flink/compute-pool/update-after-use.golden
test/fixtures/output/flink/compute-pool/update.golden
test/test-server/fcpm_handlers.go

Revert "feat: add cloud provider to output for compute pool commands"

---

internal/iam/command_groupmapping_create.go
test/fixtures/output/iam/group-mapping/create-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

Fix example for group mapping creation cli

---

pkg/cmd/flags.go
test/fixtures/output/kafka/1.golden
test/fixtures/output/kafka/cluster/create-help.golden

Checklist
---------
What
----
There is GCP support for BYOK now. Update documentation.

Fix BYOK docs

---

pkg/schemaregistry/client.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a `401 Unauthorized` bug for Confluent Platform `confluent schema-registry` commands
Checklist
---------
What
----
References
----------
Test & Review
-------------

Use cfg context auth token for on-prem schema registry client

---

.gitignore
service.yml

This is a routine update from cc-service-bot based on the service.yml in your repo. This PR
should be approved and merged as soon as CI passes.

chore: update repo by service bot

---

.gitignore
internal/iam/command_rbac_role_binding_create.go
test/fixtures/output/iam/rbac/role-binding/create-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Cloud cluster needs to be specified in addition to kafka cluster even though they're the same.
Also put vendor back into .gitignore, which keeps getting removed by automation.
References
----------
Test & Review
-------------

Fix example typo in `confluent iam rbac rb create`

---

.gitignore

Revert "chore: update repo by service bot"

---

pkg/flink/internal/controller/.snapshots/TestInteractiveOutputControllerTestSuite-TestTableTitleDisplaysChangelogMode
pkg/flink/internal/controller/.snapshots/TestInteractiveOutputControllerTestSuite-TestTableTitleDisplaysComplete
pkg/flink/internal/controller/.snapshots/TestInteractiveOutputControllerTestSuite-TestTableTitleDisplaysFailed
pkg/flink/internal/controller/.snapshots/TestInteractiveOutputControllerTestSuite-TestTableTitleDisplaysPageSizeAndCacheSizeWithUnsafeTrace
pkg/flink/internal/controller/.snapshots/TestInteractiveOutputControllerTestSuite-TestTableTitleDisplaysPaused
pkg/flink/internal/controller/.snapshots/TestInteractiveOutputControllerTestSuite-TestTableTitleDisplaysRunning
pkg/flink/internal/controller/.snapshots/TestInteractiveOutputControllerTestSuite-TestTableTitleDisplaysTableMode
pkg/flink/internal/controller/interactive_output_controller.go
pkg/flink/internal/controller/interactive_output_controller_test.go

Release Notes
-------------
New Features
- [Early Access] Add statement name to title of interactive results view in `confluent flink shell`
Checklist
---------
What
----
Adds the statement name to the title of the interactive results view:
table mode:
changelog mode:
References
----------
Test & Review
-------------

feat: add statement name to interactive results view

---

internal/iam/command.go
internal/iam/command_ipfilter_update.go
internal/iam/command_ipgroup_update.go
pkg/types/set.go
pkg/types/set_test.go
test/fixtures/output/iam/ip-filter/update-resource-add-and-remove.golden
test/fixtures/output/iam/ip-filter/update-resource-duplicate.golden
test/fixtures/output/iam/ip-filter/update-resource-remove-not-exist.golden
test/fixtures/output/iam/ip-group/update-resource-add-and-remove.golden
test/fixtures/output/iam/ip-group/update-resource-duplicate.golden
test/fixtures/output/iam/ip-group/update-resource-remove-not-exist.golden

Checklist
---------
What
----
There is a lot of logic involving the `--add-*` and `--delete-*` flags that can be extracted out into a separate function!
Test & Review
-------------
Added unit tests.

Add helper and unit test `--add` and `--delete` flags

---

internal/flink/command_shell.go
pkg/flink/app/application.go
pkg/flink/types/application_options.go
test/fixtures/output/flink/shell-help.golden

Release Notes
-------------
Checklist
---------
What
----
The language service is now enabled by default when running confluent flink shell.
References
----------
Test & Review
-------------

chore: remove language service flag

---

.gitignore
README.md
mk-files/release.mk

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Currently a draft PR because I still need to update the release script to add the `.deb` and `.rpm` file checksums to the checksum text file.
References
----------
Test & Review
-------------

Update `README.md` with APT/YUM installation instructions

---

CONTRIBUTING.md
pkg/errors/README.md
pkg/output/README.md

What
----
Clear up some ambiguity around how user-facing strings should be formatted.

Add README.md for pkg/output

---

internal/kafka/command_topic_produce.go
test/fixtures/output/kafka/topic/produce-help-onprem.golden
test/fixtures/output/kafka/topic/produce-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

Fix `topic produce` example text

---

go.mod
go.sum
internal/network/command.go
internal/network/command_create.go
internal/network/command_network_link_endpoint.go
internal/network/command_network_link_endpoint_create.go
internal/network/command_network_link_endpoint_update.go
internal/network/command_network_link_service.go
internal/network/command_network_link_service_create.go
internal/network/command_network_link_service_update.go
internal/network/command_peering.go
internal/network/command_peering_create.go
internal/network/command_peering_update.go
internal/network/command_private_link_access.go
internal/network/command_private_link_access_create.go
internal/network/command_private_link_access_test.go
internal/network/command_private_link_access_update.go
internal/network/command_transit_gateway_attachment.go
internal/network/command_transit_gateway_attachment_create.go
internal/network/command_transit_gateway_attachment_update.go
internal/network/command_update.go
pkg/ccloudv2/client.go
pkg/ccloudv2/networking.go
test/test-server/networking_handlers.go

What
----
- Update networking SDKs to pick up changes for `MultipleSearchFilter` and minispec updates
- networking -> v0.10.0 
- networking-ip -> v0.2.0
- networking-privatelink -> v0.2.0
References
----------
Test & Review
-------------

Update Networking SDKs

---

test/fixtures/output/local/kafka/topic/describe.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
More kafka topic configs are being returned in `confluent local kafka topic describe`, so this PR updates the golden file to fix the test.
References
----------
Test & Review
-------------

Fix `confluent local` test

---

pkg/flink/internal/store/store_test.go
pkg/flink/types/statement.go
test/fixtures/output/flink/statement/create-no-name-yaml.golden

Release Notes
-------------
Checklist
---------
What
----
Updated the format of the statement name to be in line with the terraform and workspace client.
References
----------
Test & Review
-------------

feat: generate statement names with format cli-date-time-uuid

---

internal/iam/command_rbac_role_binding_list.go
test/fixtures/output/iam/rbac/role-binding/list-user-clusteradmin-cloud.golden
test/fixtures/output/iam/rbac/role-binding/list-user-clusteradmin-json-cloud.golden
test/fixtures/output/iam/rbac/role-binding/list-user-clusteradmin-yaml-cloud.golden
test/fixtures/output/iam/rbac/role-binding/list-user-envadmin-cloud.golden
test/fixtures/output/iam/rbac/role-binding/list-user-orgadmin-cloud.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- Role bindings for "User" principals in `confluent iam rbac role-binding list` will now show the "Name" of the user
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

Show user full name in `confluent iam rbac role-binding list`

---

go.mod
go.sum
internal/network/command.go
internal/network/command_list.go
test/fixtures/output/network/delete-autocomplete.golden
test/fixtures/output/network/describe-autocomplete.golden
test/fixtures/output/network/describe-gateway-json.golden
test/fixtures/output/network/describe-gateway.golden
test/fixtures/output/network/list-json.golden
test/fixtures/output/network/list.golden
test/fixtures/output/network/peering/create-autocomplete.golden
test/fixtures/output/network/private-link/access/create-autocomplete.golden
test/fixtures/output/network/transit-gateway-attachment/create-autocomplete.golden
test/fixtures/output/network/update-autocomplete.golden
test/network_test.go
test/test-server/networking_handlers.go

What
----
Note that this is merging into the feature branch https://github.com/confluentinc/cli/tree/traffic-10544-dnsforwarder. We will merge commits into main from this feature branch after all of the commands for dns forwarder are implemented.
- Add `gateway` to `confluent network list/describe`
References
----------
[DNS Peering for Managed Connectors](https://confluentinc.atlassian.net/wiki/spaces/CIRE/pages/2947056320/1-Pager+--+DNS+peering+for+managed+connectors)
Test & Review
-------------
Added integration tests
Manual tests

[TRAFFIC-10544] Add gateway to network list/describe

---

internal/feedback/command.go

Checklist
---------
What
----
We received feedback with "\n", but this should be considered empty feedback.
Test & Review
-------------
Tested in staging

Don't accept feedback with tabs/newlines/spaces only

---

internal/network/command.go
test/fixtures/output/network/describe-aws-privatelink-provisioning-json.golden
test/fixtures/output/network/describe-aws-privatelink-provisioning.golden
test/fixtures/output/network/describe-aws-privatelink-ready-json.golden
test/fixtures/output/network/describe-aws-privatelink-ready.golden
test/fixtures/output/network/describe-aws-provisioning-yaml.golden
test/fixtures/output/network/describe-aws-provisioning.golden
test/fixtures/output/network/describe-aws-ready-yaml.golden
test/fixtures/output/network/describe-aws-ready.golden
test/fixtures/output/network/update.golden
test/test-server/networking_handlers.go

Release Notes
-------------
New Features
- Add "Idle Since" column to `confluent network` commands
Checklist
---------
What
----
This PR adds `idle_since` to network CLI output. 
References
----------
https://github.com/confluentinc/api/pull/1332
Test & Review
-------------

Add idle_since to network output

---

internal/flink/command.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Enable feature flag `cli.flink_artifact.early_access` for flink artifact command
Test & Review
-------------

SCP-1904 create UDF EA-specific LD flag for Flink Artifact CLI

---

pkg/auth/sso/auth0_utils.go
pkg/auth/sso/auth_state.go

Release Notes
-------------
Checklist
---------
What
----
Updates the okta config to use the new okta tenant.
References
----------
https://confluentinc.atlassian.net/browse/IDENTITY-3533
Test & Review
-------------
```
./confluent login --url https://infra.confluentgov-internal.com                                  ✔ │ 1.21.5 Go │ system Node │ 11:18:45 AM
Enter your Confluent Cloud credentials:
Email: ndeloney@confluentgov.com
Logged in as "ndeloney@confluentgov.com" for organization "3ef286ab-1740-4101-99f9-b2a4c6f3af60" ("confluent").

Identity-3533 Update infra-us-gov okta configs

---

go.mod
go.sum
pkg/flink/internal/controller/input_controller.go

Release Notes
-------------
New Features
- Down arrow can be used to enter the completion list in `confluent flink shell`.
Checklist
---------
What
----
Enabled arrow down to enter the completion list apart from tab.
References
----------
Test & Review
-------------

feat: enable completion on down

---

pkg/flink/README.md

Release Notes
-------------
Checklist
---------
What
----
Updating old prop name as it's currently in code and documented here client.results-timeout
References
----------
Test & Review
-------------

refactor: 1-liner rename local prop in flink readme

---

pkg/flink/internal/controller/input_controller.go

Release Notes
-------------
New Features
- support `Ctrl + Left`, `Ctrl + Right` and `Ctrl + Backspace` shortcuts on Windows in `confluent flink shell`
Checklist
---------
What
----
References
----------
Test & Review
-------------

fix: support leftWord, rightWord, deleteWord shortcuts on Windows

---

internal/flink/command_region_use.go
test/fixtures/output/flink/region/use-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

DOCS-27920: Fix description in confluent flink region use command

---

internal/api-key/command_create.go

Checklist
---------
What
----
The backend needs a different HTTP body.
References
----------
https://confluentinc.atlassian.net/browse/API-1860
Test & Review
-------------
Manually tested in staging

API-1860: Update HTTP body for `api-key create --resource flink`

---

internal/schema-registry/command_kek_create.go
pkg/cmd/flags.go
test/fixtures/output/schema-registry/kek/create-help-onprem.golden
test/fixtures/output/schema-registry/kek/create-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
`--kms-type` is required so it should not have a default value. Also fix suggested values.
References
----------
Test & Review
-------------

Fix `schema-registry kek create` flags

---

pkg/auth/sso/auth0_utils.go

Checklist
---------
What
----
```
% confluent login --url https://devel.confluentgov-internal.com
Logged in as "bstrauch@confluentgov.com" for organization "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" ("Confluent").
```
References
----------
Test & Review
-------------

Enable devel-us-gov login

---

mk-files/release.mk

What
----
Re-open the PR if closed, add `|| true` since pre-commit returns false if there are errors
References
----------
Test & Review
-------------
Reran and it worked

Fix `make update-muckrake`

---

internal/flink/command_artifact_create.go
internal/flink/command_artifact_list.go
test/test-server/connect_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- rename flink artifact type from flink-udf to flink_udf
Checklist
---------
What
----
References
----------
Test & Review
-------------

rename flink artifact type from flink-udf to flink_udf

---

internal/kafka/command_consumer_group_lag_describe.go
internal/kafka/command_consumer_group_lag_list.go
internal/kafka/command_consumer_group_lag_summarize.go
test/fixtures/output/kafka/consumer/group/lag/describe-help.golden
test/fixtures/output/kafka/consumer/group/lag/list-help.golden
test/fixtures/output/kafka/consumer/group/lag/summarize-help.golden

Checklist
---------
What
----
These commands should mention that they are restricted to dedicated clusters.
Test & Review
-------------

Update description of `kafka consumer group lag` commands

---

pkg/auth/sso/auth0_utils.go
pkg/auth/sso/auth0_utils_test.go
pkg/auth/sso/auth_state.go
pkg/auth/sso/auth_state_test.go
pkg/ccloudv2/utils_test.go
pkg/config/config_test.go

What
----
CPD is deprecated and can be removed
Test & Review
-------------
Updated unit tests

Remove references to CPD

---

internal/connect/command_custom_plugin_list.go
test/fixtures/output/connect/custom-plugin/list-json.golden
test/fixtures/output/connect/custom-plugin/list-yaml.golden
test/fixtures/output/connect/custom-plugin/list.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- [Early Access] Exclude Flink UDF artifacts in `confluent connect custom-plugin list`
Checklist
---------
What
----
References
----------
Test & Review
-------------

List Custom Connect plugins should exclude flink-udf artifacts

---

mk-files/release.mk

What
----
Need to update packaging/resources/config.yml to prepare for transition to Semaphore
References
----------
Test & Review
-------------
```
--- a/packaging/resources/config.yml
+++ b/packaging/resources/config.yml
@@ -3,7 +3,7 @@ CP_VERSION: "7.7.0-0"
CONFLUENT_PACKAGE_PREFIX: "confluent"
PACKAGE_MIN_FILE_SIZE_BYTES: 10000
COMPONENT_BRANCHES:
-  cli: "v3.57.0"
+  cli: "v3.59.0"
avro-c: "v1.8.0"
avro-cpp: "v1.8.0"
librdkafka: "v1.8.2"
```

Add additional line to `make update-packaging`

---

mk-files/release.mk

What
----
The name of this file was changed here: https://github.com/confluentinc/packaging/pull/1248
References
----------
Test & Review
-------------

Fix `make update-packaging`

---

pkg/auth/sso/auth0_utils.go
pkg/auth/sso/auth0_utils_test.go

Checklist
---------
What
----
Support production URLs in recovery regions such as prod-us-gov-east-1.
References
----------
Test & Review
-------------

Support prod-us-gov recovery region URLs

---

internal/flink/command_compute_pool_delete.go

Release Notes
-------------
Checklist
---------
What
----
Cleaning up statement retention time feature flag. Change is live for all customers.
References
----------
Test & Review
-------------

chore: remove retention time feature flag

---

mk-files/release.mk
scripts/build_linux.sh

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
To match updated release process. Intended to be run after a new release containing deb/rpm files has been published to GH.
run with `make update-package-managers`
If you don't use `DRY_RUN=true`, _this will sync to the prod directories_
References
----------
Test & Review
-------------
Tested w/ dry run.

Update APT/YUM release script

---

pkg/config/config.go
pkg/config/context_state.go
pkg/secret/encryption_windows.go
pkg/secret/password_protection_constants.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

Add prefix for encrypted Windows auth tokens

---

internal/flink/command_statement_list.go
pkg/errors/catcher.go
test/fixtures/output/flink/statement/list-cp-incorrect-region.golden
test/fixtures/output/flink/statement/list-cp-not-found.golden
test/flink_test.go

Release Notes
-------------
Bug Fixes
- `confluent flink statement list` improve error messages when compute pool cannot be found
Checklist
---------
What
----
Improved the error messages when a compute pool is not found when trying to list statements.
**before**:
```
❯ confluent flink statement list --cloud aws --region eu-west-1 --compute-pool lfcp-devc5ow86n --environment env-abc
None found.
```
**after**:
```
❯ confluent flink statement list --cloud aws --region eu-west-1 --compute-pool lfcp-devc5ow86n --environment env-abc
Error: Flink compute pool "lfcp-devc5ow86n" not found or access forbidden: Resource Not Found
Suggestions:
List available Flink compute pools with `confluent flink compute-pool list`.
Make sure you have selected the compute pool's environment with `confluent …
```

[KFS-2204] validate provided compute pool in flink statement list cmd

---

go.mod
go.sum

Release Notes
-------------
Checklist
---------
What
----
We're using a weird version of this dependency. Looking at the tags of that repo, we should be using v1.0.1 instead https://github.com/texttheater/golang-levenshtein/tags
References
----------
Test & Review
-------------

chore: update levenshtein dependency

---

internal/flink/command_artifact.go
internal/flink/command_artifact_create.go
internal/flink/command_artifact_delete.go
internal/flink/command_artifact_describe.go
test/fixtures/output/flink/artifact/create-help.golden
test/flink_test.go
test/test-server/ccloudv2_router.go
test/test-server/flink_artifact_handler.go

Release Notes
-------------
New Features
- Add `--class` to `confluent flink artifact create`
Checklist
---------
What
----
References
----------
Test & Review
-------------

[FRT-639] Introduce CLI artifact class param (#36)

---

cmd/lint/main.go
internal/flink/command_statement.go
internal/flink/command_statement_update.go
internal/iam/acl_utils.go
pkg/acl/acl.go
pkg/flink/app/application.go
pkg/flink/lsp/lsp_completer_ws.go
test/fixtures/output/flink/statement/create-wait.golden
test/fixtures/output/flink/statement/describe-yaml.golden
test/fixtures/output/flink/statement/describe.golden
test/fixtures/output/flink/statement/help.golden
test/fixtures/output/flink/statement/update-compute-pool.golden
test/fixtures/output/flink/statement/update-database-autocomplete.golden
test/fixtures/output/flink/statement/update-help.golden
test/fixtures/output/flink/statement/update-principal.golden
test/fixtures/output/flink/statement/update-stopped.golden
test/fixtures/output/iam/acl/create-help-onprem.golden
test/fixtures/output/iam/acl/delete-help-onprem.golden
test/fixtures/output/iam/acl/list-help-onprem.golden
test/fixtures/output/kafka/acl/create-help-onprem.golden
test/fixtures/output/kafka/acl/delete-help-onprem.golden
test/fixtures/output/kafka/acl/list-help-onprem.golden
test/flink_test.go
test/test-server/flink_gateway_router.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Add `confluent flink statement update` for updating a statement's principal and compute pool, or stopping a statement
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

[CLI-2818] Flink statement update

---

internal/flink/command_artifact_delete.go
pkg/deletion/deletion.go
test/fixtures/output/flink/artifact/delete-prompt.golden

Release Notes
-------------
Bug Fixes
- Update the confirmation prompt in `confluent flink artifact delete` to warn users that it might affect running statements
Checklist
---------
What
----
References
----------
Test & Review
-------------

[FRT-729] Update Artifact delete with warning breaking statement message

---

cmd/docs/main.go
internal/iam/command_certificate_pool_create.go
internal/iam/command_certificate_pool_delete.go
internal/iam/command_certificate_pool_describe.go
internal/iam/command_certificate_pool_list.go
internal/iam/command_certificate_pool_update.go
pkg/cmd/flags.go
test/fixtures/output/iam/certificate-pool/create-help.golden
test/fixtures/output/iam/certificate-pool/delete-help.golden
test/fixtures/output/iam/certificate-pool/describe-help.golden
test/fixtures/output/iam/certificate-pool/list-help.golden
test/fixtures/output/iam/certificate-pool/update-help.golden
test/fixtures/output/iam/group-mapping/create-help.golden
test/fixtures/output/iam/group-mapping/update-help.golden
test/fixtures/output/iam/pool/create-help.golden
test/fixtures/output/iam/pool/no-op-update.golden
test/fixtures/output/iam/pool/update-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- [Limited Availability] Add `confluent iam certificate-authority` and `confluent iam certificate-pool` commands to manage mTLS authentication
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Fix flags and unhide mTLS command reference.
References
----------
Test & Review
-------------

Update flags for mTLS

---

go.mod
go.sum
internal/network/command_access_point_private_link_egress_endpoint_create.go
internal/network/command_gateway.go
internal/network/command_gateway_create.go
internal/network/command_gateway_delete.go
internal/network/command_gateway_describe.go
internal/network/command_gateway_list.go
internal/network/command_gateway_update.go
pkg/ccloudv2/client.go
pkg/ccloudv2/networking-gateway.go
pkg/ccloudv2/networking.go
pkg/cmd/flags.go
pkg/resource/resource.go
test/fixtures/output/network/gateway/create-aws.golden
test/fixtures/output/network/gateway/create-help.golden
test/fixtures/output/network/gateway/create-type-autocomplete.golden
test/fixtures/output/network/gateway/delete-fail.golden
test/fixtures/output/network/gateway/delete-help.golden
test/fixtures/output/network/gateway/delete-multiple.golden
test/fixtures/output/network/gateway/delete.golden
test/fixtures/output/network/gateway/describe-aws-json.golden
test/fixtures/output/network/gateway/describe-azure.golden
test/fixtures/output/network/gateway/help.golden
test/fixtures/output/network/gateway/list-json.golden
test/fixtures/output/network/gateway/list.golden
test/fixtures/output/network/gateway/update-help.golden
test/fixtures/output/network/gateway/update.golden
test/network_test.go
test/test-server/networking_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Add `confluent network gateway [create | delete | update]` to manage gateways
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

[CLI-3190] Add CRUD for `confluent network gateway` commands

---

go.mod
go.sum
internal/kafka/command_link_describe.go
test/fixtures/output/kafka/link/describe-bidirectional-link.golden
test/test-server/kafka_rest_router.go

Release Notes
-------------
New Features
- Add mirror partition states summery for describe link
Checklist
---------
What
----
References
----------
Test & Review
-------------

KGLOBAL-5675: Add support for mirror partition state summery for link describe 

---

internal/flink/command_artifact.go
internal/flink/command_artifact_create.go
test/fixtures/output/flink/artifact/create-help.golden
test/fixtures/output/flink/artifact/create-python.golden
test/fixtures/output/flink/artifact/create.golden
test/fixtures/output/flink/artifact/describe.golden
test/flink_test.go
test/test-server/flink_artifact_handler.go

Release Notes
-------------
Bug Fixes
- Deprecate Artifact class field and expose Description and link fields
Checklist
---------

[FRT-781] Deprecate Artifact class field and expose Description and link fields

---

go.mod
go.sum
internal/flink/command_artifact_create.go
internal/flink/command_artifact_delete.go
internal/flink/command_artifact_describe.go
internal/flink/command_artifact_list.go
pkg/ccloudv2/flink_artifact.go
test/fixtures/output/flink/artifact/delete-help.golden
test/fixtures/output/flink/artifact/describe-help.golden
test/fixtures/output/flink/artifact/list-help.golden
test/flink_test.go

Release Notes
-------------
Bug Fixes
- Migrate to Flink Artifact 0.2.0 API
Checklist
---------

[FRT-792] Migrate to Flink Artifact 0.2.0 API

---

internal/iam/command_ipfilter_list.go
internal/iam/command_ipfilter_update.go
test/fixtures/output/iam/ip-filter/create-npn-group.golden
test/fixtures/output/iam/ip-filter/create-operation-groups.golden
test/fixtures/output/iam/ip-filter/create.golden
test/fixtures/output/iam/ip-filter/describe.golden
test/fixtures/output/iam/ip-filter/list-help.golden
test/fixtures/output/iam/ip-filter/list.golden
test/fixtures/output/iam/ip-filter/update-add-operation-group.golden
test/fixtures/output/iam/ip-filter/update-help.golden
test/fixtures/output/iam/ip-filter/update-remove-operation-group.golden
test/fixtures/output/iam/ip-filter/update-resource-add-and-remove.golden
test/fixtures/output/iam/ip-filter/update-resource-duplicate.golden
test/fixtures/output/iam/ip-filter/update-resource-remove-not-exist.golden
test/fixtures/output/iam/ip-filter/update.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

Fix integration test golden files

---

go.mod
go.sum
internal/custom-code-logging/command_custom_code_logging_delete.go
internal/custom-code-logging/command_custom_code_logging_describe.go
internal/custom-code-logging/command_custom_code_logging_list.go
internal/custom-code-logging/command_custom_code_logging_update.go
pkg/ccloudv2/custom_code_logging.go
test/fixtures/output/custom-code-logging/delete-help.golden
test/fixtures/output/custom-code-logging/describe-help.golden
test/fixtures/output/custom-code-logging/update-help.golden
test/fixtures/output/custom-code-logging/update-no-updates.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

Add env when calling custom code logging update list get delete

---

cmd/docs/main.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Hide custom-code-logging docs from command reference.
References
----------
Test & Review
-------------

Hide unreleased docs

---

internal/command.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

remove LD flag for custom code logging

---

internal/flink/command_application.go
internal/flink/command_environment.go
test/fixtures/output/flink/help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Do not allow `flink application` or `flink environment` to be run while logged in to Confluent Cloud, as they are not Confluent Cloud commands and we should not be collecting metrics on them.
References
----------
Test & Review
-------------

Add missing annotations for `flink application` and `flink environment`

---

go.mod
go.sum
internal/kafka/command_link_describe.go
test/fixtures/output/kafka/link/describe-bidirectional-link.golden
test/test-server/kafka_rest_router.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Add the "Mirror Partition States Count" field for `confluent kafka link describe`
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Reapply a reverted PR with some naming updates.
References
----------
Test & Review
-------------

Reapply KGLOBAL-5675

---

internal/flink/command_statement_resume.go
internal/flink/command_statement_stop.go
internal/flink/command_statement_update.go
test/fixtures/output/flink/statement/resume-help.golden
test/fixtures/output/flink/statement/stop-help.golden
test/fixtures/output/flink/statement/update-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Improve the `confluent flink statement [update | stop | resume]` examples with more accurate descriptions and provide better clarity to users
Checklist
---------
What
----
References
----------
Test & Review
-------------

[APIT2662] Improve the Flink statement update/stop/resume examples with more accurate description

---

.github/CODEOWNERS

Release Notes
-------------
Checklist
---------
What
----
I've moved to the sql team. Having both teams for a while for the transition.
References
----------
Test & Review
-------------

chore: add sql team to codeowners

---

internal/custom-code-logging/command_custom_code_logging_update.go

Release Notes
-------------
- n/a
New Features
- n/a
Bug Fixes
- Fix for `Error: malformed body: Unsupported destination, supported value ["Kafka"]` when running custom-code-logging update
Checklist
---------
What
----
References
----------
Test & Review
-------------
make build to create the cli binary and ran dist/confluent_darwin_arm64/confluent custom-code-logging update to verify the command now works.

SCP-4091: Fix ccl update destination error

---

internal/custom-code-logging/command_custom_code_logging.go
internal/custom-code-logging/command_custom_code_logging_create.go
internal/custom-code-logging/command_custom_code_logging_describe.go
internal/custom-code-logging/command_custom_code_logging_list.go
test/fixtures/output/custom-code-logging/create-no-env.golden
test/fixtures/output/custom-code-logging/create.golden
test/fixtures/output/custom-code-logging/describe-json.golden
test/fixtures/output/custom-code-logging/describe-yaml.golden
test/fixtures/output/custom-code-logging/describe.golden
test/fixtures/output/custom-code-logging/list-json.golden
test/fixtures/output/custom-code-logging/list-no-environment.golden
test/fixtures/output/custom-code-logging/list-yaml.golden
test/fixtures/output/custom-code-logging/list.golden
test/test-server/custom_code_logging_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
add topic, cluster and loglevel for custom code logging output
References
----------
Test & Review
-------------

SCP-4090 add topic, cluster and loglevel for custom code logging output

---

internal/cloud-signup/command.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Add user-tracking to the URL for cloud-signup
References
----------
https://confluentinc.atlassian.net/browse/CLI-3317
Test & Review
-------------
Tested manually

[CLI-3317] Add user-tracking to the URL for cloud-signup

---

pkg/auth/auth_token_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Make email address for SSO case insensitive
References
----------
https://confluentinc.atlassian.net/browse/CLI-3333
Test & Review
-------------
Tested manually 
Before: 
After:

[CLI-3333] Make email address for SSO case insensitive

---

internal/flink/command_artifact_create.go
internal/flink/command_artifact_delete.go
internal/flink/command_artifact_describe.go
internal/flink/command_artifact_list.go

Release Notes
-------------
Bug Fixes
- Make sure the environment is valid for artifact CLI commands
Checklist
---------

[FRT-838] Pre-Validate environment for artifact commands

---

pkg/auth/auth_token_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- SSO login failure fixed.
Checklist
---------
What
----
References
----------
https://confluentinc.atlassian.net/browse/RCCA-24326
Test & Review
-------------

RCCA-24326 - Confluent CLI SSO login fails for multiple customers

---

internal/flink/command_connection.go
internal/flink/command_connection_create.go
internal/flink/command_connection_delete.go
internal/flink/command_connection_describe.go
internal/flink/command_connection_list.go
internal/flink/command_connection_update.go
test/fixtures/output/flink/connection/create/create-wrong-env.golden
test/fixtures/output/flink/connection/delete/delete-wrong-env.golden
test/fixtures/output/flink/connection/describe/describe-wrong-env.golden
test/fixtures/output/flink/connection/list/list-wrong-env.golden
test/fixtures/output/flink/connection/update/update-wrong-env.golden
test/flink_test.go

Release Notes
-------------
Bug Fixes
- Check environment for connection commands
Checklist
---------
What
----
References
----------
Test & Review
-------------
Added new integration test

Check environment for connection commands

---

.github/pull_request_template.md

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Update the `pull_request_template.md` file for CLI to reflect the new PR approval requirements and checklist.
References
----------
New CAB approval requirement:
https://confluentinc.atlassian.net/wiki/spaces/NEI/pages/3945988850/E+G+Production+Change+Management+Process
CLI ticket:
https://confluentinc.atlassian.net/browse/APIT-2738
Test & Review
-------------
Since this PR only impacts the GitHub setting, so no test or verification is necessary.

[APIT-2738] Update the PR template file for CLI to reflect the new PR approval requirement

---

.github/pull_request_template.md

Release Notes
-------------
New Features
- Update the PR request template file.
Checklist
---------
What
----
The update on the `pull_request_template.md` file, changes include:
- Add the `Blast Radius` section.
- PR owner should specify which test environment the feature is enabled in the checklist.
- Update `CLI integration tests` -> `CLI integration or unit tests`.
- Some grammar level update.
References
----------
https://confluentinc.atlassian.net/wiki/spaces/AEGI/pages/3949592874/Confluent+CLI+developer+contributing+and+PR+approval+requirements
Test & Review
-------------
Since this PR only impacts a MD file, no test is required.

[APIT-2738] Improve the PR template by adding Blast Radius and be more specific in checklist items

---

internal/iam/command.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
lint issue in https://github.com/confluentinc/cli/pull/3005
Blast Radius
----
N/A
References
----------
https://github.com/confluentinc/cli/pull/3005
Test & Review
-------------
`make lint` passes

Fix lint issues on AM-5052

---

pkg/output/printer.go
pkg/output/printer_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix broken link highlighting in `confluent local kafka start`
Checklist
---------
What
----
Before:
After:
References
----------
Test & Review
-------------
Unit tests

Fix link regular expression and test

---

internal/iam/command_rbac_role_list.go
test/test-server/cloud_mds_handlers.go

Bug Fixes
---------
- Ensures all public and production ready RBAC roles are available via the RBAC List command.
Checklist
---------
What
----
Some production-ready roles were hidden in the Confluent CLI due to existing outside the explicit namespace list in our CLI code. The [RBAC Roles List API](https://github.com/confluentinc/cc-rbac-services/pull/1643) has been updated so that it will now return all public and production ready roles by default without needing a specific namespace parameter entered. This will allow the CLI to automatically show the correct list of public RBAC roles without needing continuous LD changes or code updates.
Blast Radius
----
The worst-case blast radius here would be a failure to see the correct roles when using the RBAC list command. This would not impact …

AM-5132: Update RBAC CLI List command to reflect new RBAC List API changes.

---

cmd/lint/main.go
go.mod
go.sum
internal/iam/command.go
internal/iam/command_pool_create.go
internal/iam/command_provider_update.go
internal/iam/command_service_account_create.go
internal/iam/command_service_account_update.go
pkg/ccloudv2/iam.go
pkg/ccloudv2/identity_provider.go
test/fixtures/output/iam/pool/create-help.golden
test/fixtures/output/iam/service-account/create-help.golden
test/iam_test.go
test/test-server/iam_handlers.go

Checklist
---------
- [N/A] I have verified this PR in Confluent Cloud pre-prod or production environment, if applicable.
- [N/A] I have verified this PR in Confluent Platform on-premises environment, if applicable.
- [N/A] I have attached manual CLI verification results or screenshots in the `Test & Review` section below.
- [N/A] I have added appropriate CLI integration or unit tests for any new or updated commands and functionality.
- [N/A] I have indicated the potential customer impact if something goes wrong in the `Blast Radius` section below.
- [N/A] I have put checkmarks below confirming that the feature associated with this PR is enabled in:
What
----
Reverting workload identity and lint changes. 
Blast Radius
----
References
----------
Test & Review
-------------

revert(AM-5052)

---

pkg/auth/auth_token_handler.go
pkg/auth/mfa/auth_mfa_flow.go
pkg/auth/mfa/auth_server.go
pkg/auth/mfa/auth_server_test.go
pkg/auth/mfa/auth_state.go
pkg/auth/mfa/auth_state_test.go
pkg/auth/sso/auth_state_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Local user login via MFA with `--no-browser` flag
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Local user login via MFA with --no-browser command
Blast Radius
----
All MFA users of the CLI
References
----------
https://confluentinc.atlassian.net/browse/CLI-3399
Test & Review
-------------
Added integration tests. 
Manual testing doc: https://docs.google.com/document/d/1kk3j2TAxiZmqlbx-2O0HJmBRk11PPcvLTrwH_FR-5pM/edit?tab=t.0

Local user login via MFA with --no-browser command

---

internal/cluster/command_register.go
test/fixtures/output/cluster/register-help-onprem.golden
test/fixtures/output/cluster/register-missing-hosts.golden

Release Notes
-------------
Checklist
---------
What
----
Updated the Examples section of this Confluent Platform command reference file to add an example and an external link to other examples in the public Docs. (There were previously no examples in the file.)
Blast Radius
----
References
----------
Jira ticket: https://confluentinc.atlassian.net/browse/DOCS-26303
Test & Review
-------------
Updated golden file.

DOCS-26303 Provide better examples and info re: registering a cluster via the CLI

---

.gitignore

Release Notes
-------------
- None
New Features
- None
Bug Fixes
- None
Checklist
---------
What
----
This tasks add the JetBrains GoLand IDE .idea/  to the .gitignore so the files are not inadvertently pushed or staged in git. 
Blast Radius
----
n/a
References
----------
https://confluentinc.atlassian.net/browse/CLI-3415
Test & Review
-------------
Made sure to check if it was actually ignored, which it was

[CLI-3415] Add JetBrains IDE project file to .gitignore

---

internal/flink/command_shell.go
test/fixtures/output/flink/shell-help.golden

**Note to reviewers**:  Build breaks are being caused by hitting the rate limit for unauthenticated docker pulls (pipeline not logging into Docker). @sgagniere will submit a PR to disable this check, then I'll rebase to main, and this should pass.
Release Notes
-------------
- N/A
New Features
- N/A
Bug Fixes
- N/A
Checklist
---------
What
----
Add an Examples section to this command reference file for Confluent Cloud, [confluent flink shell](https://docs.confluent.io/confluent-cli/current/command-reference/flink/confluent_flink_shell.html#) for the purposes of adding an external link to the [Flink shell Quick Start](https://docs.confluent.io/cloud/current/flink/get-started/quick-start-shell.html) in the public Docs. (There were previously no examples or an Examples …

DOCS-32803 CLI command reference Docs: Provide links from confluent flink shell to the Quick Start examples

---

pkg/flink/components/interactive_input.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Prevent `confluent flink shell` from crashing when window is too small
Checklist
---------
What
----
Confluent Cloud: In `confluent flink shell`, avoid crashing on small window sizes due to passing a negative value to `strings.Repeat()`
Blast Radius
----
Customers using the `confluent flink shell` command will be impacted
References
----------
https://confluentinc.atlassian.net/browse/CLI-3447
Test & Review
-------------
Before:
After:

CLI-3447: Fix `flink shell` panic

---

go.mod
go.sum

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Upgrade the `confluent-kafka-go` library version to the latest to fix an issue specific to CSFLE encryption.
Checklist
---------
What
----
The PR fixes a specific issue regarding how the schema field is encrypted for CSFLE when using an older version of the `confluent-kafka-go` library.
Blast Radius
----
Only customers using the CSFLE feature will be impacted in the worst case.
References
----------
https://confluent.slack.com/archives/C057NJLGL06/p1741204983738529
Test & Review
-------------
Technical support engineers have helped to verify the fix described in this thread:
https://confluent.slack.com/archives/C057NJLGL06/p1741204983738529

Upgrade the confluent Kafka go version to the latest

---

Makefile
service.yml

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
https://confluent.slack.com/archives/C010Y0EP5MZ/p1743189930443959
Blast Radius
----
References
----------
Test & Review
-------------

[CLI-3423] Follow up PR to address the MK_INCLUDE issue

---

pkg/docs/doc_page.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------

PLSR docs warning for deprecated

---

pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementPrintsNoWarningForLocalStatements
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementPrintsNoWarningForStatementsOtherThanInsertOrStatementSet
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementPrintsNoWarningWhenUserIdentityIsUsed
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementPrintsUserInfo
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementReturnsWhenUserDetaches
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementWaitsForCompletedState
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementWaitsForFailedState
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementWaitsForNonEmptyPageToken
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementWithWarning
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestOutputOfDryRunStatements-failed_dry_run
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestOutputOfDryRunStatements-successful_dry_run
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestOutputOfDryRunStatements-unexpected_status_dry_run
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestRenderMsgAndStatusLocalStatements-local_non-failed_statement
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestRenderMsgAndStatusNonLocalFailedStatements-statement_with_name
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestRenderMsgAndStatusNonLocalFailedStatements-statement_without_name
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestRenderMsgAndStatusNonLocalNonFailedStatements-statement_with_name
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestRenderMsgAndStatusNonLocalNonFailedStatements-statement_without_name
pkg/flink/internal/controller/statement_controller_test.go
pkg/flink/internal/store/.snapshots/TestStoreTestSuite-TestProcessStatementFailsOnError
pkg/flink/internal/store/.snapshots/TestStoreTestSuite-TestProcessStatementUsesUserProvidedStatementName
pkg/flink/internal/store/.snapshots/TestStoreTestSuite-TestProcessStatementWithServiceAccount
pkg/flink/internal/store/.snapshots/TestStoreTestSuite-TestProcessStatementWithUserIdentity
pkg/flink/internal/store/store.go
pkg/flink/types/processed_statement.go
test/fixtures/output/flink/shell/reset-all-keys.golden
test/fixtures/output/flink/shell/reset-single-key.golden
test/fixtures/output/flink/shell/set-single-key.golden
test/fixtures/output/flink/shell/use-catalog.golden
test/fixtures/output/flink/shell/use-database.golden
test/flink_test.go

Release Notes
-------------
New Features
- The `confluent flink shell` now supports statement warnings, which will be gradually added.
Checklist
---------
What
----
We're adding warnings to help customers identify potential issues with their statements for confluent cloud. The backend sends the warning in the detail field, and we just display them, if present.
Blast Radius
----
No one will be blocked. We will only show extra information.
References
----------
FSE-332
Test & Review
-------------
Unit test added and

[FSE-332] Support warnings for `confluent flink shell`

---

.semaphore/semaphore.yml
Makefile
debian/patches/standard_build_layout.patch

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------

SonarQube integration for CLI w/o Service Bot

---

.semaphore/semaphore.yml
docker/Dockerfile_alpine_amd64
docker/Dockerfile_alpine_arm64
docker/Dockerfile_build_linux_amd64
docker/Dockerfile_build_linux_arm64

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
This upgrades our semaphore agent to Ubuntu 24 to comply with DevProd's deprecation of Ubuntu 20.
Blast Radius
----
References
----------
Test & Review
-------------

Upgrade CLI Semaphore Agent to Ubuntu 24

---

pkg/flink/internal/results/materialized_results_test.go
pkg/flink/internal/results/result_fetcher_test.go
pkg/flink/types/materialized_results.go
pkg/flink/types/materialized_results_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- `confluent flink shell` now handles multiple rows for the same primary key when materializing results.
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Since flink does not enforce primary keys, clients can submit multiple records with the same key. We now support handling multiple records for the same key when materializing results in flink shell.
Blast Radius
----
CC customers will see different results when running their queries for edge cases when they "misuse" primary keys. 
References
----------
[FCP-3130]
Test & Review
-------------
Multiple unit tests
[FCP-3130]: https://confluentinc.atlassian.net/browse/FCP-3130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[FCP-3130] Support multiple rows for the same key

---

pkg/serdes/serdes_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The test cleanup occasionally throws an error on Windows because a file is still in use.
Since it is the cleanup code and not the actual tests that is causing the overall test failure, we can disable that check on Windows for now without losing coverage.
Blast Radius
----
References
----------
Test & Review
-------------

Remove flaky unit test condition for Windows

---

internal/connect/command.go
internal/connect/command_artifact.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------

Add feature flag to Custom SMT feature for EA

---

.semaphore/semaphore.yml

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Add `$ProgressPreference = 'SilentlyContinue'` to speed up the powershell `Invoke WebRequest` command in the Windows pipeline by not displaying the progress bar. This step takes anywhere from 2 to 6 minutes, which is almost entirely due to the progress bar. Removing that brings the runtime of that step down to a few seconds.
Blast Radius
----
References
----------
Test & Review
-------------
Compare:
`00:02` with ProgressPreference = SilentlyContinue: https://semaphore.ci.confluent.io/jobs/e7bfe5c9-f1e7-49b1-9468-9c7fa93028f9
`03:37` without: https://semaphore.ci.confluent.io/jobs/2760f1e1-3dd3-429c-b4a3-7113931b3932

Speed up Windows pipeline by a few minutes

---

pkg/ccloudv2/logging.go
test/connect_test.go
test/fixtures/output/connect/cluster/describe-autocomplete.golden
test/fixtures/output/connect/cluster/list-json.golden
test/fixtures/output/connect/cluster/list-yaml.golden
test/fixtures/output/connect/cluster/list.golden
test/fixtures/output/connect/logs/logs-server-connection-issue.golden
test/test-server/connect_handler.go

Release Notes
-------------
New Features
- Improves error messaging in case of server connection issues to inform about the rate limit. Also increases page size to the maximum supported by the API. 
Checklist
---------
What
----
We improve the error messaging for the case where CLI is unable to connect to the server and also increase the page size to maximum possible value.
Blast Radius
----
References
----------
Test & Review
-------------
```
mchoudhary@WH9KW4M76R cli % ./confluent connect logs lcc-123 --start-time 2025-07-04T05:30:00Z --end-time 2025-07-04T05:40:00Z --level INFO
Error: failed to query connector logs: failed to make HTTP request to logging API due to issue connecting to the server, please make sure you adhere to 5 requests per minute per connector rate limit
```

Add ratelimit error message for connect logs subcommand

---

pkg/auth/auth_token_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
For Confluent Cloud SSO/MFA refresh.
Errors that don't end command execution should instead be logged. 
Blast Radius
----
None.
References
----------
Test & Review
-------------
NORMAL USAGE not impacted (not a test of the error message itself):
```
confluent environment list -vvv             
2025-07-14T13:54:16.447-0700 [DEBUG] unable to find value for requested flag "connect.artifact.enabled"
2025-07-14T13:54:16.447-0700 [DEBUG] Searching $PATH and ~/.confluent/plugins for plugins. Plugins can be disabled in /Users/sgagniere/.confluent/config.json.
2025-07-14T13:54:16.485-0700 [DEBUG] Updating auth tokens
2025-07-14T13:54:16.485-0700 [DEBUG] Did …
```

Log errors from SSO/MFA refresh requests to the DEBUG log

---

.semaphore/semaphore.yml

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The `Expand-Archive` powershell command takes 2+ minutes to extract an archive when it only takes 7z 10-15 seconds.
Blast Radius
----
References
----------
Test & Review
-------------
Current:
New:

Replace Expand-Archive with 7z in Windows test pipeline

---

internal/connect/command.go
internal/connect/command_custom_runtime.go
internal/connect/command_custom_runtime_list.go
logs.txt
pkg/ccloudv2/connect_custom_plugin.go
test/connect_test.go
test/fixtures/output/connect/custom-connector-runtime/help.golden
test/fixtures/output/connect/custom-connector-runtime/list-help.golden
test/fixtures/output/connect/custom-connector-runtime/list-json.golden
test/fixtures/output/connect/custom-connector-runtime/list-yaml.golden
test/fixtures/output/connect/custom-connector-runtime/list.golden
test/fixtures/output/connect/help-onprem.golden
test/fixtures/output/connect/help.golden
test/test-server/ccloudv2_router.go
test/test-server/connect_handler.go

Release Notes
-------------
New Features
- Add `connect custom-connector-runtime list` command.
Checklist
---------
What
----
Blast Radius
----
Adds a new command for `confluent connect` 
Backward compatible
References
----------
Link to one pager: https://confluentinc.atlassian.net/wiki/spaces/OAAC/pages/4076929951
Test & Review
-------------
Tested on stag
Stag Testing: 
```
> dist/confluent_darwin_arm64/confluent connect custom-connector-runtime list
ID       | Runtime Name | Runtime AK Version | Supported Java Versions | Product Maturity |        End of Life At         |          Description            
-----------------+--------------+--------------------+-------------------------+------------------+-------------------------------+---------------------------------
ccrv-stgc1ep54 | …
```

Add list custom connect runtime in connect

---

internal/connect/command_custom_runtime.go
internal/connect/command_custom_runtime_list.go
test/fixtures/output/connect/custom-connector-runtime/list-json.golden
test/fixtures/output/connect/custom-connector-runtime/list-yaml.golden
test/fixtures/output/connect/custom-connector-runtime/list.golden
test/test-server/connect_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Handle Empty End of Life for list custom connector runtimes
Checklist
---------
What
----
Minor Fix in List custom Connector Runtimes
Null EoL were not being handled properly and were returned as timestamp which was not making any sense. 
In this PR, we have handled Null EoL explicitly.
Previous PR:https://github.com/confluentinc/cli/pull/3137
Blast Radius
----
confluent connect custom-connector-runtime list
References
----------
Test & Review
-------------
Stag testing: 
```
dist/confluent_darwin_arm64/confluent connect custom-connector-runtime list
ID       | Runtime Name | Runtime AK Version | Supported Java Versions | Product Maturity |        End of Life At         |          Description …
```

[Minor][Fix] Handle Empty Eol for list runtimes

---

internal/schema-registry/command_schema_delete.go
test/fixtures/output/schema-registry/schema/delete-help-onprem.golden
test/fixtures/output/schema-registry/schema/delete-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
It is currently not clear from the command reference or `--help` output how someone should permanently delete a schema version.
This PR updates the wording for both Cloud and On-Prem, and adds new examples outlining the process.
Blast Radius
----
None, this is only a documentation update.
References
----------
Test & Review
-------------

[CLI-3680] Improve description for the `--permanent` flag for `schema-registry schema delete`

---

internal/flink/command_artifact_create.go
test/fixtures/output/flink/artifact/create-gcp.golden
test/fixtures/output/flink/artifact/create-python-gcp.golden
test/fixtures/output/flink/artifact/delete-gcp.golden
test/fixtures/output/flink/artifact/delete-prompt-gcp.golden
test/fixtures/output/flink/artifact/describe-gcp.golden
test/fixtures/output/flink/artifact/list-gcp.golden
test/flink_test.go
test/test-server/flink_artifact_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Support create flink artifact on gcp.
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
On the backend, we allow create flink artifact on gcp. However, cli has not supported it yet.
```
confluent flink artifact create test-artifact --artifact-file ~/Downloads/plugin.jar --cloud gcp --region us-central1
Error: <?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>Access denied.</Message><Details>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Details><StringToSign>GOOG4-RSA-SHA256
20250811T174954Z
20250811/auto/storage/goog4_request
3bd249cba6a76e2e7ab331b54546e2c04cd52a9ee68840e51ee589a0b9b3b583</Str …
```

Support flink artifact on GCP

---

Makefile
debian/patches/standard_build_layout.patch

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Basically the same change as in this PR: https://github.com/confluentinc/cli/pull/3155
Makefile directives can't have tabs in front of them or else they'll be considered shell commands
Blast Radius
----
References
----------
Test & Review
-------------

Fix `make cross-build`

---

sonar-project.properties

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------

Add back `sonar.go.coverage.reportPaths`

---

docker/Dockerfile_alpine_amd64
docker/Dockerfile_alpine_arm64
docker/Dockerfile_build_linux_amd64
docker/Dockerfile_build_linux_arm64

Release Notes
-------------
Adds the ability to configure isTest. I ran into an issue where the locally built CLI was not hitting the prod endpoints due to isTest being false. With this change my workflow was
```
docker build . --file docker/Dockerfile_build_linux_amd64 --tag test-build-linux-amd64 --build-arg IS_TEST=false
docker container create --name test-build-container-linux-amd64  test-build-linux-amd64
docker container cp test-build-container-linux-amd64:/cli/confluent  dirty-confluent-linux-amd64
```
None
New Features
None
Bug Fixes
None
https://confluent.slack.com/archives/CG6BW233L/p1758637935028189
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------

CONFLUENT: Add arg for setting isTest

---

internal/iam/command_rbac.go
internal/iam/command_rbac_role_describe.go
internal/iam/command_rbac_role_list.go
test/fixtures/output/iam/rbac/role/list-cloud.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Add the `usm` namespace so that the `UsmAgent` role can be described with the Cloud command `confluent iam role-binding role describe`.
Blast Radius
----
None.
References
----------
Test & Review
-------------
Tested in staging.
Before:
```
confluent iam rbac role describe UsmAgent
Error: unknown role "UsmAgent"
Suggestions:
The available roles are "AccountAdmin", "Assigner", "CloudClusterAdmin", "DataDiscovery", "DataSteward", "DeveloperManage", "DeveloperRead", "DeveloperWrite", "EnvironmentAdmin", "FlinkAdmin", "FlinkDeveloper", "KsqlAdmin", "MetricsViewer", "Operator", "OrganizationAdmin", "ResourceKeyAdmin", "ResourceOwner", and "UsmOperator". …
```

[APIE-587] Add USM namespace for role bindings

---

internal/provider-integration/v2/command_create.go
pkg/ccloudv2/provider_integration_v2.go
test/fixtures/output/provider-integration/v2/create-invalid-azure-atomic.golden
test/fixtures/output/provider-integration/v2/create-invalid-gcp-atomic.golden
test/provider_integration_test.go
test/test-server/provider_integration_v2_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The implementation of Provider Integration V2 encapsulates both the creation of a PI into a draft as well as the subsequent update/patch into one create command. If the 2nd part fails, the draft can be left in a lingering state where it can't be updated again. This PR ensures that if the 2nd part fails, we cleanup by deleting the draft as well as relaying the error message that the backend sends us in the 400 response.
Blast Radius
----
References
----------
Test & Review
-------------
```
Test 1: Invalid GCP service account (should show 'invalid Google Service Account'):
Created provider integration cspi-stgcd13vd in DRAFT state.
Deleted draft …
```

Provider Integration V2 impl. updated for atomicity
