internal/cmd/pipeline/command.go
test/fixtures/output/pipeline/update-activation-privilege.golden

Checklist
---------
* yes: ok
What
----
This seems an regression introduced during migration to v3:
* the `ActivationPrivilege` was removed from the pipeline output
* the unit test file `update-activation-privilege.golden` was also updated hence the integ test didn't catch this
This fix introduce back the property
References
----------
Test & Review
-------------

[SD-1668] Fix the activation privileges in the output

---

internal/cmd/iam/command_rbac_role_binding.go
test/test-server/ccloud_handlers.go

Checklist
---------
* yes: ok
What
----
Two bug fixes:
1. It's possible for the `Organization` field to be `nil`. We should be using the `Account` field instead.
2. We need to use `TrimPrefix()` instead of `TrimLeft()`, otherwise principals starting with any of the characters "U", "s", "e", "r", or ":" will be trimmed.

`iam rbac role-binding` fixes

---

internal/cmd/iam/command_rbac_role_binding.go
test/fixtures/output/iam/rbac/role-binding/create-service-account-developer-read.golden
test/iam_test.go

Checklist
---------
* yes: ok
What
----
The `displayCCloudCreateAndDeleteOutput` function makes a call to `V2Client.GetIamUserById` for both user id's and service account id's. Before v3, whether or not the error from this call was `nil` was used to determine whether to format the output for service accounts or users. In v3 this error was returned immediately, hence the issue.
I've replaced the check for `err != nil` with a check on the format of the id and moved the `V2Client.GetIamUserById` call so that it should only be called with an actual user id.
References
----------
n/a
Test & Review
-------------
Manual testing using commands of the following forms:
`confluent iam rbac rb create --principal User:sa-12345 …

[RCCA-10729] Resolve display error when creating role bindings with service accounts

---

internal/cmd/iam/acl_utils.go
internal/cmd/iam/command_acl_create.go
internal/cmd/iam/command_acl_list.go
internal/cmd/iam/command_acl_test.go
internal/cmd/iam/command_rbac_role_binding_list.go
internal/cmd/kafka/command_acl_create.go
internal/cmd/kafka/command_acl_create_onprem.go
internal/cmd/kafka/command_acl_delete_onprem.go
internal/pkg/acl/acl.go
internal/pkg/acl/acl_test.go
test/fixtures/output/iam/acl/create-help.golden
test/fixtures/output/iam/acl/list-help.golden
test/fixtures/output/iam/rbac/role-binding/list-failure-help-cloud.golden
test/fixtures/output/iam/rbac/role-binding/list-help-cloud.golden
test/fixtures/output/kafka/acl/create-help.golden
test/fixtures/output/kafka/acl/onprem-create-help.golden
test/fixtures/output/kafka/acl/onprem-list-help.golden
test/kafka_test.go

Checklist
---------
* yes: ok
What
----
Updates to examples and flag strings.
- operations like "read" and "describe" for ACL commands are now lowercase in the example strings and the `--help` output. This is not a breaking change; only the text has been updated and the code continues to accept lower or upper case.
- Added new examples to `confluent iam rbac role-binding list` to highlight the `--inclusive` flag.
- Added more integration tests for help text.
References
----------
n/a
Test & Review
-------------
Ran all tests
Should we update the description of the `confluent iam rbac role-binding list` command to explain which combinations of flags correspond to …

Various example and flag text updates

---

internal/cmd/kafka/command_link_list.go

Checklist
---------
* yes: ok
What
----
Avoid panic due to a `nil` pointer dereference.
References
----------
https://confluent.slack.com/archives/C010Y0EP5MZ/p1675803783662019

Fix `kafka link list` panic

---

internal/pkg/ccloudv2/cli.go
internal/pkg/plugin/plugin.go
internal/pkg/usage/usage.go

Checklist
---------
* yes: ok
What
----
* Moved a few expensive operations outside of loops for plugin search.
* Limited usage service calls to 5s. If there is a service outage, this is much better than the original timeout of 30s.
References
----------
* https://confluent.slack.com/archives/C010Y0EP5MZ/p1675957387604929
* https://confluent.slack.com/archives/C010Y0EP5MZ/p1675878574713979
Test & Review
-------------
Set the timeout to 1ms and observed the following error:
```
2023-02-09T14:18:54.580-0800 [WARN]  Failed to report CLI usage: Post "https://api.confluent.cloud/cli/v1/usages": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Performance improvements

---

.goreleaser-build.yml
.goreleaser-linux-glibc-arm64.yml
.goreleaser-linux-glibc.yml
.goreleaser.yml
Jenkinsfile
Makefile
debian/patches/standard_build_layout.patch
mk-files/release.mk

Checklist
---------
* yes: ok
What
----
Noticed a few of these during the last release and staying on top of them!
```
DEPRECATED: `archives.replacements` should not be used anymore, check https://goreleaser.com/deprecations#archivesreplacements for more info
DEPRECATED: `archives.rlcp` will be the default soon, check https://goreleaser.com/deprecations#archivesrlcp for more info
```

Fix goreleaser deprecation warnings

---

internal/cmd/kafka/command_cluster_update.go
test/test-server/cmk_handlers.go

Checklist
---------
* yes: ok
What
----
According to docs https://docs.confluent.io/cloud/current/clusters/cluster-api.html#id3 in one request we should only specify the name or the config (cku), although it's possible to update both at the same time. But when the user provides only cku, the display name is set to the new update name field, which is not what the user wants as the name could be different. 
To avoid breaking changes, we still allow updating both name and cku in one line, but in our next major version we might consider only allowing name or cku, to make the command more atomic and match the behavior of other update commands like schema-registry `mode` / `compatibility`
References
---------- …

Do not set `name` field in cluster update when it's not specified

---

.goreleaser-linux-glibc-arm64.yml
.goreleaser-linux-glibc.yml
.goreleaser.yml
.semaphore/semaphore.yml
Jenkinsfile
Makefile
README.md
debian/patches/standard_build_layout.patch
mk-files/release.mk

Checklist
---------
* yes: ok
What
----
`go install` is essentially a no-op when a package is already installed (it's much more performant now than it was in certain older versions of Go). We can move the `go install` commands closer to where they're needed to simplify the setup process (and make our tests that only use some of the dependencies faster)
Test & Review
-------------
Manually executed targets to make sure they still work as intended.

Remove `make deps`

---

internal/cmd/api-key/command.go
internal/cmd/api-key/command_list.go
internal/cmd/api-key/command_test.go
test/test-server/ccloud_handlers.go

Checklist
---------
* yes: ok
What
----
users with DeveloperRead/Write/Manage roles get a 403 Forbidden when trying to call `confluent api-key list`. 
```
> confluent -vvvv api-key list
2022-03-02T22:41:32.196-0800 [DEBUG] UserService.GetServiceAccounts request: GET https://devel.cpdev.cloud/api/service_accounts
2022-03-02T22:41:32.495-0800 [DEBUG] UserService.GetServiceAccounts response: 200 OK X-Request-Id:37073471e5fa8cad325d32274d5b9d4b Body: {"users":[],"page_info":{"page_size":0,"page_token":""},"error":null} request: GET https://devel.cpdev.cloud/api/service_accounts
2022-03-02T22:41:32.495-0800 [DEBUG] UserService.List request: GET https://devel.cpdev.cloud/api/users
2022-03-02T22:41:32.564-0800 [DEBUG] …
```

[CIAM-1796] Dataplane roles get 403 when listing api keys

---

internal/cmd/asyncapi/account_details.go
internal/cmd/asyncapi/command_export.go
internal/cmd/asyncapi/command_export_test.go

Release Notes
-------------
New Features
Bug Fixes
- Fixes logging for the Protobuf case
- Ensures that in case of Protobuf, further functions are not called for that channel (subject).
Checklist
---------
* yes
What
----
- In case of a Protobuf schema, that subject should be skipped. Ensuring that other functions are not called in such a case.
- Switching to log.Clilogger.Info() method instead of using log.Clilogger.log()
- Adding a unit test for the protobuf case
References
----------
https://confluent.slack.com/archives/C010Y0EP5MZ/p1676912651486499
Test & Review
-------------

AsyncAPI Fix for Protobuf message logging

---

go.mod
go.sum
internal/pkg/secret/encryption_other.go

Release Notes
-------------
Bug Fixes
- Fixed an issue where users can't log in on Alpine linux due to missing ``/etc/machine-id`` file
Checklist
---------
* yes: ok
What
----
Use a maintained fork of the previous `machineid` package, where it can detect machine id even in docker containers. 
References
----------
https://github.com/denisbrodbeck/machineid/issues/5#issuecomment-752416741
Test & Review
-------------
Tested on mac, ubuntu and alpine. After running login, `/etc/machine-id` is generated on alpine. 

[RCCA-11060] Use panta/machineid to fix `/etc/machine-id` not found issue on alpine linux

---

mk-files/usage.mk

Checklist
---------
* yes: ok
What
----
cctunnel returns control to the user before it's actually done. Adding a sleep statement before the next command in this script to try and prevent the connection refused errors I keep getting when I do the releases.
3 seconds is probably longer than necessary, but seems alright for a first try.

Add sleep statement to update db script

---

internal/pkg/plugin/plugin.go
internal/pkg/plugin/plugin_test.go

Release Notes
-------------
Bug Fixes
- Use ``$PATHEXT`` to correctly determine if a plugin is executable on Windows
Checklist
---------
* yes: ok
What
----
Before, the list of valid plugin extensions was hardcoded (and was missing several extension types!) Windows relies on `$PATHEXT` to determine which file extensions are executable, so we should too.
References
----------
https://confluentinc.atlassian.net/browse/CLI-2067
Test & Review
-------------
Unit tests

[CLI-2067] Use `$PATHEXT` to find executable plugins on Windows

---

internal/pkg/config/v1/context.go
internal/pkg/dynamic-config/dynamic_context.go

Release Notes
-------------
New Features
Bug Fixes
- Prevent a panic that could occur when using commands with the ``--environment`` flag
Checklist
---------
* yes: ok
What
----
If `State` or `Auth` are unexpectedly nil, trying to get `c.State.Auth.Accounts` will panic. This PR replaces the direct access with `Get` functions that check for both a non-nil state and auth.
References
----------
n/a
Test & Review
-------------
All tests pass.
Checked that commands using `--environment` flag still work correctly, and that everything works if you delete the the environment list from the config file (although I'll note that this is true even before this PR, so it's unclear why …

[CLI-2101] Prevent panic when the parsing environment flag into the context

---

internal/cmd/kafka/command_acl.go
internal/cmd/kafka/command_acl_create.go
internal/cmd/kafka/command_acl_delete.go
internal/cmd/kafka/command_acl_list.go

Release Notes
-------------
New Features
Bug Fixes
Checklist
---------
* yes: ok
What
----
only get service accounts and users once, in kafka acl commands, if users are already got, pass it on to next call.
References
----------
Test & Review
-------------
```
mhe@C02DV0KVMD6T cli % confluent kafka acl list -vvv
2023-02-28T13:20:38.937-0800 [DEBUG] Searching `$PATH` for plugins. Plugins can be disabled in /Users/mhe/.confluent/config.json.
2023-02-28T13:20:39.307-0800 [DEBUG] UserService.GetServiceAccounts request: GET https://confluent.cloud/api/service_accounts
2023-02-28T13:20:39.613-0800 [DEBUG] UserService.GetServiceAccounts response: 200 OK …
```

[CLI-1757] only get service accounts and users once, in kafka acl commands

---

internal/cmd/price/command_list.go
test/cli_test.go
test/fixtures/output/iam/identity-pool/create.golden
test/fixtures/output/iam/identity-pool/update.golden
test/fixtures/output/price/list-empty-flag.golden
test/iam_test.go
test/pipeline_test.go
test/price_test.go

Release Notes
-------------
Bug Fixes
- Prevent empty values from being passed to flags in ``confluent price list``
Checklist
---------
* yes: ok
What
----
`confluent price list --cloud "" --region ""` used to be accepted. Empty values should not be accepted, so now we error.
Used the shlex package to parse integration test commands in a similar manner to bash/zsh (now you can pass multi-word arguments in quotes)
References
----------
https://confluentinc.atlassian.net/browse/CLI-2262
Test & Review
-------------
Added an integration test and fixed other integration tests after switching to shlex.

[CLI-2262] Check for empty flag values in `price list`

---

internal/cmd/api-key/command_create.go
internal/pkg/errors/error_message.go
test/api_key_test.go
test/cli_test.go
test/fixtures/output/api-key/29.golden
test/fixtures/output/api-key/54.golden
test/fixtures/output/api-key/60.golden

Release Notes
-------------
New Features
- Add the ``--use`` flag to ``confluent api-key create`` to select the API key after it has been created
Checklist
---------
* yes: ok
What
----
new flag ``--use`` in ``confluent api-key create`` which will use the created API key for the provided resource after successfully creating the key.
If the resource provided is not a kafka cluster, print out error that ``use`` was not effective.
References
----------
https://confluentinc.atlassian.net/browse/CLI-962
Test & Review
-------------

[CLI-962] add `--use` flag in `api-key create` to automatically use the created api-key for the provided resource

---

dockerfiles/Dockerfile

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix ``cipher: message authentication failed`` issue on Alpine image
Checklist
---------
* yes: ok
What
----
got multiple reports saying alpine image is not working because of `cipher authentication error`. Because `/etc` was a read-only dir and cli generates/reads machine id on `/etc/machine-id`, encryption was failing because no actual machine id is being used. chown this dir to solve the read/write issue.
References
----------
Test & Review
-------------
Tested alpine image that commands and `--save` are working.

Chown /etc so cli can read/write /etc/machine-id on Alpine for encryption

---

internal/pkg/config/load/load_latest.go
internal/pkg/config/v1/config.go

Release Notes
-------------
- Disable plugins by default on Windows, but allow manual re-enablement in ~/.confluent/config.json
Checklist
---------
* yes: ok
What
----
Plugin search can be prohibitively slow on Windows. Users with a long `$PATH` often report search times of around 20s, even when running `confluent version`. This is unacceptable UX, so plugins should be disabled by default on Windows. A user can enable them in ~/.confluent/config.json and they won't be disabled again in the lifetime of the configuration file.
Test & Review
-------------
Removed the `runtime.OS == "windows"` condition and tested manually.

Disable plugins by default on Windows

---

internal/pkg/ccloudv2/api-keys.go
internal/pkg/ccloudv2/byok.go
internal/pkg/ccloudv2/cdx.go
internal/pkg/ccloudv2/cmk.go
internal/pkg/ccloudv2/iam.go
internal/pkg/ccloudv2/identity-provider.go
internal/pkg/ccloudv2/kafka-quota.go
internal/pkg/ccloudv2/org.go
internal/pkg/ccloudv2/service-quota.go
internal/pkg/ccloudv2/stream-designer.go
internal/pkg/ccloudv2/utils.go

Release Notes
--------------
Bug Fixes
- Correctly propagate backend errors in ``confluent kafka quota list``
Checklist
---------
1. [CRUCIAL] Is the change for CP or CCloud functionalities that are already live in prod?
* yes: ok
What
----
Identical utility functions to extract next page tokens for list commands had identical code but different arguments because each v2 API in `ccloud-sdk-go-v2` defines its own `NullableString` struct.
This PR defines an interface w/ the two NullableString methods that we call (there are other methods, but we don't need them) so that we can unify all of these into one function.
Targeting `v3` instead of `main` because `v3` has more usages of this pattern (in `mds`) than `main`.
References
----------
n/a
Test & Review
-------------
Ran tests.
Manually …

Remove duplicated page token code

---

debian/Makefile
debian/patches/standard_build_layout.patch

Checklist
---------
* yes: ok
What
----
Packaging was failing because the leading "v" had not been stripped from the binary URL for versions >= v3.0.0
Test & Review
-------------
Ran the make target locally with < v3.0.0 and >= v3.0.0

Conditionally strip "v" from version in packaging

---

mk-files/release-notes.mk

Checklist
---------
* yes: ok
What
----
Last release, the version got set to `""` and the release notes were placed in the `//` directory. Now they should be correctly placed in the `/v3.5.0/` directory, for example.

Fix `make publish-release-notes-to-s3` target [skip secret scan]

---

debian/Makefile
debian/patches/standard_build_layout.patch

Reverts confluentinc/cli#1784
I misdiagnosed the error (RPM packaging downloads binaries, not archives), and this change made things worse.

Revert "Conditionally strip "v" from version in packaging"

---

debian/Makefile
debian/patches/standard_build_layout.patch

Checklist
---------
* yes: ok
What
----
If EL7, use `--define "debug_package %{nil}"`, else (EL8) use `--nodebuginfo`.
https://stackoverflow.com/questions/36983051/rpmbuild-how-to-skip-generation-of-debuginfo-packages-without-change-spec-fi
Test & Review
-------------
Not sure how to test, need help from DevProd team.

Fix incompatible `--nodebuginfo` flag in debian packaging

---

internal/pkg/cmd/prerunner.go
internal/pkg/dynamic-config/dynamic_context.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Allow ``confluent kafka topic produce`` to run when using a context created with ``confluent context create``
Checklist
---------
* yes: ok
What
----
The `anonymous-id` Kafka cluster id should not be checked for the `lkc-` prefix.
References
----------
Test & Review
-------------
Manual testing using the steps outlined in the ticket.

[CLI-2137] remove prefix check for `anonymous-id`

---

install.sh

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
The script needs updating to account for linux & alpine arm64 support. Currently, you see the following error:
`confluentinc/cli crit platform linux/arm64 is not supported.  Please contact Confluent support if you believe this is a mistake.`
Added the two os/arch combinations to the script, and removed a block of unsupported os/arch combinations since line 82 makes it redundant.
References
----------
Test & Review
-------------
Tested in a linux arm64 image:
```
./install.sh -b /usr/local/bin v3.5.1
confluentinc/cli info checking S3 for tag 'v3.5.1'
confluentinc/cli info …
```

Add linux & alpine arm64 to supported platforms in the installer script

---

internal/cmd/api-key/command.go
internal/cmd/api-key/command_list.go
internal/pkg/config/v1/context.go
internal/pkg/config/v1/context_state.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Prevent a panic which could occur in various ``confluent api-key`` commands
Checklist
---------
* yes: ok
What
----
If `State.Auth.User` is `nil` for whatever reason, a panic will result in `getAllUsers` when that function attempts to access the `User.Id` field.
References
----------
Test & Review
-------------
Followup: investigate the cause of incorrectly populated contexts.

Prevent panic in `api-key list` and `describe`

---

internal/pkg/config/v1/context_state.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fixed a decryption error when running ``confluent context list`` with old contexts from `~/.confluent/config.json`
Checklist
---------
* yes: ok
What
----
when logged in with older than 3.2.0, then you run newer 3.2.0, new salt and nonce will only be generated for current context that you're logged into. When running `context list`, other old contexts are only being read and i.e. some random mock contexts with mock tokens (not jwt format) would be decrypted, while there's no salt or nonce used to generate them in the first place. Add a check when decrypting tokens, only decrypt when: it is a valid format token, it's not …

Check salt length for old contexts as well to avoid incorrect salt length error in decryption

---

internal/pkg/featureflags/feature_flags.go
internal/pkg/featureflags/feature_flags_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
We don't appear to be using this for any flags, and it's responsible for multiple calls to `GetKafkaClusterForCommand()` at the start of almost every command.
References
----------
Test & Review
-------------
ran (updated) tests

Remove calls for cluster info in feature flags

---

mk-files/release.mk

What
----
Instead of the default commit history changelog, upload the release notes (which were previously only uploaded to S3) to GitHub.
https://goreleaser.com/customization/release/#custom-release-notes
Test & Review
-------------
Will test in this week's release.

Add custom release notes to GitHub release

---

internal/cmd/api-key/command_describe.go
internal/cmd/iam/command_rbac.go
internal/cmd/iam/command_rbac_role_describe.go
internal/cmd/iam/command_rbac_role_list.go

Release Notes
-------------
- N/A
New Features
- N/A (adds a new namespace but is hidden behind LD flag so not user-facing)
Bug Fixes
- N/A
Checklist
---------
* yes: ok
What
----
We are adding a new namespace `identity` behind an LD flag so that during EA we can introduce customers to the new role, `IdentityAdmin`,  in this namespace.
This PR adds the `identity` namespace to the `role describe` and `role list`.
References
----------
Test & Review
-------------
Tested manually in stag.
```
confluent iam rbac role describe IdentityAdmin               
+---------------+-----------------------------------------------------------------+
| Name          | IdentityAdmin …
```

[CIAM-2686] Add identity namespace behind an LD flag

---

internal/cmd/kafka/command_topic_consume.go
internal/cmd/kafka/command_topic_consume_onprem.go
internal/cmd/kafka/command_topic_produce.go
internal/cmd/kafka/command_topic_produce_onprem.go
internal/cmd/schema-registry/command_compatibility_validate.go
internal/cmd/schema-registry/command_compatibility_validate_onprem.go
internal/cmd/schema-registry/command_schema_create.go
internal/cmd/schema-registry/command_schema_create_onprem.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Correct file name autocompletion to ``avsc`` for Avro files
Checklist
---------
* yes: ok
What
----
Correct `MarkFlagFilename` for Avro files to `avsc`, the actual file suffix
References
----------
Test & Review
-------------

Correct `MarkFlagFilename` for Avro files to `avsc`

---

internal/pkg/secret/encryption_other.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Add suggestions to check CLI's access to ``/etc`` when encryption fails
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok  
What
----
Add suggestion to check access to /etc when cipher authentication fails
```
mhe@C02DV0KVMD6T cli % confluent kafka topic list
Error: cipher: message authentication failed. Check cli read/write permission to /etc.
```
References
----------
Test & Review
-------------

Add suggestion to check access to /etc when cipher authentication fails

---

internal/pkg/update/client.go

Release Notes
-------------
Bug Fixes
- Fix `confluent update` for Windows
Checklist
---------
* yes: ok
What
----
When updating from `ccloud` to `confluent`, the path was different, and we deleted `ccloud`. On Windows, the path can be different due to the difference between `confluent` and `confluent.exe`. This PR deletes that check since it's no longer relevant.
Test & Review
-------------
Waiting for validation from @sgagniere that this fixes the issue on Windows.

On `confluent update`, no longer remove CLI if path is different

---

internal/pkg/config/v1/context_state.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug on Windows preventing decryption of authentication tokens
Checklist
---------
* yes: ok
What
----
Before decrypting the auth token and auth refresh token, the CLI checked for a non-nil `Salt`. Salt is not used on Windows and is always nil, resulting in the cli not decrypting the tokens.
References
----------
Test & Review
-------------
Manually tested on Windows (and Mac, to make sure this PR didn't introduce new bugs!) with the following steps:
`confluent login`
`confluent environment list`
Ran unit tests …

Don't check Salt on Windows

---

internal/cmd/api-key/command_describe.go
internal/cmd/connect/command_cluster.go
internal/cmd/connect/command_cluster_pause.go
internal/cmd/connect/command_cluster_resume.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Add argument autocompletion for `confluent api-key describe`
- Add support for autocompleting multiple arguments for `confluent connect cluster pause` and `confluent connect cluster resume`
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
The `api-key describe` change is self explanatory.
For `pause` and `resume`, I split the old `validArgs` function into two functions `validArgs` and `validArgsMultiple`, where only `validArgs` checks the length of args.
References
----------
n/a
Test & Review
-------------
Manual testing. For connect, I checked that I can autocomplete multiple arguments for `pause` and `resume` but not for …

Update autocompletion for `api-key describe` and `connect cluster pause/resume`

---

internal/cmd/asyncapi/command_export.go
internal/cmd/asyncapi/command_import.go
test/fixtures/output/asyncapi/asyncapi-spec.yaml

Release Notes
-------------
New Features
- Support for number of topic partitions in `confluent asyncapi export` 
Checklist
---------
Yes
What
----
- Add number of partitions in the AsyncAPI Specification file created using `confluent asyncapi export`. 
- The command `confluent asyncapi import` will check `x-partitions` field in Kafka bindings for each channel while creating a new topic. 
References
----------
Test & Review
-------------
Tested locally against devel account.

AsyncAPI: Export number of partitions

---

internal/cmd/ksql/command.go
internal/cmd/ksql/command_cluster_list.go
internal/pkg/ccloudv2/ksql.go
internal/pkg/cmd/flags.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug which could prevent some KSQL clusters from being listed in `confluent ksql cluster list`
Checklist
---------
* yes: ok
What
----
`ListKsqlClusters` in `pkg/ccloudv2/ksql.go` was missing pagination support.
References
----------
Test & Review
-------------
Ran all tests
Manual testing:
- created 3 ksql clusters
- checked that list shows all 3
- tested page token handling by manually setting the page size from 100 to 2 and checking that it still showed all 3
- did the same as above with a page size of 1

[CLI-2383] Add pagination to `ksql cluster list`

---

test/test-server/kafka_rest_router.go
test/test-server/quotas_handler.go
test/test-server/streamsharing_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
I'm splitting off some of the tangential changes from the CLI-2065 into separate PRs since that one is getting large.
The SDKs we're using already come with functions to convert strings and int32s to pointers so there's no need to write our own functions to do it. We also had two identical versions of the string to pointer function, which are both removed here.
References
----------
Test & Review
-------------
Tests still pass.

Replace our pointer conversion functions with SDK equivalents

---

internal/pkg/auth/sso/auth0_utils.go
internal/pkg/auth/sso/auth0_utils_test.go

Checklist
---------
* yes: ok
What
----
* `confluent login --url https://stag.cpdev.cloud/` was not working for SSO logins (note the trailing slash).
* Default to "prod" in case of an error
Test & Review
-------------
Unit tested changes.

Fix CCloud environment lookup for SSO login

---

internal/pkg/cmd/flags.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Context autocompletion extracts the key slice from a map, which is unordered. This means that the list order is not deterministic, which is causing a flaky autocompletion test.
This PR is a one line change to return a sorted key slice instead.
References
----------
Test & Review
-------------
Tests pass

Use sorted keys for context autocompletion

---

internal/pkg/config/v1/context.go

Checklist
---------
* yes: ok
What
----
A small papercut: After #1840, a environment named `""` was being created in the `environments` field of the configuration file. This has no impact, but we should still clean it up. The root cause is the `envId` field that gets passed into the following function is always `""`, except during tests (unit tests that should actually be integration tests) where it is not empty, but also has no impact and can be deleted. Will clean the relevant tests in the future.
Test & Review
-------------
All tests still pass.

Prevent `""` environment from being stored in configuration file

---

mk-files/cc-cli-service.mk

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
`diff`'s exit status is `0` for no differences, `1` for differences, and `>1` for errors. But bash interprets `1` as an error, so the script fails if there are differences.
The fix is to check that the exit code `$?` is less than 2.
References
----------
Test & Review
-------------
Manually tested with `DRY_RUN=true`. 
Since that run had a difference, I also changed the diff command to `diff=$$(diff -u $$a $$a)` to check success for no changes and `diff=$$(diff -u $$a)` to check failure for errors.
Open …

Fix diff in `update-db`

---

internal/cmd/asyncapi/command_export.go
test/asyncapi_test.go
test/fixtures/output/asyncapi/asyncapi-no-topics.yaml
test/fixtures/output/asyncapi/asyncapi-topic-specified.yaml
test/fixtures/output/asyncapi/export-no-topics.golden
test/fixtures/output/asyncapi/export-topic-specified.golden

Release Notes
-------------
New Features
- Add `--topics` flag to `confluent asyncapi export` to only export specified topics
Checklist
---------
* yes
What
----
- Added flag to allow user to specify a list of topics to export on asyncapi. If this parameter is set, we check that the topic is listed under `--topics` before exporting it
- Optional flag, default is still to export all topics
Test & Review
-------------
Tested on prod confluent cloud, create topics and schemas (with TopicNamingStrategy) and export a subset of them with `--topics topic1,topic2...`

[DGS-6655] AsyncAPI Export: Pass a list of topics to export as input

---

.goreleaser.yml
Makefile
debian/patches/standard_build_layout.patch
mk-files/release.mk

What
----
Add prebuilt Linux binaries to the GoReleaser pipeline. This is a first step before we can easily release to various package managers.
References
----------
https://goreleaser.com/customization/builds/#import-pre-built-binaries
Test & Review
-------------
Tested with `DRY_RUN=true`

Set up GoReleaser Pro

---

.goreleaser.yml
mk-files/release.mk
scripts/build_linux_glibc.sh

What
----
No need to break the GoReleaser run into two separate commands. We can build the Linux binaries first and add them as `prebuilt`. Also fixed some small bugs.

Fix GoReleaser Pro

---

internal/pkg/releasenotes/by_version.go
internal/pkg/releasenotes/release_notes.go

Checklist
---------
* yes: ok
What
----
`make release-notes` fails if the last release was out-of-order. Determine the latest release by sorting tags by semver.

Fix `make release-notes` for out-of-order releases

---

mk-files/release.mk

What
----
The `dist/` folder should only be deleted if it exists, and it shouldn't be cleaned at the start of `goreleaser release` since it contains the Linux binaries.

Fix dist folder management for `make gorelease`

---

.goreleaser.yml

What
----
All binaries/archives except for alpine were being uploaded to S3, since alpine has a unique ID to avoid naming conflicts.

Upload Alpine binaries/archives to S3

---

mk-files/cc-cli-service.mk

What
----
Fix the diff algorithm for `make update-db`. Sort by version, find the prior version (semver order, not chronological order), and compute the diff between those two migration files.
Test & Review
-------------
Manual testing

Support out-of-order releases for `make update-db`

---

.goreleaser.yml
Makefile
debian/patches/standard_build_layout.patch
mk-files/dockerhub.mk

Release Notes
-------------
New Features
- Publish linux/arm64 Docker image
What
----
Use GoReleaser to release to DockerHub, instead of mk-files/dockerhub.mk
Test & Review
-------------
Tested with `DRY_RUN=true` and the release was "successfully" published to DockerHub (due to https://github.com/goreleaser/goreleaser/issues/3988) 😬

Release to DockerHub with GoReleaser

---

internal/pkg/auth/auth_token_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Prevent `confluent login --organization-id` from logging users into the wrong SSO-enabled organization
Checklist
---------
* yes: ok
What
----
After logging in with SSO and obtaining the idp id, the organization resource id was not being sent in the final login request. Without the organization resource id, the backend interprets this as a request to log into the default organization. If that organization also uses the same idp, that request will succeed (*single* sign on), and inadvertently ignore the `organization-id` flag.
References
----------
Test & Review
-------------
Manually tested w/ @ivanhyf 's help …

[CLI-2496] Resolve issue causing users to log into the wrong SSO org

---

internal/cmd/kafka/utils.go
test/fixtures/output/kafka/describe-unknown-cluster-type.golden
test/kafka_test.go
test/test-server/cmk_handlers.go
test/test-server/utils.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
An `UNKNOWN` value is already supported, so we should use that instead of assuming that `DEDICATED` is the default case.
References
----------
Test & Review
-------------
Added an integration test.

[CLI-2504] Use `UNKNOWN` as the default instead of `DEDICATED` for cluster type

---

internal/cmd/asyncapi/command_export.go
internal/cmd/asyncapi/command_export_test.go
test/asyncapi_test.go

Release Notes
-------------
New Features
- Support topic prefixes ending with a wildcard (*) in `confluent asyncapi export --topics`
Checklist
---------
* yes
What
----
If `--topics` specified, split into prefixes and regular topics. Then check that a topic is either present in the list of specified topics or has a prefix given by the user, otherwise don't export it.
For added tests, we only care about the CLI output (are topics correct?) so reusing files. File check is not useful here
Test & Review
-------------
Tested on prod confluent cloud, create topics and schemas (with TopicNamingStrategy) and export a subset of them with `--topics topic1,topic2,prefix*...`

DGS-7258 Async API Ability to only export topics with prefix

---

test/fixtures/output/local/start.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
I noticed this while testing something else.
The `local kafka start` integration test can fail if you don't already have the latest image downloaded, because the string `Image is up to date for confluentinc/confluent-local:latest` is replaced with `Downloaded newer image for confluentinc/confluent-local:latest`.
So the test fails the first time you run it if you didn't run the `confluent local start` command before.
Since this golden file already uses regex, this PR just adds a bit more regex to allow for either string.
References
----------
Test & Review
------------- …

Update `local kafka start` golden file

---

internal/pkg/update/client.go
internal/pkg/update/os.go
internal/pkg/update/s3/object_key.go
internal/pkg/update/s3/public.go

Release Notes
-------------
Bug Fixes
- Fix `confluent update` checksum validation for Alpine Linux
Checklist
---------
* yes: ok
What
----
The checksum validation code was inferring the OS as "linux" instead of "alpine" when downloading the correct checksum.
Test & Review
-------------
Manual verification, since we don't have alpine-specific CI.

Fix `confluent update` for alpine

---

internal/pkg/config/v1/config.go
internal/pkg/secret/encryption_other.go
test/login_test.go
test/test-server/ccloud_handlers.go

Checklist
---------
* yes: ok
What
----
The new FedRAMP environment returns refresh tokens that have a different format, so the `v1\..*` regex no longer works. This PR prefixes all encrypted strings with "AES/GCM/NoPadding:" (encryption algorithm name) so we know if a refresh token is encrypted or not. The existence of that prefix + the correct platform name (i.e. "confluentgov.com") should be enough to know if we should encrypt a refresh token or not.
Test & Review
-------------
Manual testing with a FedRAMP test account.

Fix base64 decoding error

---

internal/pkg/flink/config/results.go
internal/pkg/flink/internal/controller/input_controller.go
internal/pkg/flink/internal/controller/table_controller.go
internal/pkg/flink/internal/store/store.go
internal/pkg/flink/internal/store/store_test.go

Checklist
---------
* yes: ok
What
----
We used to delete statements after their execution to save system resources, which should not be an issue anymore. This change introduces a config variable that allows to switch this behavior back on if we need it, but disables it by default.

KFS-906: chore: remove statement cleanup

---

go.mod
go.sum

Checklist
---------
* yes: ok
What
----
Add the fix from https://github.com/keybase/go-keychain/pull/99, prevents "warning: 'SecKeychainItemDelete' is deprecated" during the build process.
Test & Review
-------------
Tests still pass!

Bump go-keychain

---

internal/cmd/iam/command_pool_use.go

Checklist
---------
* yes: ok
What
----
Fix suggestion text for `confluent iam pool use`. Not sure why it says Flink.

Fix `iam pool use` typo

---

internal/pkg/cmd/authenticated_cli_command.go
internal/pkg/cmd/cli_command.go
internal/pkg/cmd/has_api_key_cli_command.go
internal/pkg/cmd/prerunner.go

Checklist
---------
* yes: ok
What
----
Move `CLICommand`, `AuthenticatedCLICommand`, and others out of the (previously 1000+ LOC) prerunner.go file. This is set up for standardizing our clients (Confluent Cloud, Confluent Hub, Kafka REST, Flink Gateway, etc).

Move command structs out of prerunner

---

internal/cmd/command.go
internal/cmd/pipeline/command.go
internal/cmd/pipeline/command_create.go
internal/cmd/pipeline/command_save.go
internal/cmd/pipeline/command_update.go
test/fixtures/output/pipeline/save-help.golden

Checklist
---------
* yes: ok
What
----
The `confluent pipeline save` command has been enabled for a while, so we should be ok to remove the feature flag to give the command some more stability in case of a LaunchDarkly outage.

Remove `pipeline save` feature flag

---

internal/cmd/flink/command_shell.go
internal/pkg/ccloudv2/flink_gateway.go
internal/pkg/flink/internal/controller/input_controller.go

Checklist
---------
* yes: ok
What
----
The token refresh in the SQL client was not working correctly. If the client was left open for >= 15mins, the JWT would expire causing errors in subsequent statements. To fix it, you would need to close and reopen the SQL client.
In order for the token refresh to work, we need to first refresh the control plane token and then swap it for a data plane token. This token can then be used in the GatewayClient.

fix: token refresh not working

---

internal/cmd/flink/command_shell.go
internal/pkg/flink/internal/controller/input_controller_test.go

Checklist
---------
* yes: ok
What
----
Function GetJwtTokenForV2Client was removed in #2002 causing the build on main to fail after #1991 was merged

fix: use new GetDataplaneToken function

---

internal/pkg/color/color.go
internal/pkg/flink/components/interactive_input.go
internal/pkg/flink/config/color.go
internal/pkg/flink/internal/controller/input_controller.go
internal/pkg/flink/internal/controller/input_controller_test.go
internal/pkg/flink/internal/controller/input_controller_utils.go
internal/pkg/flink/internal/highlighting/lexer.go
internal/pkg/flink/internal/highlighting/lexer_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Product wanted us to use different colors in the client for different purposes. Erros should be red, info white and and warnings yellow.
This is now also configurable from a central file.
References
----------
Test & Review
-------------

feat: use different colors for different types of information

---

docker/Dockerfile
internal/pkg/errors/strings.go

Release Notes
-------------
Bug Fixes
- Fix permission issue while running `confluent update` in Docker image
Checklist
---------
* yes: ok
What
----
`confluent update` has never worked on Docker due to the following error:
```
Error: update client failure: error updating CLI binary: open /bin/.confluent.new: permission denied
Suggestions:
Please submit a support ticket.
In the meantime, see link for other ways to download the latest CLI version:
https://docs.confluent.io/current/cli/installing.html
```
Also fix stylistic output while printing release notes.
Test & Review
-------------
Manual verification

Allow `confluent update` in Docker image

---

internal/pkg/ccloudv2/utils.go

Checklist
---------
* yes: ok
What
----
Forgot to add confluentgov.com to this list, only the internal environment existed until now.

Add confluentgov.com to list of cloud hostnames

---

internal/cmd/iam/command_rbac_role_binding.go
test/cli_test.go
test/fixtures/output/iam/rbac/role-binding/create-identity-pool-developer-read.golden
test/iam_test.go

Release Notes
-------------
Bug Fixes
- Fixes the 404 error when creating a role binding attached to an identity pool
Checklist
---------
* yes: ok
What
----
Granting roles on identityPool was returning 404 but the role was actually granted. This because the cli was trying to fetch the email for identityPool and failing
References
----------
https://confluentinc.atlassian.net/browse/KFS-950
Test & Review
-------------
Added integration 

[KFS-950] Fix 404 after role binding create pools

---

cmd/docs/main.go
internal/cmd/command.go
internal/cmd/stream-share/command.go

Checklist
---------
* yes: ok
What
----
Stream sharing has been GA for a while. Remove the feature flag to increase stability in case of a Launch Darkly outage, and generate documentation.

Remove `stream-share` feature flag

---

internal/cmd/api-key/command.go
internal/cmd/api-key/command_create.go
internal/cmd/api-key/command_list.go
internal/cmd/api-key/command_store.go
internal/cmd/api-key/command_use.go
test/api_key_test.go
test/fixtures/output/api-key/53.golden
test/fixtures/output/api-key/54.golden
test/fixtures/output/api-key/create-help.golden
test/fixtures/output/api-key/create-resource-autocomplete.golden
test/fixtures/output/api-key/describe-autocomplete.golden
test/fixtures/output/api-key/list-help.golden
test/fixtures/output/api-key/store-help.golden
test/fixtures/output/api-key/use-help.golden

Release Notes
-------------
New Features
- Autocompletion for `confluent api-key create --resource`
Checklist
---------
* yes: ok
What
----
Autocomplete the `--resource` flag with "cloud", the list of Kafka cluster IDs, KSQL cluster IDs, and the Schema Registry cluster ID (if it exists). Improve examples to include "cloud" and Schema Registry API keys.
```
% confluent api-key create --resource
lkc-8mm8z0     -- my-kafka-cluster
lksqlc-wzzvnm  -- my-ksql-cluster
lsrc-6oomr2    -- Stream Governance Package
cloud
```
Test & Review
-------------
Integration test

Autocomplete `api-key create --resource`

---

internal/pkg/flink/internal/controller/table_controller.go
internal/pkg/flink/internal/controller/table_controller_test.go
internal/pkg/flink/types/statements.go

Checklist
---------
* yes: ok
What
----
This fixes a NPE when opening up the row view after having moved the table row iterator. This bug was happening for instance when you moved the cursor to the top most row, then hit a key that triggers a rerender of the table (e.g. toggle auto refresh or toggle table mode) and then hit enter on that row. 
The NPE then happened because the iterator was moved out of bounds because it was reset too early. E.g.: 
1. user has first row selected 
2. user toggles auto refresh 
3. selectLastRow() is called and reset the iterator to the last row, but selectedRowIdx is still at 1! 
4. then the rowSelectionHandler is triggered thinks the selected row is still at 1, and then moves the …

fix: reset iterator and selected row idx correctly

---

internal/pkg/flink/internal/results/result_converter.go
internal/pkg/flink/internal/results/result_converter_test.go
internal/pkg/flink/test/generators/results.go
internal/pkg/flink/types/statements.go

Checklist
---------
* yes: ok
What
----
Fixes a bug where the table was not updated correctly and every row was just interpreted as an Insert operation.
We were using int32 to parse the op response from gateway, while it's actually a float64, leading to the value always being set to 0 -> Insert Operation +I.

fix: use float64 type for op

---

internal/cmd/kafka/command_acl.go
internal/cmd/kafka/command_acl_create.go
internal/cmd/kafka/command_acl_create_onprem.go
internal/cmd/kafka/command_acl_delete_onprem.go
internal/cmd/kafka/command_acl_list.go
internal/cmd/kafka/command_acl_list_onprem.go
internal/cmd/kafka/kafka_api.go
internal/pkg/acl/acl.go
internal/pkg/acl/acl_test.go
internal/pkg/errors/error_message.go
test/fixtures/output/kafka/acl/delete-json.golden
test/fixtures/output/kafka/acl/delete-prompt.golden
test/fixtures/output/kafka/acl/delete-yaml.golden
test/fixtures/output/kafka/acl/delete.golden
test/fixtures/output/kafka/acl/list-json.golden
test/fixtures/output/kafka/acl/list-yaml.golden
test/fixtures/output/kafka/acl/list.golden
test/test-server/kafka_rest_router.go

Checklist
---------
* yes: ok
What
----
We no longer need to get the list of users, since we can mandate that the "list" endpoint returns resource IDs instead of numeric IDs by passing `UserV2:*` to the backend.
Test & Review
-------------
Manual testing, although still not done

Remove extra API call from `kafka acl list`

---

internal/pkg/color/color.go
internal/pkg/flink/internal/controller/input_controller_utils.go
internal/pkg/flink/internal/highlighting/lexer.go
internal/pkg/flink/internal/highlighting/lexer_test.go
internal/pkg/flink/internal/reverseisearch/reverse_i_search.go

Release Notes
-------------
Bug Fixes
- Use the default terminal colours in flink shell to make them more readable on light backgrounds
Checklist
---------
* yes: ok
What
----
The only colors that are user-defined and we can use from the user config are: text, bold text and (text) selection - see picture at the bottom. That means, every time we use another color, we’re at risk that some user won’t be able to see some information properly, if the terminal doesn’t configure proper alternatives for the default colors. For example, ohmyzsh uses a bunch of colors and if I change my theme there are some things that I can’t read properly anymore, see last example:
The defined user colors can be used by basically not adding …

KFS-963 feat: use default terminal color for infos

---

internal/pkg/flink/internal/controller/input_controller.go
internal/pkg/flink/internal/controller/input_controller_test.go

Checklist
---------
* yes: ok
What
----
We only want to print the "no rows" message if status detail field is not set.

chore: only show no rows message when status details is empty

---

internal/cmd/organization/command_describe.go
internal/cmd/organization/command_update.go
internal/pkg/ccloudv2/flink.go
internal/pkg/ccloudv2/org.go
internal/pkg/errors/catcher.go

Checklist
---------
* yes: ok
What
----
Make sure all Flink related commands that get --environment as an argument (create, delete, describe and list compute pool) fail with a descriptive message, for example:
```
Tested on STAG: env-mzoyn2  does not exist
mbpro16 :: confluentinc/cli » ./dist/confluent_darwin_amd64_v1/confluent  flink compute-pool list --environment env-mzoyn2                                                    
Error: env-mzoyn2 not found or access forbidden: Forbidden Access: 403 Forbidden
Suggestions:
List available env-mzoyn2s with `confluent env-mzoyn2 list`.
```

FLINKCC-100: Create compute pool with wrong-env should fail with descriptive error

---

internal/pkg/dynamic-config/dynamic_context.go

Release Notes
-------------
Bug Fixes
- Prevents panic when trying to run `kafka client-config create` commands
Checklist
---------
* yes: ok
What
----
Fixes a nil dereference panic that can occur when `kafka client-config create` is run if Schema Registry is not enabled for the current environment
References
----------
https://confluentinc.atlassian.net/browse/CLI-2574

fixing panic in kafka client-config create

---

internal/pkg/flink/app/application.go
internal/pkg/flink/app/application_test.go
internal/pkg/flink/internal/store/store_test.go
internal/pkg/flink/types/statements.go

Checklist
---------
* yes: ok
What
----
We now use the interactive table when either of these cases is true for a non-local statement:
- the results include a next page token
- the statement is a SELECT statement 
- the results have more than 3 columns
In all other cases the basic table is used.
**Note: we need the additional isSelectStatement check before deciding based on the number of columns, because of statements like this one:  `SELECT NOW(), COUNT(*) FROM (VALUES (1), (2), (3));`. This is a statement with retractions, but it only has two columns. You definitely want to use the interactive mode here though, so you can check out the results in both the changelog and the table mode. Because you never now what …

feat: adjust logic when to show basic vs. interactive table

---

internal/pkg/flink/components/.snapshots/TestTableViewTestSuite-TestTableShortcutsShouldDisplayChangelogMode
internal/pkg/flink/components/.snapshots/TestTableViewTestSuite-TestTableShortcutsShouldDisplayPause
internal/pkg/flink/components/.snapshots/TestTableViewTestSuite-TestTableShortcutsShouldDisplayPlay
internal/pkg/flink/components/.snapshots/TestTableViewTestSuite-TestTableShortcutsShouldDisplayTableMode
internal/pkg/flink/internal/controller/interactive_output_controller.go
internal/pkg/flink/internal/controller/interactive_output_controller_test.go

Checklist
---------
* yes: ok
What
----
Automatically pause the auto refresh when a user triggers a scroll event (arrow up/down, jump keys U/D)
**Note: merge after   #2052 **

feat: pause refresh when user triggers scroll event

---

internal/pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementPrintsUserInfo
internal/pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestRenderMsgAndStatusNonLocalNonFailedStatements-statement_with_name
internal/pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestRenderMsgAndStatusNonLocalNonFailedStatements-statement_without_name
internal/pkg/flink/internal/controller/statement_controller.go
internal/pkg/flink/internal/controller/statement_controller_test.go
internal/pkg/flink/internal/store/store.go
internal/pkg/flink/internal/store/store_test.go
internal/pkg/flink/types/statements.go

Release Notes
-------------
Checklist
---------
* yes: ok
What
----
- Adjusted the message sent while waiting for results to be ready
- Also print status
- Print complete/running status after statement is ready
- properly account for gateway response time when calculating timeout
References
----------
Test & Review
-------------
Tests updated

Refactor/KFS-984 and KFS-982 update out msg and timeout accounts for gateway response time

---

internal/cmd/flink/command_shell.go
internal/pkg/flink/config/local_statements.go
internal/pkg/flink/internal/store/store.go

Checklist
---------
* yes: ok
What
----
Removes `execution.runtime-mode` from the default properties, as this is not needed anymore and could lead to requests being rejected when server-side validation is introduced

chore: remove execution.runtime-mode as it's not needed anymore

---

internal/pkg/ccloudv2/flink_gateway.go

Release Notes
-------------
Make client-generated Flink statement name (that is based on uuid) 2 characters shorter, as the current last two characters are:
'-'  + one alphanumeric character, which makes the name pattern looking somewhat clumsy. 
Checklist
---------
* yes: ok
What
----
The naming pattern before this PR was picked just to make the whole name shorter without looking much how it looks in the end.  Example: the following statement name `97590109-f7c8-4c5e-b` would become `97590109-f7c8-4c5e` instead.

make flink statement name two characters shorter

---

internal/cmd/local/command_kafka_start.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Print an error message when `confluent local kafka start` is run from an AMD64 binary on an ARM64 machine
Checklist
---------
* yes: ok
What
----
m2 machine supports running amd64 software even though it's arm64 natively, which will cause problem that cli will try to create a amd64 container that can't be run on arm64 m2. Add a arch check in `confluent local kafka start`.
References
----------
Test & Review
-------------

[confluent-local] verify machine arch matches cli arch before starting docker

---

internal/cmd/asyncapi/account_details.go
internal/cmd/schema-registry/command_schema_describe.go
test/test-server/schema_registry_handlers.go

Release Notes
-------------
Bug Fixes
- Fix "type" output in `confluent schema-registry schema describe` and properly format Avro schemas
Checklist
---------
* yes: ok
What
----
Fixing a typo from an earlier PR, this time with updated tests 🤦‍♂️
Test & Review
-------------
Modify tests to match backend response.

[CLI-2592] Correctly default to Avro when a schema type is not returned

---

internal/cmd/api-key/command_store.go

Release Notes
-------------
Bug Fixes
- Prevents a panic when passing a non-existent Kafka cluster to `confluent api-key store --resource`
Checklist
---------
* yes: ok
What
----
A panic can occur when the user tries to store an api-key secret for a resource that doesn’t exist anymore for that api-key.
References
----------
https://confluentinc.atlassian.net/browse/CLI-2589

CLI-2589 fix panic when running `api-key store` with resource flag

---

internal/pkg/cmd/run_requirements_test.go
internal/pkg/config/v1/config.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Clear error message when user runs on premise commands when logged into Confluent Cloud
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
if logged in to cloud but runs a cp cmd, will notify:
```
mhe@C02DV0KVMD6T cli % confluent cluster list
Error: this is not a Confluent Cloud command. You must log in to Confluent Platform to use this command
Suggestions:
Log in with `confluent login --url <mds-url>`.
Run command with "--help" to see available commands.
```
References
----------
Test & Review
-------------

notify context is cloud when run on-prem cmds after cloud login

---

internal/pkg/update/client.go
internal/pkg/update/client_test.go
internal/pkg/update/s3/public.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
got a panic report that index was out of range (-1) on line 93. that could only happen if `nextMajorVersion` was declared to be `v0` which makes no sense. Return a `failed to obtain correct version info` error if that happens.
References
----------
https://confluent.slack.com/archives/C010Y0EP5MZ/p1689092199750689
Test & Review
-------------

check index in range when getting minor version number in update

---

cmd/lint/main.go
internal/cmd/kafka/command_topic_produce.go
internal/pkg/cmd/flags.go
internal/pkg/errors/error_message.go
test/fixtures/output/asyncapi/export-help.golden
test/fixtures/output/kafka/topic/consume-help-onprem.golden
test/fixtures/output/kafka/topic/consume-help.golden
test/fixtures/output/kafka/topic/produce-help-onprem.golden
test/fixtures/output/kafka/topic/produce-help.golden
test/fixtures/output/kafka/topic/produce-no-schema.golden

Release Notes
-------------
New Features
- Support passing schema IDs to the `--schema` flag in `confluent kafka topic produce`
Checklist
---------
* yes: ok
What
----
In https://confluentinc.atlassian.net/browse/CLI-2182, we want to support schemas for message keys. Currently, this would require adding `--key-schema` and `--key-schema-id` to mirror `--schema` and `--schema-id`. This PR allows passing IDs to `--schema` so we can deprecate `--schema-id`. (... so in a following PR we only need to add `--key-schema`).
Test & Review
-------------
Updated relevant tests

Deprecate `kafka topic produce --schema-id`

---

internal/cmd/api-key/command_list.go
internal/cmd/kafka/command_acl.go
internal/cmd/kafka/command_acl_create.go
internal/cmd/kafka/command_acl_delete.go
internal/cmd/kafka/command_acl_list.go
internal/cmd/kafka/command_quota_create.go
internal/cmd/kafka/command_topic_consume.go
internal/cmd/kafka/command_topic_consume_onprem.go
internal/cmd/kafka/command_topic_produce.go
internal/cmd/kafka/command_topic_produce_onprem.go
internal/cmd/kafka/kafka_api.go
internal/cmd/local/command_kafka_topic_consume.go
internal/cmd/local/command_kafka_topic_produce.go
internal/cmd/login/command.go
internal/pkg/errors/error_message.go
test/fixtures/output/kafka/quota/create-no-ingress.golden
test/fixtures/output/kafka/topic/produce-help.golden

Checklist
---------
* yes: ok
What
----
A recent version of Cobra added two functions to mark flags as (1) required together and (2) mutually exclusive. Use the built-in functions instead of an inconsistent hardcoded solution.
Also mark `--output` as deprecated in `confluent kafka topic produce`, since it doesn't get used and can be deleted in the next major version.

Use built-in flag combination primitives from Cobra

---

internal/pkg/cmd/prerunner.go
internal/pkg/config/v1/config.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Add a suggestion to use `confluent kafka cluster` when users run the on-premises `confluent cluster` command while logged in to Confluent Cloud
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
```
mhe@C02DV0KVMD6T cli % confluent cluster list --context login-mhe@confluent.io-https://confluent.cloud
Error: `confluent cluster list` is not a Confluent Cloud command. Did you mean `confluent kafka cluster list`?
Suggestions:
If you are a Confluent Cloud user, run `confluent kafka cluster list` instead.
If you are attempting to connect to Confluent Platform, login with `confluent login --url <mds-url>` to use `confluent cluster list`. …
```

suggest `confluent kafka cluster` when run `confluent cluster` while logged in to cloud

---

internal/cmd/asyncapi/account_details.go
internal/cmd/kafka/command_link_configuration_list.go
internal/cmd/kafka/command_link_configuration_update.go
internal/cmd/kafka/command_link_create.go
internal/cmd/kafka/command_link_delete.go
internal/cmd/kafka/command_link_describe.go
internal/cmd/kafka/command_link_list.go
internal/cmd/kafka/command_mirror.go
internal/cmd/kafka/command_mirror_create.go
internal/cmd/kafka/command_mirror_describe.go
internal/cmd/kafka/command_mirror_failover.go
internal/cmd/kafka/command_mirror_list.go
internal/cmd/kafka/command_mirror_pause.go
internal/cmd/kafka/command_mirror_promote.go
internal/cmd/kafka/command_mirror_resume.go
internal/cmd/kafka/utils.go
internal/pkg/cmd/flags.go
internal/pkg/config/v1/environment_context.go
test/byok_test.go
test/environment_test.go
test/fixtures/output/kafka/create-availability-autocomplete.golden
test/fixtures/output/kafka/create-type-autocomplete.golden
test/iam_test.go
test/kafka_test.go

Release Notes
-------------
Bug Fixes
- Fix autocompletion of `--availability` and `--type` flags in `confluent kafka cluster create`
Checklist
---------
* yes: ok
What
----
Fix autocompletion, consolidate Kafka REST helper function, improve overall formatting

Fix autocompletion for `kafka cluster create`, formatting improvements

---

internal/pkg/flink/app/application.go
internal/pkg/flink/app/application_test.go

Checklist
---------
* yes: ok
What
----
This makes it so that we only use the interactive output when we have a next page token or the statement is a select statement. We do not factor in the number of columns in this decision anymore. 
The main reason for this is the DESCRIBE statement. With the results of the DESCRIBE statement being displayed in the interactive table, the user needs to run the DESCRIBE, then memorize the field names and schema, and then write their query in one go. It is much easier for the user, if we just print the fields and the schema, so that the subsequent queries can be written without going back and forth between the terminal and the interactive table.

fix: make basic output the default regardless of number of columns

---

internal/pkg/flink/internal/controller/statement_controller.go
internal/pkg/flink/internal/controller/statement_controller_test.go

Release Notes
-------------
Checklist
---------
* yes: ok
What
----
When submitting persistent queries like INSERT INTO that run in the background we attach to the job and listen for errors and the user can exit this mode now pressing also ctrlC, ctrlD and so on, which are the regular cancelEvents for the other statements. 
References
----------
Test & Review
-------------
unit tests

feat/KFS-1058-exit attached mode upon pressing ControlC, ControlD, ControlQ..

---

internal/cmd/asyncapi/command_export.go
internal/cmd/asyncapi/command_import.go
test/fixtures/input/asyncapi/asyncapi-spec.yaml
test/fixtures/output/asyncapi/asyncapi-spec.yaml
test/fixtures/output/asyncapi/asyncapi-topic-specified.yaml

Release Notes
-------------
Bug Fixes
- Fix `confluent asyncapi import` and `confluent asyncapi export` to follow AsyncAPI documentation for Kafka channel bindings, with explicit fields for `bindingVersion`, `partitions`, and `topicConfiguration`.
Checklist
---------
* yes: ok
What
----
We are not outputting Kafka bindings in the correct format. Previously, our Kafka bindings struct looked like this (x- in front of a field means that it is custom, not specified in the asyncapi documentation)
```
type confluentBinding struct {
XPartitions int32             `json:"x-partitions,omitempty"`
XConfigs    map[string]string `json:"x-configs,omitempty"`
}
```
However, not all of these fields should have been custom. The …

DGS-6578 AsyncAPI: Add correct Kafka bindings section

---

go.mod
go.sum
internal/cmd/kafka/command_link_list.go
internal/cmd/kafka/command_link_list_onprem.go
internal/pkg/ccloudv2/kafkarest.go
test/test-server/kafka_rest_router.go

Release Notes
-------------
Bug Fixes
- Correctly display Confluent Platform mirror topics in `confluent kafka link list --include-topics`
Checklist
---------
1. [CRUCIAL] Is the change for features that are already live in prod? yes
What
----
For CCloud, revert the workaround introduced in https://github.com/confluentinc/cli/pull/1912 since it is no longer needed.
For CP, fix the issue by changing TopicsNames to TopicName.
References
----------
KGLOBAL-3306
Test & Review
-------------
- Manual tested on CCloud with 3 mirror topics
- make test

KGLOBAL-3306: Fix TopicsNames to TopicName

---

internal/cmd/kafka/command_broker_describe.go
internal/cmd/kafka/command_cluster.go
internal/cmd/kafka/command_cluster_configuration.go
internal/cmd/kafka/command_cluster_configuration_describe.go
internal/cmd/kafka/command_cluster_configuration_describe_test.go
internal/cmd/kafka/command_cluster_configuration_list.go
internal/cmd/kafka/command_cluster_configuration_update.go
internal/cmd/kafka/command_cluster_configuration_update_test.go
internal/cmd/kafka/command_link_configuration_list.go
internal/pkg/ccloudv2/kafkarest.go
test/fixtures/output/kafka/broker/describe-1-config.golden
test/fixtures/output/kafka/broker/describe-1.golden
test/fixtures/output/kafka/broker/describe-all-config.golden
test/fixtures/output/kafka/broker/describe-all.golden
test/fixtures/output/kafka/cluster/configuration/describe-help.golden
test/fixtures/output/kafka/cluster/configuration/describe.golden
test/fixtures/output/kafka/cluster/configuration/help.golden
test/fixtures/output/kafka/cluster/configuration/list-help.golden
test/fixtures/output/kafka/cluster/configuration/list.golden
test/fixtures/output/kafka/cluster/configuration/update-help.golden
test/fixtures/output/kafka/cluster/configuration/update.golden
test/fixtures/output/kafka/cluster/help-onprem.golden
test/fixtures/output/kafka/cluster/help.golden
test/fixtures/output/kafka/link/configuration-list-plain-bidirectional-link.golden
test/fixtures/output/kafka/link/configuration-list-plain.golden
test/kafka_test.go
test/test-server/kafka_rest_router.go

Release Notes
-------------
New Features
- Add `confluent kafka cluster configuration` commands for managing dedicated cluster configurations
Checklist
---------
* yes: ok
What
----
Add the ability to describe, list, and update configurations for dedicated clusters. This is missing functionality that exists in bin/kafka-configs.
Test & Review
-------------
Unit tests and integration tests

[CLI-2025] Add `kafka cluster configuration` commands

---

internal/pkg/ccloudv2/flink_gateway.go
internal/pkg/ccloudv2/flink_gateway_test.go
internal/pkg/errors/flink/flink_errors.go
internal/pkg/errors/flink_errors.go
internal/pkg/flink/internal/controller/statement_controller.go
internal/pkg/flink/internal/controller/statement_controller_test.go
internal/pkg/flink/internal/store/store.go
internal/pkg/flink/internal/store/store_test.go
internal/pkg/flink/internal/store/store_utils.go
internal/pkg/flink/types/statement_error.go

Checklist
---------
* yes: ok
What
----
We want to propagate the status code from the gateway client. Added a new error type FlinkError which implements ErrorWithSuggestion and Coder so we just extend existing functionalities with extra error code.

added new FlinkError to propagate status code

---

internal/cmd/billing/command_cost_list.go
test/fixtures/output/billing/cost/list-help.golden
test/fixtures/output/billing/cost/list-missing-flag.golden

Checklist
---------
* yes: ok
What
----
Example was missing "cost".

Fix `billing cost list` typo

---

.goreleaser-build.yml
internal/cmd/command.go
internal/cmd/update/command.go

Release Notes
-------------
New Features
- Suggest updating with `brew upgrade` if installed with Homebrew
Checklist
---------
* yes: ok
What
----
If updates are disabled (CP or Homebrew), mark `confluent update` as hidden and return a helpful suggestion on execution.
* For Homebrew, suggest `brew upgrade`
* For CP, suggest independently installing a binary according to https://docs.confluent.io/platform/current/installation/versions-interoperability.html#confluent-cli
Test & Review
-------------
Manually tested all of the negative paths, added tracing to debug the positive path, if needed.

[CLI-2576] Detect Homebrew installation on `confluent update`

---

internal/cmd/command.go
internal/pkg/cmd/prerunner_test.go
internal/pkg/cmd/test_helpers.go
internal/pkg/config/v1/platform.go
internal/pkg/featureflags/feature_flags.go

Checklist
---------
* yes: ok
What
----
Now the CLI automatically uses the LaunchDarkly Test environment to fetch feature flags when the user is not logged into the prod environment. Setting the `XX_LAUNCH_DARKLY_TEST_ENV` variable is now no longer needed.
References
----------
https://confluentinc.atlassian.net/browse/CLI-2624
Test & Review
-------------

CLI automatically uses LD test env when not logged into prod

---

Makefile
debian/patches/standard_build_layout.patch

Checklist
---------
* yes: ok
What
----
`go install` should always use the GOOS and GOARCH of the current system, so default to `""` for both.

[CLI-2673] Fix cross-compilation for linux

---

internal/pkg/config/v1/api_key_pair.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix authentication issue in `confluent kafka topic [produce | consume]` on Windows
Checklist
---------
* yes: ok
What
----
Encrypted api secrets don't have an `AesGcm` prefix, so we shouldn't check for that before decrypting secrets on Windows.
References
----------
Test & Review
-------------
Manual testing on Windows, Linux, and MacOS.
Next: fix an issue on Windows with `confluent kafka topic produce` where `Ctrl-C` causes a panic and `Ctrl-D` does nothing. In other words, the only way to exit out of `consume` on Windows is to panic.
This doesn't appear to be …

Fix api secret decryption issue on Windows

---

.goreleaser.yml

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Recently the `gorelease` make target has been failing with
```
error checking for default branch            projectID= statusCode=404 error=GET https://api.github.com/repos//: 404 Not Found []
```
Looking at the goreleaser docs, it looks like 1.19 introduced a `base` section under `pull_requests`. I've added that section to our goreleaser file with the base branch being `master`.
References
----------
Test & Review
-------------
Will try it out on next release...

Add base to goreleaser brews

---

internal/cmd/context/command_update.go
internal/cmd/iam/command_groupmapping_update.go
internal/cmd/iam/command_pool_update.go
internal/cmd/iam/command_provider_update.go
internal/cmd/kafka/command_cluster_update.go
internal/cmd/kafka/command_quota_update.go
internal/cmd/pipeline/command_update.go
internal/pkg/errors/error_message.go
internal/pkg/errors/no_op_error.go
test/fixtures/output/context/update/1.golden
test/fixtures/output/iam/identity-pool/no-op-update.golden
test/fixtures/output/kafka/cluster/create-flag-error.golden
test/fixtures/output/kafka/quota/no-op-update.golden
test/iam_test.go
test/kafka_test.go

Release Notes
-------------
Checklist
---------
* yes: ok
What
----
Several resources' `update` commands check for a no-op update request and return an error instead of sending an extraneous API request. This PR standardizes the error checking and error string format.
This includes `iam group-mapping, pool, provider`, `pipeline`, `kafka cluster, quota` and `context`.
References
----------
https://confluentinc.atlassian.net/browse/CLI-2680
Test & Review
-------------
Added no-op `update` subcommand integration tests.

[CLI-2680] Adding global no-op update error checking + message

---

internal/cmd/api-key/command_describe.go
internal/cmd/api-key/command_list.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
When listing api keys with `confluent api-key list`, we call `c.getEmail` for every single key.
This function first checks if the user ID belongs to a service account. If it doesn't, then this function will next check if it belongs to an auditlog service account, and it does this by making a request to `/api/me`. It then finally checks if the ID belongs to a user account.
The problem here is that this will make a redundant http request for every key attached to a user, which can be quite a lot. A simple fix is to just move the user account check ahead of the auditlog …

Remove extraneous GET requests in `confluent api-key list`

---

internal/cmd/connect/command_event.go
internal/cmd/connect/command_plugin.go
test/fixtures/output/connect/event/help.golden
test/fixtures/output/connect/help-onprem.golden
test/fixtures/output/connect/help.golden
test/fixtures/output/connect/plugin/help-onprem.golden
test/fixtures/output/connect/plugin/help.golden

Release Notes
-------------
New Features
- Add custom connector support for `confluent connect cluster` commands
Checklist
---------
* yes: ok
What
----
Changed description of plugin and event to show that only managed connectors support those commands.
References
----------
[CLI Command design](https://confluentinc.atlassian.net/wiki/spaces/CPU/pages/3121446976/Custom+Connector+CLI+Design+Spec)
Test & Review
-------------
Ran a local build and was able to see the new descriptions

Updated connect cli command descriptions

---

internal/cmd/kafka/command_mirror.go
internal/cmd/kafka/command_mirror_describe.go
internal/cmd/kafka/command_mirror_list.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Prevent errors for certain statuses in `confluent kafka mirror describe` and `confluent kafka mirror list`
Checklist
---------
* yes: ok
What
----
The ccloud-sdk-go-v2 version of the kafkarest sdk enforces a requirement that the mirror status be one of `active`, `failed`, `paused`, `stopped`, or `pending_stopped`. However, the backend can return additional statuses `source_unavailable`, `link_failed`, or `link_stopped`.
This PR reverts the SDK switch for `mirror list`, `mirror describe`, and the mirror autocompletion.
This is meant to be temporary until the SDK is updated to account for this.
References
----------
Test & …

Revert sdk change for `confluent kafka mirror list` and `describe`

---

internal/pkg/flink/app/application.go
internal/pkg/flink/internal/autocomplete/docs_completer.go
internal/pkg/flink/internal/history/history.go
internal/pkg/flink/internal/utils/input.go

Release Notes
-------------
Bug Fixes
- Resolve `confluent flink shell` panic when `/dev/tty` is inaccessible
Checklist
---------
* yes: ok
What
----
When starting a flink application via the `confluent flink shell` command, [this function](https://github.com/confluentinc/go-prompt/blob/master/input_posix.go#L69) can panic if the file `/dev/tty` is inaccessible (e.g. running cli in containerized environment, or cli doesn’t have permission). Since the panicking function is used outside of CLI source, we should `recover()` and format an error for the user.
References
----------
https://confluentinc.atlassian.net/browse/CLI-2683

Recover from panic when opening dev/ttv and format error

---

internal/cmd/api-key/command_list.go
test/api_key_test.go
test/fixtures/output/api-key/56.golden
test/fixtures/output/api-key/57.golden
test/fixtures/output/api-key/58.golden
test/fixtures/output/api-key/59.golden
test/test-server/srcm_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Some system tests recently failed because API keys with a single resource don't show up in `confluent api-key list`. The cause is that the associated resource is listed in the `Resource` field of the http response and not in the `Resources` field, which is given preference for multicluster enabled orgs.
This PR only uses the list in `Resources` if it is non-empty.
I also added a check on the test handler for `/srcm/v2/clusters/{id}` to verify that the `{id}` matches the test backend SR cluster id. There was previously a confusing golden file where the SR cluster given to …

Show single-resource API keys for multicluster enabled orgs

---

internal/network/command.go
internal/network/command_delete.go
pkg/ccloudv2/networking.go
pkg/resource/resource.go
test/fixtures/output/network/delete-help.golden
test/fixtures/output/network/delete-network-not-exist.golden
test/fixtures/output/network/delete-network-with-dependency.golden
test/fixtures/output/network/delete-prompt.golden
test/fixtures/output/network/delete.golden
test/fixtures/output/network/help.golden
test/network_test.go
test/test-server/networking_handlers.go

Release Notes
-------------
New Features
* Add `confluent network delete` to delete a specific network.
Checklist
---------
* yes: ok
What
----
Added the `confluent network delete` command
References
----------
Test & Review
-------------
Added …

[TRAFFIC-9067] - Add `confluent network delete` command

---

internal/kafka/command_topic.go
internal/kafka/command_topic_produce.go
internal/kafka/command_topic_produce_onprem.go
internal/local/command_kafka_topic_produce.go

Release Notes
-------------
Bug Fixes
- Resolved a close of closed channel panic in `topic produce`.
Checklist
---------
* yes: ok
What
----
Building off of the ideas in https://github.com/confluentinc/cli/pull/2199, this race condition seems to have been resolved. 
Basically, sending an interrupt signal via `^C` now writes `\u0004` (Unicode encoding of `^D`) to the `input` channel, which can normally never receive this value, since writing `^D` to `stdIn` will just close the channel. 
Now, in the loop over `input`, we `break` if we get an error from the Scanner or if the value received from the `input` channel is `^D` (meaning a shutdown has been triggered with `^C`). This means the `input` channel is only closed …

[CLI-2642] Resolve race condition resulting in double channel close panic in `topic produce` commands

---

.github/CODEOWNERS
pkg/flink/config/local_statements.go
pkg/flink/internal/autocomplete/.snapshots/TestSetAutoCompletionSnapshot
pkg/flink/internal/autocomplete/set_completer.go
pkg/flink/internal/store/.snapshots/TestProcessSetStatement-should_return_all_keys_and_values_from_config_if_configKey_is_empty
pkg/flink/internal/store/.snapshots/TestProcessSetStatement-should_return_all_keys_and_values_from_config_if_configKey_is_empty_after_updates
pkg/flink/internal/store/store.go
pkg/flink/internal/store/store_test.go
pkg/flink/internal/store/store_utils.go
pkg/flink/internal/store/store_utils_test.go

Checklist
---------
* yes: ok
What
----
We changed the names of some of the config options we accept in the backend, this PR is to reflect those changes in the sql client. Included changes:
- `catalog` is now named `sql.current-catalog`
- `default_database` is now named `sql.current-database`
- `table.local-time-zone` is now named `sql.local-time-zone` and has a GMT instead of a UTC prefix for the timezone offset
- `table.results-timeout` is now named `client.results-timeout` and is set in milliseconds instead of seconds
References
----------
Config options doc:
https://confluentinc.atlassian.net/wiki/spaces/FLINK/pages/3022523030/WIP+SET+USE+Configuration

feat: update SET config options to reflect recent backend changes

---

internal/api-key/command.go
internal/kafka/command_clientconfig_create.go
internal/schema-registry/command_cluster_delete.go
pkg/config/config_test.go
pkg/config/context.go
pkg/config/schema_registry_cluster.go
pkg/config/test_json/account_overwrite.json
pkg/config/test_json/stateful_cloud.json
pkg/config/test_json/stateful_cloud_save.json
pkg/config/test_json/stateful_onprem.json
pkg/config/test_json/stateful_onprem_save.json
pkg/config/test_json/stateless_cloud.json
pkg/config/test_json/stateless_onprem.json
pkg/dynamic-config/dynamic_context.go

Checklist
---------
* yes: ok
What
----
Thanks @MuweiHe for pointing out that as of #2134, we are essentially not using Schema Registry API keys in the CLI anymore. Rewrote `confluent kafka client-config create` to grab the Schema Registry cluster from the backend (this improves consistency) instead of the configuration file, and stopped marking Schema Registry API keys as "current" in `api-key list`. This allows us to deprecate the Schema Registry field in the configuration file!
Test & Review
-------------

[CLI-2686] Deprecate "schema_registry_clusters" configuration field

---

internal/network/command.go
internal/network/command_describe.go
internal/network/command_update.go
pkg/ccloudv2/networking.go
test/fixtures/output/network/describe-help.golden
test/fixtures/output/network/describe-missing-id.golden
test/fixtures/output/network/describe.golden
test/fixtures/output/network/help.golden
test/fixtures/output/network/update-help.golden
test/fixtures/output/network/update-missing-args.golden
test/fixtures/output/network/update-missing-flags.golden
test/fixtures/output/network/update-network-not-exist.golden
test/fixtures/output/network/update.golden
test/network_test.go
test/test-server/networking_handlers.go

Checklist
---------
* yes: ok
What
----
* Added the `confluent network update` command. Note that there is a `--zones-info` flag in the original design and it's a mistake. The network update API does not support updating `zonesInfo`, there's a mistake in the API documentation.
* Updated the `printTable` function to print a space after the delimiting commas.
* Moved the `printTable` function for better readability and reusability.
References
----------
[CLI Commands …

[TRAFFIC-9068] - Add `confluent network update` command

---

internal/kafka/command_acl_create_onprem.go
internal/kafka/command_acl_delete_onprem.go
internal/kafka/command_acl_list_onprem.go
internal/kafka/command_broker_delete.go
internal/kafka/command_broker_describe.go
internal/kafka/command_broker_gettasks.go
internal/kafka/command_broker_list.go
internal/kafka/command_broker_update.go
internal/kafka/command_link_configuration_list_onprem.go
internal/kafka/command_link_configuration_update_onprem.go
internal/kafka/command_link_create_onprem.go
internal/kafka/command_link_delete_onprem.go
internal/kafka/command_link_describe_onprem.go
internal/kafka/command_link_list_onprem.go
internal/kafka/command_partition_describe.go
internal/kafka/command_partition_list.go
internal/kafka/command_partition_reassignment_list.go
internal/kafka/command_replica_list.go
internal/kafka/command_topic_create_onprem.go
internal/kafka/command_topic_delete_onprem.go
internal/kafka/command_topic_describe_onprem.go
internal/kafka/command_topic_list_onprem.go
internal/kafka/command_topic_onprem.go
internal/kafka/command_topic_update_onprem.go
internal/kafka/kafka_rest_onprem.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
I noticed that `getClusterIdForRestRequests` and `initKafkaRest` are always called together for (non-local) commands.
So I rolled the logic of `getClusterIdForRestRequests` into `initKafkaRest` to save an extra function call across all of the onprem commands.
This is also a small step towards unifying the cloud and onprem command implementations.
References
----------
Test & Review
-------------

Simplify KafkaREST setup for on-prem commands

---

internal/login/command.go
pkg/cmd/prerunner.go
pkg/cmd/prerunner_test.go
pkg/cmd/token_validator.go
pkg/errors/catcher.go
pkg/errors/error_message.go
pkg/errors/strings.go

Release Notes
-------------
Bug Fixes
- After session has timed out, correctly refresh credentials with environment variables or credentials saved with `confluent login --save`
Checklist
---------
* yes: ok
What
----
When the user's refresh token expires (5 minutes), check the user's environment variables and keychain to refresh the token. This is a sub-optimal solution, since we should try refreshing the auth token with the auth refresh token first, but that will require a major rewrite- I'll open a separate ticket for that.
Minor: Also remove reference to deprecated netrc file in error suggestion
Test & Review
-------------
Manually tested all paths.

Check environment variables and keychain during token refresh

---

internal/iam/command_rbac_role_binding_list.go
pkg/config/auth_config.go

Release Notes
-------------
Bug Fixes
- Resolve a panic in `confluent iam rbac role-binding list`
Checklist
---------
* yes: ok
What
----
Now using a panic-safe getter to retrieve the `User` field of an `AuthConfig` struct.
References
----------
https://confluentinc.atlassian.net/browse/CLI-2701

[CLI-2701] fixing confluent iam rbac role-binding list panic

---

internal/network/command.go
internal/network/command_list.go
internal/network/command_peering.go
internal/network/command_peering_list.go
pkg/ccloudv2/networking.go
test/fixtures/output/network/help.golden
test/fixtures/output/network/list-help.golden
test/fixtures/output/network/peering/help.golden
test/fixtures/output/network/peering/list-help.golden
test/fixtures/output/network/peering/list-json.golden
test/fixtures/output/network/peering/list.golden
test/network_test.go
test/test-server/ccloudv2_router.go
test/test-server/networking_handlers.go

What
----
* Added `confluent network peering` to manage peering connections and `confluent network peering list` to display peering connections
References
----------
Test & Review
-------------

[TRAFFIC-9317] - Add `confluent network peering list` command

---

internal/network/command.go
internal/network/command_peering.go
internal/network/command_peering_describe.go
internal/network/command_peering_list.go
pkg/ccloudv2/networking.go
test/fixtures/output/network/peering/describe-autocomplete.golden
test/fixtures/output/network/peering/describe-aws-json.golden
test/fixtures/output/network/peering/describe-aws.golden
test/fixtures/output/network/peering/describe-azure.golden
test/fixtures/output/network/peering/describe-gcp.golden
test/fixtures/output/network/peering/describe-help.golden
test/fixtures/output/network/peering/describe-invalid.golden
test/fixtures/output/network/peering/describe-missing-id.golden
test/fixtures/output/network/peering/help.golden
test/fixtures/output/network/peering/list-json.golden
test/fixtures/output/network/peering/list.golden
test/network_test.go
test/test-server/ccloudv2_router.go
test/test-server/networking_handlers.go

What
----
* Added string constants `CloudAws`, `CloudGcp`, and `CloudAzure` to the `network` package as discussed in https://github.com/confluentinc/cli/pull/2227#discussion_r1310548820
* Updated output for `confluent network peering list`. I discussed with @kabraham13 regarding the `list` output that we could display `aws.account`, `gcp.project`, `azure.tenant` in the `Cloud Account` column, and `aws.vpc`, `gcp.vpc_network`, `azure.vnet` in the `Virtual Network` column. 
* Added `confluent network peering describe` to describe a peering connection
* Added …

[TRAFFIC-9319] - Add `confluent network peering describe` command

---

internal/network/command_peering.go
internal/network/command_peering_delete.go
internal/network/command_peering_describe.go
internal/network/command_peering_list.go
internal/network/command_peering_update.go
pkg/ccloudv2/networking.go
pkg/resource/resource.go
test/fixtures/output/network/help.golden
test/fixtures/output/network/peering/delete-help.golden
test/fixtures/output/network/peering/delete-multiple-fail.golden
test/fixtures/output/network/peering/delete-multiple-refuse.golden
test/fixtures/output/network/peering/delete-multiple-success.golden
test/fixtures/output/network/peering/delete-peering-not-exist.golden
test/fixtures/output/network/peering/delete-prompt.golden
test/fixtures/output/network/peering/delete.golden
test/fixtures/output/network/peering/describe-help.golden
test/fixtures/output/network/peering/describe-missing-id.golden
test/fixtures/output/network/peering/help.golden
test/fixtures/output/network/peering/list-help.golden
test/fixtures/output/network/peering/update-help.golden
test/fixtures/output/network/peering/update-missing-args.golden
test/fixtures/output/network/peering/update-missing-flags.golden
test/fixtures/output/network/peering/update-peering-not-exist.golden
test/fixtures/output/network/peering/update.golden
test/network_test.go
test/test-server/networking_handlers.go

What
----
* Add `confluent network peering update` to update the display name of a peering connection.
* Add `confluent network peering delete` to delete a peering connection.
References
----------
Test & Review
------------- …

[TRAFFIC-9320] [TRAFFIC-9321] - Add `confluent network peering update|delete` command

---

pkg/resource/resource.go
test/fixtures/output/kafka/link/delete-link-no-prefix.golden
test/kafka_test.go
test/test-server/kafka_rest_router.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Resolve an issue in `confluent kafka link delete` preventing users from deleting certain cluster links
Checklist
---------
* yes: ok
What
----
Cluster links do not have a set prefix, so `ClusterLinkPrefix` causes the prefix validation to fail when deleting cluster links unless the link name happens to starts with `link-`.
This PR removes this variable from the resource/prefix maps, so that prefix validation will do nothing (as intended for resources with no prefix) when deleting cluster links.
References
----------
Test & Review
-------------
Added a new integration test case with a link that doesn't start with this …

Remove Link prefix validation

---

debian/Makefile
debian/control
debian/patches/standard_build_layout.patch

Checklist
---------
* yes: ok
What
----
As per @rahejaprince's suggestion, we should try setting `Architecture: all` to enable linux/arm64 support for CP.
Test & Review
-------------
Unclear how we can test this, other than include this change in the nightly release. Any ideas @rahejaprince?

Try adding linux/arm64 support for CP

---

internal/kafka/command_topic_produce.go
internal/kafka/command_topic_produce_onprem.go
pkg/serdes/integer_deserialization_provider.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix an issue causing `confluent kafka topic consume` to deserialize integers to incorrect values when using `--key-format integer` or `value-format integer`
- Resolve a panic that could occur in `confluent kafka topic consume` when using `--key-format integer` and `--print-key`
- `--parse-key` must now be specified when using `confluent kafka topic produce --key-format`
Checklist
---------
* yes: ok
What
----
Integers were being serialized with Little Endian but deserialized with Big Endian, resulting in wrong values.
While investigating I also discovered that you can end up with a panic if you consume any messages without …

Resolve integer deserialization issue in `topic consume`

---

pkg/ccloudv2/iam.go
pkg/ccloudv2/utils.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug in `confluent iam user invitation list` where only the first 100 results were listed
Checklist
---------
* yes: ok
What
----
Backend api has a off-by-1 error and page size 100 doesn't work. temply use 99 for all calls to minimize the change. expect a backend fix next week so we can revert this change.
References
----------
Test & Review
-------------
tested with 110 invites and page size 99 returns all results.

Temporarily use page size 99 for v2 api list calls

---

internal/local/command_kafka_topic_produce.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug causing panic when running `confluent local kafka topic produce <topic> --parse-key`
Checklist
---------
* yes: ok
What
----
looks like earlier value schema serializer introduced a bug here. key was missing serializer. local kafka doesn't support sr yet so using the same `string` serializer for both key and value.
References
----------
Test & Review
-------------

[confluent-local-2] fix local kafka produce with key panic

---

internal/network/command.go
internal/network/command_private_link.go
internal/network/command_private_link_access.go
internal/network/command_private_link_access_describe.go
internal/network/command_private_link_access_list.go
internal/network/command_private_link_access_test.go
pkg/ccloudv2/networking.go
test/fixtures/output/network/help.golden
test/fixtures/output/network/private-link/access/describe-autocomplete.golden
test/fixtures/output/network/private-link/access/describe-aws-json.golden
test/fixtures/output/network/private-link/access/describe-aws.golden
test/fixtures/output/network/private-link/access/describe-azure.golden
test/fixtures/output/network/private-link/access/describe-gcp.golden
test/fixtures/output/network/private-link/access/describe-help.golden
test/fixtures/output/network/private-link/access/describe-invalid.golden
test/fixtures/output/network/private-link/access/describe-missing-id.golden
test/fixtures/output/network/private-link/access/help.golden
test/fixtures/output/network/private-link/access/list-help.golden
test/fixtures/output/network/private-link/access/list-json.golden
test/fixtures/output/network/private-link/access/list.golden
test/fixtures/output/network/private-link/help.golden
test/network_test.go
test/test-server/ccloudv2_router.go
test/test-server/networking_handlers.go

What
----
* Add `confluent network private-link` and an alias "pl"
* Add `confluent network private-link access`
* Add `confluent network private-link access list`
* Add `confluent network private-link access describe <id>`
References
----------
Test & Review
-------------
Performed manual …

[TRAFFIC-9330][TRAFFIC-9331] - Add `confluent network private-link access list|describe` commands

---

internal/network/command.go
internal/network/command_peering.go
internal/network/command_peering_create.go
internal/network/command_peering_delete.go
internal/network/command_peering_describe.go
internal/network/command_peering_list.go
internal/network/command_peering_update.go
internal/network/command_private_link_access.go
internal/network/command_private_link_access_describe.go
internal/network/command_private_link_access_list.go
internal/network/command_transit_gateway_attachment.go
internal/network/command_transit_gateway_attachment_create.go
internal/network/command_transit_gateway_attachment_delete.go
internal/network/command_transit_gateway_attachment_describe.go
internal/network/command_transit_gateway_attachment_list.go
internal/network/command_transit_gateway_attachment_update.go
test/fixtures/output/network/delete-autocomplete.golden
test/fixtures/output/network/peering/delete-autocomplete.golden
test/fixtures/output/network/peering/update-autocomplete.golden
test/fixtures/output/network/transit-gateway-attachment/delete-autocomplete.golden
test/fixtures/output/network/transit-gateway-attachment/update-autocomplete.golden
test/fixtures/output/network/update-autocomplete.golden
test/network_test.go

What
----
Note that this is merging into the feature branch https://github.com/confluentinc/cli/tree/traffic-8850-network-cli
* Update `peering`, `transit-gateway-attachment` subcommands to use the `command` struct from the parent command, as discussed in https://github.com/confluentinc/cli/pull/2251#discussion_r1322058537.
* Move variable declaration closer to where it's used, as discussed in https://github.com/confluentinc/cli/pull/2251#discussion_r1322060160.
* Add autocomplete test cases for `update` and `delete`, this is to ensure that these commands are using the correct `ValidXXXArgs` functions.
References
----------
Test & Review
-------------
```
make build
make lint
make test
```

Refactor network commands

---

internal/network/command_private_link_access.go
internal/network/command_private_link_access_delete.go
internal/network/command_private_link_access_update.go
pkg/ccloudv2/networking.go
pkg/resource/resource.go
test/fixtures/output/network/private-link/access/delete-autocomplete.golden
test/fixtures/output/network/private-link/access/delete-help.golden
test/fixtures/output/network/private-link/access/delete-multiple-fail.golden
test/fixtures/output/network/private-link/access/delete-multiple-refuse.golden
test/fixtures/output/network/private-link/access/delete-multiple-success.golden
test/fixtures/output/network/private-link/access/delete-pla-not-exist.golden
test/fixtures/output/network/private-link/access/delete-prompt.golden
test/fixtures/output/network/private-link/access/delete.golden
test/fixtures/output/network/private-link/access/help.golden
test/fixtures/output/network/private-link/access/update-autocomplete.golden
test/fixtures/output/network/private-link/access/update-help.golden
test/fixtures/output/network/private-link/access/update-missing-args.golden
test/fixtures/output/network/private-link/access/update-missing-flags.golden
test/fixtures/output/network/private-link/access/update-pla-not-exist.golden
test/fixtures/output/network/private-link/access/update.golden
test/network_test.go
test/test-server/networking_handlers.go

What
----
* Add `confluent network private-link access update` 
* Add `confluent network private-link access delete`
References
----------
Test & Review
-------------

[TRAFFIC-9332][TRAFFIC-9333] - Add confluent network private-link access update|delete commands

---

go.mod
go.sum
internal/kafka/command_mirror.go
internal/kafka/command_mirror_describe.go
internal/kafka/command_mirror_list.go
test/fixtures/output/kafka/mirror/describe-autocomplete.golden
test/fixtures/output/kafka/mirror/list-mirror-json.golden
test/fixtures/output/kafka/mirror/list-mirror-yaml.golden
test/fixtures/output/kafka/mirror/list-mirror.golden
test/test-server/kafka_rest_router.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Switch `mirror describe | list` back to using the proper SDK, which has been updated to include the previously missing `LINK_PAUSED`, `LINK_FAILED`, and `SOURCE_UNAVAILABLE` statuses.
References
----------
Test & Review
-------------
Updated the list test to include the three missing statuses.

Switch remaining `confluent kafka mirror` commands to using the cloud version of the kafkarest sdk

---

internal/network/command_private_link_access.go
internal/network/command_private_link_access_create.go
pkg/ccloudv2/networking.go
test/fixtures/output/network/private-link/access/create-autocomplete.golden
test/fixtures/output/network/private-link/access/create-aws.golden
test/fixtures/output/network/private-link/access/create-azure.golden
test/fixtures/output/network/private-link/access/create-duplicate.golden
test/fixtures/output/network/private-link/access/create-gcp.golden
test/fixtures/output/network/private-link/access/create-help.golden
test/fixtures/output/network/private-link/access/create-missing-flags.golden
test/fixtures/output/network/private-link/access/create-wrong-network-cloud.golden
test/fixtures/output/network/private-link/access/help.golden
test/network_test.go
test/test-server/networking_handlers.go

What
----
* Add `confluent network private-link access create` 
References
----------
Test & Review
-------------
* create aws pl access
* create gcp psc access
* create azure pl access

[TRAFFIC-9334] - Add `confluent network private-link access create` command

---

internal/kafka/command_topic_consume.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a panic that occurs when using `confluent kafka topic consume --key-format` with a schema based key format
Checklist
---------
* yes: ok
What
----
The SR client was previously only initialized if the user provided a schema based value format. This PR initializes the SR client if they provide a schema based value format or key format.
References
----------
Test & Review
-------------
Manual testing:
```
confluent kafka topic produce avro-test --key-format avro --key-schema ~/schemas/schema-avro-test-value-v1.avsc --parse-key --value-format string --delimiter ";"
Successfully registered schema with ID "100003".
Starting …
```

[CLI-2797] Fix panic in `kafka topic consume`

---

internal/context/command_update.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug when running CLI after running `confluent context update --name`
Checklist
---------
* yes: ok
What
----
context tokens are encrypted using ctx name as part of additional info. when it's renamed, tokens should be decrypted first and then be encrypted again (this is done in 'save'), or a inconsistent ctx name will lead to decrypting failures.
References
----------
Test & Review
-------------
```
mhe@C02DV0KVMD6T cli % confluent context update login-mhe@confluent.io-https://confluent.cloud --name xtc
decrypting auth token of context: login-mhe@confluent.io-https://confluent.cloud
decrypting refresh auth token of …
```

Fix cipher: message authentication failed after renaming context

---

internal/connect/command_custom_plugin_update.go
internal/connect/utils.go

Release Notes
-------------
Checklist
---------
yes: ok 
What
----
Depending on the internet connection of the user some file upload to s3 for custom connector plugins would time out. Increased the timeout to 20 minutes to support that.
Test & Review
-------------
Tested manually using the binary

Increased timeout for sling client for s3 upload

---

internal/kafka/command_link_describe.go
test/fixtures/output/kafka/link/describe-help.golden
test/fixtures/output/kafka/link/describe-json.golden
test/kafka_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Add the missing `--output` flag to `confluent kafka link describe` and remove the unused `--force` flag
Checklist
---------
* yes: ok
What
----
I think this qualifies more as a bug fix than a breaking change, because the `--force` flag was never intended to be available for this command. Since `--output` is also missing, this was just a copy paste error.
References
----------
Test & Review
-------------
Added a new integration test for the output flag.

Remove `--force` and add `--output` to `confluent kafka link describe`

---

go.mod
go.sum
internal/network/command_private_link.go
internal/network/command_private_link_attachment.go
internal/network/command_private_link_attachment_describe.go
internal/network/command_private_link_attachment_list.go
pkg/ccloudv2/client.go
pkg/ccloudv2/networking.go
pkg/ccloudv2/networking_privatelink.go
test/fixtures/output/network/private-link/attachment/describe-autocomplete.golden
test/fixtures/output/network/private-link/attachment/describe-aws-json.golden
test/fixtures/output/network/private-link/attachment/describe-aws-provisioning.golden
test/fixtures/output/network/private-link/attachment/describe-aws.golden
test/fixtures/output/network/private-link/attachment/describe-help.golden
test/fixtures/output/network/private-link/attachment/describe-invalid.golden
test/fixtures/output/network/private-link/attachment/describe-missing-id.golden
test/fixtures/output/network/private-link/attachment/help.golden
test/fixtures/output/network/private-link/attachment/list-help.golden
test/fixtures/output/network/private-link/attachment/list-json.golden
test/fixtures/output/network/private-link/attachment/list.golden
test/network_test.go
test/test-server/ccloudv2_router.go
test/test-server/networking_handlers.go

What
----
* Add `confluent network private-link attachment`
* Add `confluent network private-link attachment list`
* Add `confluent network private-link attachment describe <id>`
References
----------
Test & Review
------------- …

[TRAFFIC-9351][TRAFFIC-9352]: Add `confluent network private-link attachment list|describe` commands

---

pkg/errors/catcher.go
pkg/errors/catcher_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
We use 402 for `quota exceeded` errors, but 402 is the standard code for `Payment Required`. This leads to a misleading error message when users reach limits.
References
----------
Test & Review
-------------
Tested manually by hitting the api key per user limit.

[CLI-2802] Remove `402 Payment Required` from quota exceeded errors

---

internal/iam/command_groupmapping_delete.go
internal/iam/command_groupmapping_update.go
test/fixtures/output/iam/group-mapping/delete-help.golden
test/fixtures/output/iam/group-mapping/update-help.golden

Checklist
---------
* yes: ok
What
----
Update `iam group-mapping` examples to use the "group-" prefix instead of the "pool-" prefix.
References
----------
https://confluentinc.atlassian.net/browse/CLI-2679

[CLI-2679] Update group mapping prefix

---

internal/local/command_service.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Verify Java version at the beginning when running `confluent local services start`
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
https://confluentinc.atlassian.net/browse/CLI-2675
Check java version is valid before starting the services, so user doesn't need to wait until service is up.
References
----------
Test & Review
-------------

CLI-2675 check java version before starting confluent local services

---

pkg/auth/auth.go
test/login_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
If users log in with a Confluent gov url with a trailing `/`, the CLI will fail to encrypt the auth refresh token. To determine if a token is an unencrypted Confluent gov refresh token, the code checks the config platform name against a list of hostnames without the trailing `/`. Because of this, the code fails to encrypt the token.
Since the unencrypted refresh token generally contains invalid base64 characters, running most commands after login will yield base64 data errors.
This PR trims `/` from the end of the platform name before it's added to the config.
References …

Remove trailing slashes from the config platform name

---

internal/iam/command_rbac_role_binding.go
internal/iam/command_rbac_role_binding_create.go
internal/iam/command_rbac_role_binding_delete.go

Checklist
---------
* yes: ok
What
----
This feature flag gets evaluated before the command is run (while flags are being listed) so it needs user information. We need to call `ParseFlagsIntoConfig` here.
Test & Review
-------------
Tested manually in prod

Fix Flink feature flag

---

pkg/flink/internal/store/store.go
pkg/flink/internal/store/store_test.go
pkg/flink/internal/store/user_properties.go
pkg/flink/internal/store/user_properties_test.go

Checklist
---------
* yes: ok
What
----
We filtered all properties that didn't contain `sql.` prefix. This is incorrect, we should only filter out those that do have the `client.` prefix

fix: make sure to send all non-local properties instead of just the sql ones

---

internal/kafka/command_topic_consume.go
internal/kafka/command_topic_produce.go
internal/kafka/command_topic_produce_onprem.go
internal/kafka/utils.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix an issue in `confluent kafka topic produce` that could prevent users from using schema formats for both `--key-format` and `--value-format` at the same time
Checklist
---------
* yes: ok
What
----
Discovered this bug while investigating the delimiter issue.
If the user provides filepaths instead of IDs for both `--key-format` and `--value-format`, the CLI attempts to register both under the same subject `topic-value`. This causes the second registration to fail unless the same schema is used for both flags.
This PR changes the naming so that schemas for key-format are registered as `topic-key` instead of `topic-value`. …

Fix bug preventing users from registering two schemas in `confluent kafka topic produce`

---

internal/iam/command_rbac_role_binding.go

Checklist
---------
* yes: ok
What
----
We want to use camel case for resource types, but when actually calling MDS v2 API, the CRN is not in camel case, ex. `crn://confluent.cloud/organization=6157fa3e-9ae3-4470-a5ee-b38f911bf780/service-account=sa-stgcc1moxj6`. This PR adds support for ServiceAccount and ComputePool, which are translated to service-account and compute-pool respectively in the CRN. 
References
----------
Test & Review
-------------
Tested in stag:
```
confluent iam rbac role-binding create --principal User:u-67w7nj --role WorkloadIdentityAssigner --resource "ServiceAccount:sa-stgcc1moxj6"
+-----------------+--------------------------+
| Principal       | User:u-67w7nj            |
| Email           | …
```

[CIAM-3594] Use Camel case for resource types

---

pkg/ccloudv2/flink_gateway.go

Release Notes
-------------
n/a
Checklist
---------
* yes: ok
What
----
Fixes a recently-introduced bug where we don't use the special flink client that follows redirects.  This was broken recently by https://github.com/confluentinc/cli/pull/2231
References
----------
https://confluentinc.atlassian.net/jira/software/c/projects/FLINKCC/issues/FLINKCC-363
Test & Review
-------------

[FLINK363] Remove erroneous override of special flink http client

---

internal/flink/command_compute_pool_use.go
pkg/errors/error_message.go
test/fixtures/output/flink/compute-pool/use-fail.golden
test/fixtures/output/flink/compute-pool/use-help.golden
test/flink_test.go

Checklist
---------
* yes: ok
What
----
Since `compute-pool use` will not switch environments for you, we ended up receiving some bug reports of people being confused why their use command didn't go through. By removing the flag we force users to manually switch, avoiding this confusion.

fix: remove environment flag for compute pool use command

---

internal/flink/command_region_list.go
test/fixtures/output/flink/region/list-cloud.golden
test/fixtures/output/flink/region/list-json.golden
test/fixtures/output/flink/region/list.golden

Checklist
---------
* yes: ok
What
----
Fixes the region list command which did not output the proper ID. As a result people got error messages in subsequent commands, because they were using the incorrect region ID.

fix: display proper ID for flink region list command

---

pkg/flink/internal/controller/basic_output_controller.go
pkg/flink/internal/results/materialized_results_test.go
pkg/flink/internal/results/result_formatter.go
pkg/flink/internal/results/result_formatter_test.go
pkg/flink/internal/utils/output.go
pkg/flink/types/materialized_results.go

Checklist
---------
* yes: ok
What
----
We did not account for multi line values in the basic table, which led to us truncating those values too early. This should fix this, by only taking too longest line into consideration, when calculating the cell width.

fix: truncate multi-line cells in the basic table properly

---

internal/network/command.go
internal/network/command_private_link_attachment.go
internal/network/command_private_link_attachment_connection.go
internal/network/command_private_link_attachment_connection_describe.go
internal/network/command_private_link_attachment_connection_list.go
pkg/ccloudv2/networking_privatelink.go
test/fixtures/output/network/private-link/attachment/connection/describe-aws-json.golden
test/fixtures/output/network/private-link/attachment/connection/describe-aws-provisioning.golden
test/fixtures/output/network/private-link/attachment/connection/describe-aws.golden
test/fixtures/output/network/private-link/attachment/connection/describe-help.golden
test/fixtures/output/network/private-link/attachment/connection/describe-invalid.golden
test/fixtures/output/network/private-link/attachment/connection/describe-missing-id.golden
test/fixtures/output/network/private-link/attachment/connection/help.golden
test/fixtures/output/network/private-link/attachment/connection/list-autocomplete.golden
test/fixtures/output/network/private-link/attachment/connection/list-help.golden
test/fixtures/output/network/private-link/attachment/connection/list-invalid.golden
test/fixtures/output/network/private-link/attachment/connection/list-json.golden
test/fixtures/output/network/private-link/attachment/connection/list-missing-args.golden
test/fixtures/output/network/private-link/attachment/connection/list-missing-flags.golden
test/fixtures/output/network/private-link/attachment/connection/list.golden
test/fixtures/output/network/private-link/attachment/help.golden
test/network_test.go
test/test-server/ccloudv2_router.go
test/test-server/networking_handlers.go

What
----
* Add `confluent network private-link attachment connection`
* Add `confluent network private-link attachment connection list`
* Add `confluent network private-link attachment connection describe`
References
----------
Test & Review
-------------
Open …

[TRAFFIC-9357][TRAFFIC-9358]: Add `confluent network private-link attachment connection list|describe` commands

---

internal/flink/command_statement_create.go
test/fixtures/output/flink/statement/create-help.golden
test/fixtures/output/flink/statement/create-no-name-yaml.golden
test/fixtures/output/flink/statement/create-wait.golden
test/flink_test.go

Checklist
---------
* yes: ok
What
----
Add `--wait` flag to `confluent flink statement create` that blocks until the statement status is no longer "PENDING"
```
% confluent flink statement create --compute-pool lfcp-9w8jwy --sql "SELECT CURRENT_TIMESTAMP;" --wait
[WARN] No service account provided. To ensure that your statements run continuously, use a service account instead of your user identity with `confluent iam service-account use` or `--service-account`. Otherwise, statements will stop running after 4 hours.
+---------------+--------------------------------------+
| Creation Date | 2023-09-27 21:28:18 +0000 UTC        |
| Name          | f08be65a-4800-4ea8-b74d-a467c94e12c3 |
| Statement     | SELECT …
```

Add `flink statement create --wait`

---

internal/flink/command.go
internal/flink/command_compute_pool.go
internal/iam/command_rbac_role_binding.go
internal/iam/command_rbac_role_binding_create.go
test/fixtures/output/iam/rbac/role-binding/create-help.golden
test/fixtures/output/iam/rbac/role-binding/delete-help.golden
test/fixtures/output/iam/rbac/role-binding/delete-missing-role-cloud.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Flink op flag is always enabled in prod, we should remove it
References
----------
Test & Review
-------------

removed op flag that is always enabled by default

---

pkg/flink/internal/store/store.go

Checklist
---------
* yes: ok
What
----
It seems like the Result schema is returned quite a bit earlier than the statement status is changed to RUNNING/COMPLETED. This hack makes use of that and just manually sets the status to RUNNING (for select statements) or COMPLETED (for all other statements) and returns early from the WaitForPendingStatement loop.
This improves the latency quite a bit (about 4 seconds for SELECT 1 on prod).
References
----------
Test & Review
-------------

feat: improve latency by not waiting for RUNNING/COMPLETED status

---

Makefile
debian/patches/standard_build_layout.patch

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
The integration tests take longer to run on the semaphore darwin machine. If they time out but the Linux tests don't, then semaphore reports `none tests failed`, which is confusing.
The default `go test` timeout is `10m`. This PR changes it to `0`, which is no time out. There shouldn't be any danger of semaphore running indefinitely, since we still have the 1 hour overall execution time limit.
References
----------
Test & Review
-------------

Remove `go test` time limit for integration tests

---

internal/kafka/command_cluster_create.go
pkg/errors/catcher.go
pkg/errors/catcher_test.go
test/test-server/cli_handler.go
test/test-server/cmk_handlers.go
test/test-server/connect_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
Remove call to ccloud-sdk-go-v1-public. This validation is already performed by the backend, so the extra API call is unnecessary.
Test & Review
-------------
Manually tested, make sure integration tests still pass

Remove extra API call during `kafka cluster create`

---

go.mod
go.sum
pkg/cmd/token_validator.go

Checklist
---------
* yes: ok
What
----
https://github.com/go-jose/go-jose is meant to replace v2, which is no longer maintained.
References
----------
https://confluentinc.atlassian.net/browse/CLI-2819
Test & Review
-------------

[CLI-2819] Update `go-jose` package

---

pkg/flink/app/application.go
pkg/flink/app/application_test.go
pkg/flink/internal/controller/statement_controller.go
pkg/flink/internal/results/result_fetcher.go
pkg/flink/internal/utils/.snapshots/TestCustomPanicRecovery
pkg/flink/internal/utils/.snapshots/TestCustomPanicRecoveryIsSafeWhenCustomRecoveryFuncPanics
pkg/flink/internal/utils/.snapshots/TestDefaultPanicRecovery
pkg/flink/internal/utils/panic.go
pkg/flink/internal/utils/panic_test.go

Checklist
---------
* yes: ok
What
----
Adds a panic recovery wrapper that can be used when spawning goroutines. This wrapper ensures we recover from panics inside goroutines, so they don't crash our main routine.

feat: add panic recovery wrapper for goroutines

---

internal/kafka/command_topic_consume.go
internal/kafka/confluent_kafka.go
internal/kafka/confluent_kafka_test.go
test/fixtures/output/kafka/topic/consume-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- Add `--print-offset` to `confluent kafka topic consume` for printing partition number and offset of each message
Bug Fixes
- PLACEHOLDER
Checklist
---------
* yes: ok
What
----
```
mhe@C02DV0KVMD6T cli % confluent kafka topic consume -b tester --print-offset --timestamp
Starting Kafka Consumer. Use Ctrl-C to exit.
Timestamp:1696896989560 Partition:3 Offset:0	6
Timestamp:1696896990093 Partition:3 Offset:1	7
```
References
----------
Test & Review
-------------

[CLI-2825] Add `print-offset` in confluent kafka topic consume

---

internal/byok/command.go
internal/byok/command_create.go
internal/byok/command_describe.go
internal/byok/command_list.go
test/fixtures/output/byok/create_1.golden
test/fixtures/output/byok/create_2.golden
test/fixtures/output/byok/describe-aws.golden
test/fixtures/output/byok/describe-azure.golden

Checklist
---------
* yes: ok
What
----
For `confluent byok [create|describe|list]` commands, instead of `[a b c]`, print `a, b, c`. The same problem exists for at least 4 other commands, will create a few more follow-up PRs.
Test & Review
-------------
Update integration tests

Use comma delimited string for human BYOK role output

---

pkg/ccloudv2/flink_gateway.go

Checklist
---------
What
----
PR #2231 introduced client redirection, which also sets the Authorization header when redirects happen. The problem is that the token used for the header, is actually the local variable that's passed to the GatewayClient constructor. This will lead to the token never being refreshed and thus to 401s after the initial token has expired. 
Instead we need to either use the token inside the GW client struct `client.AuthToken`, which gets refreshed by the flink shell or copy over the authorization header from the previous request.

[FCP-1283] fix: bug where expired token was used on redirect

---

internal/kafka/command_topic_consume_onprem.go
internal/kafka/command_topic_produce_onprem.go
test/fixtures/output/kafka/topic/produce-help-onprem.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- In on-premises `confluent kafka topic produce`, the `--ca-location` flag is no longer required
Checklist
---------
What
----
Since plaintext mode is supported, `--ca-location` should not be required.
References
----------
Closes #2364
Test & Review
-------------

Do not require `--ca-location` in `kafka topic produce`

---

pkg/errors/error_message.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The CLI can put a user in a state where auto-login incorrectly and automatically tries to log them in:
```
% confluent login --save --url devel.cpdev.cloud --organization-id e9eb4f2c-ef73-475c-ba7f-6b37a4ff00e5
Assuming https protocol.
Error: incorrect email, password, or organization ID
Suggestions:
To log into an organization other than the default organization, use the `--organization-id` flag.
To avoid session timeouts, non-SSO users can save their credentials with `confluent login --save`.
```
The fix here is to use `--prompt`, so this should be a suggestion. Note that this …

Suggest using `--prompt` on invalid login

---

internal/asyncapi/command_export.go
internal/asyncapi/command_import.go
pkg/cmd/flags.go
pkg/flink/components/table_view.go
pkg/serdes/avro_serialization_provider.go
pkg/serdes/double_deserialization_provider.go
pkg/serdes/double_serialization_provider.go
pkg/serdes/integer_deserialization_provider.go
pkg/serdes/integer_serialization_provider.go
pkg/serdes/json_serialization_provider.go
pkg/serdes/protobuf_serialization_provider.go
pkg/serdes/serdes.go
pkg/serdes/serdes_test.go
test/fixtures/output/asyncapi/export-help.golden
test/fixtures/output/kafka/topic/consume-help-onprem.golden
test/fixtures/output/kafka/topic/consume-help.golden
test/fixtures/output/kafka/topic/produce-help-onprem.golden
test/fixtures/output/kafka/topic/produce-help.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- Support `--value-format double` in `confluent kafka topic produce` and `confluent kafka topic consume`
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Added support for integers in #2163. Adding support for doubles.
Test & Review
-------------
Manually tested:
```
% confluent kafka topic produce test-double --value-format double
Starting Kafka Producer. Use Ctrl-C or Ctrl-D to exit.
1.1
3.14159265358979
% confluent kafka topic consume test-double --value-format double --from-beginning 
Starting Kafka Consumer. Use Ctrl-C to exit.
1.100000
3.141593
^CStopping Consumer.
```

Support for `--value-format double`

---

internal/flink/command_statement.go
internal/flink/command_statement_create.go
internal/flink/command_statement_list.go
pkg/ccloudv2/flink_gateway.go
pkg/flink/internal/store/store.go
pkg/flink/test/mock/gateway_client_fake.go
pkg/flink/test/mock/gateway_client_mock.go
pkg/flink/types/statement.go
test/fixtures/output/flink/statement/create-no-name-yaml.golden

Checklist
---------
What
----
* Filter statements by compute pool while autocompleting
* Generate statement names with the same function (previously was generating statement names with different length)

Fix Flink autocomplete and statement name generation bugs

---

internal/flink/command_region_list.go
internal/flink/command_region_use.go
test/fixtures/output/flink/region/list-cloud.golden
test/fixtures/output/flink/region/list-json.golden
test/fixtures/output/flink/region/list.golden
test/fixtures/output/flink/region/use-autocomplete.golden
test/fixtures/output/flink/region/use-help.golden
test/fixtures/output/flink/region/use-missing-cloud.golden
test/fixtures/output/flink/region/use-missing-region.golden
test/fixtures/output/flink/region/use.golden
test/flink_test.go

Checklist
---------
What
----
The ID is only used in the backend and causes confusion in the frontend. Require `--cloud` and `--region` flags instead of concatenated region ID.
Test & Review
-------------

Remove "ID" from `flink region list`

---

.github/CODEOWNERS

Checklist
---------
What
----
According to https://confluent.slack.com/archives/C038ZJ00P/p1698776762773139?thread_ts=1692295006.029139&cid=C038ZJ00P, we will no longer be able to force merge in a week or two from today. Since `flink shell` development has decreased to < 1 PR/week and we are not releasing faster than once per week, we should remove the Flink team from the CODEOWNERS file, so a review is not required from the Flink team for changes to the go.mod file and global edits that happen to touch Flink-related files.

Remove Flink from CODEOWNERS

---

internal/asyncapi/account_details.go
internal/asyncapi/command_export.go
pkg/schema-registry/client.go

Checklist
---------
What
----
We already collect metrics on all Confluent Cloud commands, so we do not need to separately collect metrics for AsyncAPI commands
Test & Review
-------------

Remove double-collected AsyncAPI metrics

---

pkg/config/context_state.go

Release Notes
-------------
Bug Fixes
- Fix panic during HTTP retry
Checklist
---------
What
----
The context state (session) might be `nil`, in which case accessing the auth token on line 55 results in an NPE
References
----------
https://confluentinc.atlassian.net/browse/CLI-2860

[CLI-2860] Fix panic in HTTP retry

---

internal/network/command.go
internal/network/command_network_link.go
internal/network/command_network_link_service.go
internal/network/command_network_link_service_describe.go
internal/network/command_network_link_service_list.go
pkg/ccloudv2/networking.go
test/fixtures/output/network/help.golden
test/fixtures/output/network/network-link/help.golden
test/fixtures/output/network/network-link/service/describe-help.golden
test/fixtures/output/network/network-link/service/describe-invalid.golden
test/fixtures/output/network/network-link/service/describe-json.golden
test/fixtures/output/network/network-link/service/describe-missing-id.golden
test/fixtures/output/network/network-link/service/describe.golden
test/fixtures/output/network/network-link/service/help.golden
test/network_test.go
test/test-server/ccloudv2_router.go
test/test-server/networking_handlers.go

What
----
- Add `confluent network network-link service describe`
- Add `confluent network nl` alias
References
----------
Test & Review
-------------

[TRAFFIC-9338] Add `confluent network network-link service describe` command

---

mk-files/docs.mk

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Fix mistakes from my last PR.
References
----------
Test & Review
-------------
Ran without `DRY_RUN` and created the PRs successfully (both targets)
Edit: We've already merged these PRs so DRY_RUN doesn't fully succeed, but here's the list of commands w/ actual version numbers on a current DRY_RUN with the most recent changes:
```
git clone git@github.com:confluentinc/docs-confluent-cli.git /var/folders/xc/09xynw81209b2w17t9d7r5s40000gp/T/tmp.KcAV6D13/docs-confluent-cli && \
cd /var/folders/xc/09xynw81209b2w17t9d7r5s40000gp/T/tmp.KcAV6D13/docs-confluent-cli && \
git fetch && \
git …
```

Fix `release-docs-main` and `release-docs-staging`

---

internal/schema-registry/command_subject_describe.go
internal/schema-registry/command_subject_list.go
test/fixtures/output/schema-registry/subject/describe-help-onprem.golden
test/fixtures/output/schema-registry/subject/describe-help.golden
test/fixtures/output/schema-registry/subject/list-help-onprem.golden
test/fixtures/output/schema-registry/subject/list-help.golden

Checklist
---------
What
----
The `--deleted` flag does not filter deleted resources, it includes them in the existing list.
Test & Review
-------------

Fix description of `--deleted` in SR commands

---

internal/local/command_kafka.go
internal/local/command_kafka_start.go
pkg/cmd/prerunner.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Resolved the `no such host` error when running `confluent local kafka start`. Confluent Local is now working with the latest Docker Desktop version 4.25.0
Checklist
---------
What
----
Something changed in the way the docker client looks up host. `localhost` the string doesn't work as it failed to map it to `0.0.0.0`. instead, explicitly declare it as `0.0.0.0` will resolve the issue.
References
----------
Test & Review
-------------

fix error where confluent local couldn't work with newer docker desktop versions

---

internal/kafka/confluent_kafka.go
internal/kafka/confluent_kafka_configs.go
pkg/errors/error_message.go
pkg/secret/encryption_other.go
pkg/secret/encryption_windows.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Add debug logs in decryption and ckgo producer/consumer creation. Windows users have been reporting see: Error: failed to create consumer: decryptbytes: procdecryptdata: The parameter is incorrect.
Adding logs in ckgo as well, as this doesn't really look like a dpapi error. Possibilities: sasl authentication?
References
----------
https://github.com/confluentinc/cli/issues/2412
Test & Review
-------------

Add debug logs in decryption and ckgo producer/consumer creation

---

internal/kafka/command_cluster_create.go
pkg/cmd/flags.go
test/fixtures/output/kafka/1.golden
test/fixtures/output/kafka/cluster/cck-network.golden
test/fixtures/output/kafka/cluster/create-help.golden
test/kafka_test.go
test/test-server/cmk_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
- [] Leave this box unchecked if features are not yet available in production
What
----
- Add `--network` option to `confluent kafka cluster create` to specify a network for a cluster. Note that this can only be used when creating a dedicated cluster. 
References
----------
Test & Review
-------------

[TRAFFIC-10037] add --network option to `confluent kafka cluster create` command

---

internal/network/command_network_link_service.go
internal/network/command_network_link_service_delete.go
pkg/ccloudv2/networking.go
pkg/resource/resource.go
test/fixtures/output/network/network-link/service/delete-autocomplete.golden
test/fixtures/output/network/network-link/service/delete-help.golden
test/fixtures/output/network/network-link/service/delete-multiple-fail.golden
test/fixtures/output/network/network-link/service/delete-multiple-refuse.golden
test/fixtures/output/network/network-link/service/delete-multiple-success.golden
test/fixtures/output/network/network-link/service/delete-nls-not-exist.golden
test/fixtures/output/network/network-link/service/delete-prompt.golden
test/fixtures/output/network/network-link/service/delete.golden
test/fixtures/output/network/network-link/service/describe-autocomplete.golden
test/fixtures/output/network/network-link/service/help.golden
test/network_test.go
test/test-server/networking_handlers.go

What
----
- Add `confluent network network-link service delete`
References
----------
Test & Review
-------------

[TRAFFIC-9340] Add `confluent network network-link service delete` command

---

internal/kafka/command_clientconfig_create.go
pkg/ccloudv2/metrics.go
pkg/cmd/authenticated_cli_command.go
pkg/errors/error_message.go
pkg/schema-registry/client.go

Checklist
---------
What
----
Pass the config (which contains both the auth token and the auth refresh token) instead of just the auth token to the Metrics and Schema Registry clients. If the session ends during a HTTP retry we can refresh it.
Test & Review
-------------
```
confluent kafka client-config create java --schema-registry-api-key <REDACTED> --schema-registry-api-secret <REDACTED>
```

Refresh session on HTTP retry: Metrics and Schema Registry clients

---

internal/iam/command_ipfilter_create.go
internal/iam/command_ipfilter_update.go
internal/iam/command_ipgroup_update.go
test/fixtures/output/iam/ip-filter/create-help.golden
test/iam_test.go

Checklist
---------
What
----
When updating an IP filter or IP group in a way which would remove all associated IP groups or CIDR blocks, respectively, it gives a more clear error about what is going wrong.
Resource group flags were given a default value, but couldn't be utilized because it was listed as "required"
References
----------
[Bug bash](https://confluentinc.atlassian.net/wiki/spaces/SECENG/pages/3240723144/IP+Filtering+CLI+Bug+Bash)
[Ticket ](https://confluentinc.atlassian.net/browse/CIAM-3912)
Test & Review
-------------
`make lint`
`make test`
Local testing after `make build`

CIAM-3912: Increase CLI error clarity

---

.goreleaser-linux-amd64.yml
.goreleaser-linux-arm64.yml
.goreleaser.yml
Makefile
debian/patches/standard_build_layout.patch

…for builds (but not archive)
Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Some preparation for adding rpm/deb support. Two things:
- Update the goreleaser version. The current version has an rpm naming bug that's fixed in the newer versions.
- Change the build id suffix from `-homebrew` to `-disableupdates` for the Darwin and Linux builds. The Linux binaries will be used to create the deb/rpm packages, so not just homebrew. Changing the suffix for the Darwin builds is simply for consistency.
I did not change the `archive-homebrew` archive id since that is still only used for Homebrew.
References
----------
Test & Review
-------------
Since this change also changes the prebuilt path for the …

Update goreleaser version and change build names in goreleaser files

---

.goreleaser.yml

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
I meant to bundle this with the previous goreleaser PR but missed it.
goreleaser added `skip_push` to `dockers`, so we should now have full `DRY_RUN` support in goreleaser. I also removed some random trailing whitespace.
References
----------
Test & Review
-------------
Ran `goreleaser check .goreleaser*.yml` and got no errors.

Add dry run to the `dockers` block in goreleaser

---

pkg/secret/encryption_other.go
pkg/secret/encryption_windows.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
cipherText is a binary-formatted []byte. Log the `encrypted` string instead to check if has the correct prefix / if it's truncated...
References
----------
Test & Review
-------------

Log the encrypted string in encryption.go

---

internal/flink/command_compute_pool.go
internal/flink/command_compute_pool_create.go
internal/flink/command_compute_pool_describe.go
internal/flink/command_compute_pool_list.go
internal/flink/command_compute_pool_update.go
test/fixtures/output/flink/compute-pool/create.golden
test/fixtures/output/flink/compute-pool/describe-after-use.golden
test/fixtures/output/flink/compute-pool/describe.golden
test/fixtures/output/flink/compute-pool/list-after-use.golden
test/fixtures/output/flink/compute-pool/list-region.golden
test/fixtures/output/flink/compute-pool/list.golden
test/fixtures/output/flink/compute-pool/update-after-use.golden
test/fixtures/output/flink/compute-pool/update.golden
test/test-server/fcpm_handlers.go

Release Notes
---------
New Features
- [Early Access] Add "Cloud" to the output of the `confluent flink compute-pool` commands
Checklist
---------
What
----
We will be launching Azure pretty soon followed by GCP. The compute pool CLI commands currently do not mention the cloud provider, so we should add it
References
----------
Test & Review
-------------

feat: add cloud provider to output for compute pool commands

---

.semaphore/semaphore.yml

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
This changes the Semaphore pipeline to macOS ARM64 agents instead of AMD64 agents. The ARM64 agents perform better.
References
----------
Test & Review
-------------

Change to macOS ARM64 Semaphore agents

---

internal/network/command.go
internal/network/command_network_link_endpoint.go
internal/network/command_network_link_endpoint_create.go
internal/network/command_network_link_endpoint_delete.go
internal/network/command_network_link_service_delete.go
pkg/ccloudv2/networking.go
pkg/resource/resource.go
test/fixtures/output/network/network-link/endpoint/create-autocomplete.golden
test/fixtures/output/network/network-link/endpoint/create-duplicate.golden
test/fixtures/output/network/network-link/endpoint/create-help.golden
test/fixtures/output/network/network-link/endpoint/create-missing-args.golden
test/fixtures/output/network/network-link/endpoint/create-missing-flags.golden
test/fixtures/output/network/network-link/endpoint/create-no-name.golden
test/fixtures/output/network/network-link/endpoint/create-same-id.golden
test/fixtures/output/network/network-link/endpoint/create.golden
test/fixtures/output/network/network-link/endpoint/delete-autocomplete.golden
test/fixtures/output/network/network-link/endpoint/delete-help.golden
test/fixtures/output/network/network-link/endpoint/delete-multiple-fail.golden
test/fixtures/output/network/network-link/endpoint/delete-multiple-refuse.golden
test/fixtures/output/network/network-link/endpoint/delete-multiple-success.golden
test/fixtures/output/network/network-link/endpoint/delete-nle-not-exist.golden
test/fixtures/output/network/network-link/endpoint/delete-prompt.golden
test/fixtures/output/network/network-link/endpoint/delete.golden
test/fixtures/output/network/network-link/endpoint/help.golden
test/fixtures/output/network/network-link/service/delete-help.golden
test/fixtures/output/network/network-link/service/help.golden
test/network_test.go
test/test-server/networking_handlers.go

What
----
- Add `confluent network network-link endpoint create`
- Add `confluent network network-link endpoint delete`
References
----------
Test & Review
-------------

[TRAFFIC-9346][TRAFFIC-9347] Add confluent network network-link endpoint create/delete

---

internal/network/command_network_link_endpoint.go
internal/network/command_network_link_endpoint_update.go
pkg/ccloudv2/networking.go
test/fixtures/output/network/network-link/endpoint/help.golden
test/fixtures/output/network/network-link/endpoint/update-autocomplete.golden
test/fixtures/output/network/network-link/endpoint/update-help.golden
test/fixtures/output/network/network-link/endpoint/update-missing-args.golden
test/fixtures/output/network/network-link/endpoint/update-missing-flags.golden
test/fixtures/output/network/network-link/endpoint/update-name-description.golden
test/fixtures/output/network/network-link/endpoint/update-nle-not-exist.golden
test/fixtures/output/network/network-link/endpoint/update.golden
test/network_test.go
test/test-server/networking_handlers.go

What
----
- Add confluent network network-link endpoint update
References
----------
Test & Review
-------------

[TRAFFIC-9345] Add confluent network network-link endpoint update

---

internal/schema-registry/command_schema_describe.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix panic in `confluent schema-registry schema describe`
Checklist
---------
What
----
If the references slice is empty, we run into a nil pointer dereference.
References
----------
Test & Review
-------------

[CLI-2932] Resolve panic in `confluent schema-registry schema describe`

---

internal/flink/command_compute_pool.go
internal/flink/command_compute_pool_create.go
internal/flink/command_compute_pool_describe.go
internal/flink/command_compute_pool_list.go
internal/flink/command_compute_pool_update.go
test/fixtures/output/flink/compute-pool/create.golden
test/fixtures/output/flink/compute-pool/describe-after-use.golden
test/fixtures/output/flink/compute-pool/describe.golden
test/fixtures/output/flink/compute-pool/list-after-use.golden
test/fixtures/output/flink/compute-pool/list-region.golden
test/fixtures/output/flink/compute-pool/list.golden
test/fixtures/output/flink/compute-pool/update-after-use.golden
test/fixtures/output/flink/compute-pool/update.golden
test/test-server/fcpm_handlers.go

Release Notes
-------------
New Features
- [Early Access] Add "Environment" field to the output of the `confluent flink compute-pool` commands
Checklist
---------
What
----
Added the environment id to the output of compute pool commands
References
----------
Test & Review
-------------

feat: add environment id to output of compute pool commands

---

.semaphore/semaphore.yml

What
----
After switching to on-prem Semaphore, adding caching actually slows down CI by 4 seconds (and 20 seconds for darwin). This is because it takes too long to upload/download the cache.

Remove caching for CI

---

.gitignore

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
A combination of a few recent PRs ended up commenting out `vendor` in `.gitignore`, which will break the linux release builds (which use vendoring and require a clean git state).
References
----------
Test & Review
-------------

Add vendor back to .gitignore

---

internal/kafka/command_cluster_test.go
pkg/kafka/region.go
test/fixtures/output/kafka/10.golden
test/fixtures/output/kafka/11.golden
test/fixtures/output/kafka/14.golden
test/fixtures/output/kafka/15.golden
test/fixtures/output/kafka/16.golden
test/test-server/ccloud_handlers.go

Checklist
---------
What
----
`is_schedulable` is a legacy flag that is unused, removed `is_schedulable` filter in `confluent kafka region list`. 
Test & Review
-------------

Update filter for `kafka region list`

---

mk-files/release.mk

What
----
If a PR for the specific branch has already been merged, it should be re-opened.
Test & Review
-------------
Tested in `DRY_RUN` mode

Fix auto-packaging PRs in release

---

internal/kafka/command_topic_produce.go

Release Notes
-------------
Bug Fixes
- Fix "no such file or directory" error when running a serialized consumer before producer
Checklist
---------
What
----
Closes #2519. The schema directory should only be deleted once by the producer, when it is closed or errors.
Test & Review
-------------
Manually tested with example from https://developer.confluent.io/tutorials/kafka-console-consumer-producer-avro/confluent.html

Fix consume before produce bug

---

internal/network/command.go
internal/network/command_create.go
internal/network/command_region.go
internal/network/command_region_list.go
pkg/network/region.go
test/fixtures/output/network/create-autocomplete-region-with-cloud.golden
test/fixtures/output/network/create-autocomplete-region.golden
test/fixtures/output/network/help.golden
test/fixtures/output/network/region/help.golden
test/fixtures/output/network/region/list-cloud.golden
test/fixtures/output/network/region/list-help.golden
test/fixtures/output/network/region/list-json.golden
test/fixtures/output/network/region/list.golden
test/network_test.go
test/test-server/ccloud_handlers.go

What
----
- Add `confluent network region list`
- Autocomplete for `confluent network create --region`
References
----------
Test & Review
-------------

[TRAFFIC-10636] Add `confluent network region list`

---

internal/connect/command_custom_plugin_create.go
test/fixtures/output/connect/custom-plugin/create-help.golden

Release Notes
-------------
New Features
- Add `--context` and `--output` to `confluent connect custom-plugin create`
Checklist
---------
What
----
This command was missing two standard flags.
Test & Review
-------------

Add missing flags to `connect custom-plugin create`

---

internal/ksql/command_cluster_create.go
test/fixtures/output/ksql/cluster/create-credential-identity-autocomplete.golden
test/ksql_test.go

Release Notes
-------------
New Features
- Autocomplete `confluent ksql cluster create --credential-identity`
Checklist
---------
What
----
Autocomplete with all users and service accounts
Test & Review
-------------
Added integration test

Autocomplete `--credential-identity` flag

---

internal/secret/command_file_rotate.go
internal/secret/command_master_key_generate.go
test/fixtures/output/secret/file/rotate-help-onprem.golden
test/fixtures/output/secret/master-key/generate-help-onprem.golden

Release Notes
-------------
New Features
- Add `--output` flag to `confluent secret file rotate` and `confluent secret master-key generate`
Checklist
---------
What
----
These commands print tables, but do not offer the `--output` flag.
Test & Review
-------------

[CLI-1992] Add `--output` flag to `secret` commands

---

mk-files/docs.mk

What
----
Improve the CLI release by cloning the CLI repo in `make publish-docs`. This removes the requirement that the CLI must be located at ~/git/go/src/...
Test & Review
-------------
Ran with `DRY_RUN=true`

Clone CLI in publish-docs target

---

go.mod
go.sum
internal/kafka/command_link.go
internal/kafka/command_link_describe_onprem.go
internal/kafka/command_link_task_list.go
internal/kafka/command_link_task_list_onprem.go
test/fixtures/output/kafka/link/help-onprem.golden
test/fixtures/output/kafka/link/list-tasks-onprem-json.golden
test/fixtures/output/kafka/link/list-tasks-onprem-yaml.golden
test/fixtures/output/kafka/link/list-tasks-onprem.golden
test/fixtures/output/kafka/link/task/help-onprem.golden
test/fixtures/output/kafka/link/task/list-help-onprem.golden
test/kafka_test.go

Release Notes
-------------
New Features
- Add `confluent kafka link task list` for listing cluster link task information on-premises
- Add `confluent kafka mirror state-transition-error list` for listing cluster linking mirror state transition errors on-premises
Checklist
---------
What
----
This is a follow-up to https://github.com/confluentinc/cli/pull/2516 to support on prem. Note we apparently don't support the mirror operations on prem - so in this patch I'm just supporting the link resource.
References
----------
Test & Review
-------------

KGLOBAL-4375: Support getting link task info on prem

---

mk-files/release.mk

What
----
Force push to avoid merge conflicts, and fix `grep` when `gh` prints to stderr
Test & Review
-------------
Used for the last release:
* https://github.com/confluentinc/packaging/pull/1154
* https://github.com/confluentinc/muckrake/pull/2239

Fix `update-packaging` and `update-muckrake` targets

---

pkg/serdes/double_deserialization_provider.go
pkg/serdes/integer_deserialization_provider.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix panic in `confluent kafka topic consume --key-format double` when consuming a message with an integer key
Checklist
---------
What
----
Producing a message with an integer key and then deserializing it with the double deserializer produces a panic because `binary.LittleEndian.Uint64` checks that the 8th index of the key byte slice is set, but integer keys have a byte slice of length 4.
Also, producing a message with a double key and then using the integer deserializer produces garbage.
So in both cases, they now return an error if the length is incorrect.
References
----------
Test & Review
-------------
Manual testing

[CLI-2992] Return an error instead of a panic if integer & double keys are switched in `topic produce` and `topic consume`

---

internal/network/command_network_link_service.go
internal/network/command_network_link_service_create.go
test/fixtures/output/network/network-link/service/create-help.golden
test/fixtures/output/network/network-link/service/create-missing-flag.golden
test/fixtures/output/network/network-link/service/create-missing-network.golden
test/fixtures/output/network/network-link/service/create-no-name.golden
test/network_test.go

What
----
- Update display_name for network-link service to optional ([API spec](https://docs.confluent.io/cloud/current/api.html#tag/Network-Link-Services-(networkingv1)/operation/createNetworkingV1NetworkLinkService:~:text=Network%20Link%20Service-,display_name,-string))
References
----------
Test & Review …

Update network-link service display_name optional

---

cmd/lint/main.go
internal/network/command_dns_forwarder.go
internal/network/command_dns_forwarder_create.go
internal/network/command_dns_forwarder_update.go
pkg/ccloudv2/networking_dnsforwarder.go
test/fixtures/output/network/dns/forwarder/create-duplicate.golden
test/fixtures/output/network/dns/forwarder/create-exceed-quota.golden
test/fixtures/output/network/dns/forwarder/create-help.golden
test/fixtures/output/network/dns/forwarder/create-invalid-gateway.golden
test/fixtures/output/network/dns/forwarder/create-missing-flags.golden
test/fixtures/output/network/dns/forwarder/create-no-name.golden
test/fixtures/output/network/dns/forwarder/create.golden
test/fixtures/output/network/dns/forwarder/help.golden
test/fixtures/output/network/dns/forwarder/update-dnsf-not-exist.golden
test/fixtures/output/network/dns/forwarder/update-gateway.golden
test/fixtures/output/network/dns/forwarder/update-help.golden
test/fixtures/output/network/dns/forwarder/update-ips.golden
test/fixtures/output/network/dns/forwarder/update-missing-args.golden
test/fixtures/output/network/dns/forwarder/update-missing-flags.golden
test/fixtures/output/network/dns/forwarder/update.golden
test/network_test.go
test/test-server/networking_handlers.go

What
----
Note that this is merging into the feature branch https://github.com/confluentinc/cli/tree/traffic-10544-dnsforwarder. We will merge commits into main from this feature branch after all of the commands for dns forwarder are implemented.
- Add `confluent network dns forwarder create`
- Add `confluent network dns forwarder update`
References
----------
[DNS Peering for Managed Connectors](https://confluentinc.atlassian.net/wiki/spaces/CIRE/pages/2947056320/1-Pager+--+DNS+peering+for+managed+connectors)
Test & Review
-------------
Added integration tests

[TRAFFIC-10544] Add `confluent network dns forwarder update/create`

---

mk-files/docs.mk

What
----
Rename `[ci skip]` to `[pint skip]` as per docs team recommendation

Rename "ci" to "pint" in docs release make targets

---

go.mod
go.sum
pkg/flink/test/mock/prompt_mock.go

Release Notes
-------------
Checklist
---------
What
----
Upgrade go-prompt's version, which includes a fix to avoid panics caused by multibyte(special characters) when using `confluent flink shell`.
References
----------
Test & Review
-------------

[CLI-3010] chore: upgrade go-prompt to v0.2.26

---

internal/environment/command_create.go
test/environment_test.go
test/fixtures/output/environment/10.golden
test/fixtures/output/environment/create-help.golden
test/test-server/org_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Defaulting the stream governance package to Essentials for new environments causes a potentially breaking change for users who automate environment and SR cluster creation. This breaking change should only be included in v4 deployment and not the current minor release.
References
----------
https://confluentinc.atlassian.net/browse/DGS-10013
https://confluentinc.atlassian.net/wiki/x/twI3xQ

DGS-10013: Do not provide default SG package to new environments

---

internal/local/command_kafka.go

Checklist
---------
What
----
Tests broke because version was not pinned. See: https://github.com/confluentinc/cli/pull/2603
Test & Review
-------------
Confluent Local tests will either pass or fail CI

Pin `confluent local` docker version

---

internal/flink/command.go
internal/flink/command_shell.go
internal/flink/command_statement_create.go
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementPrintsNoWarningWhenUserIdentityIsUsed
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementPrintsWarningWhenNoServiceAccountIsUsed
pkg/flink/internal/controller/statement_controller.go
pkg/flink/internal/controller/statement_controller_test.go
test/fixtures/output/flink/statement/create-service-account-warning.golden

Release Notes
-------------
Checklist
---------
What
----
The 4h time limit for background statements that run with a user identity was removed, so we should also remove the warning in the CLI.
References
----------
Test & Review
-------------

chore: remove service account warning

---

internal/iam/command_rbac_role_binding.go
internal/iam/command_rbac_role_binding_list.go
pkg/resource/resource.go
test/fixtures/output/iam/group-mapping/create.golden
test/fixtures/output/iam/group-mapping/delete-dne.golden
test/fixtures/output/iam/group-mapping/delete-multiple-refuse.golden
test/fixtures/output/iam/group-mapping/delete-multiple-success.golden
test/fixtures/output/iam/group-mapping/delete-prompt.golden
test/fixtures/output/iam/group-mapping/delete.golden
test/fixtures/output/iam/group-mapping/describe.golden
test/fixtures/output/iam/group-mapping/list.golden
test/fixtures/output/iam/group-mapping/update.golden
test/fixtures/output/iam/rbac/role-binding/list-user-orgadmin-cloud.golden
test/iam_test.go
test/test-server/ccloud_handlers.go
test/test-server/iam_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug preventing role bindings with an SSO group mapping principal from displaying in `confluent iam rbac role-binding list`
- Fix a bug causing an incorrect error message to be displayed in `confluent iam rbac role-binding create` and `confluent iam rbac role-binding delete` when the principal is an SSO group mapping
Checklist
---------
What
----
We weren't handling group mappings in `conflulent iam rbac role-binding` commands, so `list` omitted role bindings for group mappings, and `create|delete` treated group mapping IDs as user IDs and subsequently produced an error while trying to display the result, even though the underlying create/delete succeeded.
References
----------
Test & …

[RCCA-17513] Fix group mapping errors in `confluent iam rbac role-binding` commands

---

internal/local/command_service.go
internal/local/command_service_test.go
service.yml

Release Notes
-------------
- PLACEHOLDER
New Features
- Allow `confluent local service` commands work with Java versions above 12
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Closes https://github.com/confluentinc/cli/issues/2612
Test & Review
-------------
Untested as this command is no longer maintained.

Let `confluent local service` commands work with Java versions above 12

---

internal/kafka/command_topic_consume.go
internal/kafka/command_topic_produce.go
pkg/config/context.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix bug preventing Confluent Platform users from using `confluent kafka topic produce` and `confluent kafka topic consume` without logging in
- No longer require `--ca-location` for on-premises `confluent kafka topic produce`
Checklist
---------
What
----
The code currently assumes that users are producing to or consuming from a cloud cluster topic if they aren't logged in.
This PR updates the flow to the following:
1. if Cloud login --> `produceCloud/consumeCloud`
2. if not logged in and bootstrap contains `confluent.cloud` --> `produceCloud/consumeCloud`
3. else --> `produceOnPrem/consumeOnPrem`
References
----------
Test & Review
-------------
Confluent Cloud, logged in (with cluster and …

[CLI-3040] On-prem users can't produce/consume without logging in

---

go.mod
go.sum
pkg/flink/app/application.go
pkg/flink/internal/controller/input_controller.go
pkg/flink/internal/controller/statement_controller.go
pkg/flink/internal/controller/statement_controller_test.go
pkg/flink/internal/reverseisearch/reverse_i_search.go
pkg/flink/internal/utils/input.go

Release Notes
-------------
Bug Fixes
- Fixes an issue where `confluent flink shell` didn't work on Windows
- Fixes an issue where pending statements couldn't be cancelled in `confluent flink shell`
Checklist
---------
What
----
On Windows you will never be able to open /dev/tty, so this check doesn't really make sense here.
To still address the original intent of this check, I've updated go-prompt to return an error instead of panicking when it fails to access /dev/tty
**Note: we still need to officially change go-prompt and release a new tag, so I'm depending on a branch here. Will update once go-prompt was released**
References
----------
Test & Review
-------------

[KFS-1676] remove check for /dev/tty existence

---

pkg/utils/utils.go

Release Notes
-------------
Bug Fixes
- Avoid crash when reading configuration files on Windows
Checklist
---------
What
----
Fix `nil` panic when reading configuration files. Likely only happens on Windows when `os.Stat()` returns `nil`.
References
----------
https://confluentinc.atlassian.net/browse/CLI-3041
Test & Review
-------------

CLI-3041: Fix nil panic when reading configuration files on Windows

---

Makefile
debian/patches/standard_build_layout.patch

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
`CC`, `CXX`, and `CGO_LDFLAGS` also need to be set to the empty string in the `go install` line if `GOOS` and `GOARCH` are set to the empty string.
References
----------
Test & Review
-------------
Manual testing:
- `make`
- `GOOS=linux make cross-build`
- `GOOS=windows make cross-build`
- uninstalled all instances of goreleaser and ran `make`
- uninstalled all instances of goreleaser and ran `GOOS=linux make cross-build`
- uninstalled all instances of goreleaser and ran `GOOS=windows make cross-build`

Fix cross compile issue

---

pkg/color/color.go
pkg/flink/components/shortcuts.go
pkg/flink/components/table_info_bar.go

Release Notes
-------------
Bug Fixes
- Improve text visibility in interactive output of `confluent flink shell`
Checklist
---------
What
----
Switch from dark cyan color name to hex code, since the color is different on Windows and Mac
Windows before:
Windows after:
References
----------
Test & Review
-------------

fix: make colors more visible in interactive output

---

pkg/flink/internal/store/store_test.go
pkg/flink/internal/store/store_utils.go
pkg/flink/internal/store/store_utils_test.go

Release Notes
-------------
New Features
- Support escaped characters for catalogs and databases set with "USE" in `confluent flink shell`
Checklist
---------
What
----
As Specification for SQL Clients: USE statements in `confluent flink shell` now support escaped catalog and database using backticks.
References
----------
Test & Review
-------------

Feat/KFS-1598 KFS-1599 escaped use statement

---

pkg/cmd/authenticated_cli_command.go
test/test-server/fcpm_handlers.go

Checklist
---------
What
----
The `http_endpoint` field should only be used from Flink regions, not Flink endpoints.
References
----------
https://confluentinc.atlassian.net/browse/API-1857
Test & Review
-------------

[API-1857] Stop using `http_endpoint` from compute pool

---

pkg/properties/properties.go
pkg/properties/properties_test.go

Release Notes
-------------
Bug Fixes
- Fix a bug causing `confluent kafka link create` and `confluent kafka link configuration update` to fail when the cluster link configuration "ssl.truststore.certificates" contains an explicit "\n" character
Checklist
---------
What
----
Replace explicit special characters (newline, carriage return and tab) in config value as specified in https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html. More specifically, explicit \n in the value is treated as \\n by current CLI parser while the Java property parser treats it as \n.
References
----------
https://confluentinc.atlassian.net/browse/KGLOBAL-4436
Test & Review
-------------
Tested on real cluster. Added unit test.

KGLOBAL-4436: Replace special characters when parsing the configurations

---

README.md

What
----
`GOARCH` should always be explicitly defined, since the instructions previously assumed the CLI was built from darwin/amd64.
Test & Review
-------------
Tested on darwin/arm64

Update cross-compilation instructions in the README

---

go.mod
go.sum
pkg/ccloudv2/client.go
pkg/ccloudv2/networking_outbound_privatelink.go
pkg/resource/resource.go

What
----
Note that this is merging into the feature branch https://github.com/confluentinc/cli/tree/traffic-10482-outbound-pl. We will merge commits into main from this feature branch after all of the commands for outbound PL are implemented.
For the Outbound PL project, we are introducing two new resources `DNS Record` and `Access Point`
* In this PR, we are setting up the ccloudv2 client for `outbound-private-link`.
* We are using the internal sdk for development as the feature is not released yet.
References
----------
[Outbound PL - Design ](https://confluentinc.atlassian.net/wiki/spaces/CIRE/pages/3171255521/Outbound+PL+-+Design)
Test & Review
-------------
`make build`
`make test`
`make lint`

[TRAFFIC-10482] Set up ccloudv2 client for OutboundPL

---

internal/kafka/command_cluster_configuration_update.go
test/fixtures/output/kafka/cluster/configuration/update-with-commas.golden
test/kafka_test.go
test/test-server/kafka_rest_router.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix an issue in `confluent kafka cluster configuration update` causing some valid inputs to return a duplicate key error
Checklist
---------
What
----
When updating a configuration that accepts a list as a value, cobra will split that input along commas. When we parse this into a map we get what we intend.
But we make `[]AlterConfigBatchRequestDataData` using the length of the input slice instead of the length of the map. This causes empty key/value pairs to be sent to the backend. If there are at least 2 of these, the backend returns an error over duplicate keys.
The fix is simply to use the length of the map and not the slice when creating the request data.
References
----------
Test & …

[RCCA-17800] Fix `confluent kafka cluster configuration update` config length bug

---

internal/api-key/command_use.go

…for an api key
Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a panic in `confluent api-key use`
Checklist
---------
What
----
We get a panic from
```
if key.Spec.Resource.Id != clusterId {
```
Since `Key` is not a pointer, the panic here will happen if either `Spec` or `Resource` are nil. Using `GetResource()` instead of `Resource` will return a default `ObjectReference` struct if either `Spec` or `Resource` is nil, which should resolve this panic.
References
----------
Test & Review
-------------

[CLI-3057] Fix panic in `confluent api-key use`

---

.github/CODEOWNERS

This PR adds API team to CLI repo's CODEOWNERS.

Add confluent/api to CLI's CODEOWNERS

---

pkg/flink/app/application.go
pkg/flink/app/application_test.go
pkg/flink/internal/utils/panic.go

Release Notes
-------------
Bug Fixes
- Fixes bug where `confluent flink shell` would crash if statements were executed too quickly
Checklist
---------
What
----
The panic recovery with limit also stopped the execution when the readEvalPrint function was called too quickly. However, it's only supposed to stop execution when there's an actual panic we recovered from
References
----------
Test & Review
-------------

fix: panic recovery w/ limit should only break on panic

---

.github/CODEOWNERS

Reverts confluentinc/cli#2648
@confluentinc/api has the same member list as @confluentinc/cli now

Revert "Add confluent/api to CLI's CODEOWNERS"

---

pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementWaitsForCompletedState
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementWaitsForFailedState
pkg/flink/internal/controller/.snapshots/TestStatementControllerTestSuite-TestExecuteStatementWaitsForNonEmptyPageToken
pkg/flink/internal/controller/statement_controller.go
pkg/flink/internal/controller/statement_controller_test.go
pkg/flink/internal/store/store_test.go
pkg/flink/types/processed_statement.go

Checklist
---------
What
----
- We should use the "listening for execution errors" flow for all statements that are RUNNING but don't have results
- We should also still check the statement prefix in case sqlTraits are not available
References
----------
Test & Review
-------------

fix: wait for statements properly

---

pkg/flink/internal/store/store.go

Checklist
---------
What
----
We will print the status detail field twice, if the statement transitions to a terminal state.
References
----------
Test & Review
-------------

fix: stop printing status detail of terminal statement twice

---

pkg/flink/internal/controller/input_controller.go

Release Notes
-------------
New Features
- Flink shell supports new keybindings
- Ctrl-D deletes characters and only closes if the buffer is empty
- Alt-D deletes words
- Alt-L lowercases words
- Alt-U uppercases words
Checklist
---------
What
----
https://github.com/confluentinc/cli/assets/13372091/e0629d3f-6802-4155-bc0d-199ec4818871
References
----------
Test & Review
-------------

KFS-1706 Add missing keyboard shortcuts to flink shell

---

pkg/kafka/cluster.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a panic in `confluent context update --kafka-cluster`
Checklist
---------
What
----
The context update command sends a `nil` client to `FindCluster`, which causes a panic if the cluster isn't found in the user's Kafka Cluster context.
References
----------
Test & Review
-------------

[CLI-3075] Prevent panic in `confluent context update`

---

pkg/flink/internal/store/store_utils.go
pkg/flink/internal/store/store_utils_test.go

Release Notes
-------------
Bug Fixes
- USE supports multibyte characters like `éüöбвг汉` in `confluent flink shell`.
Checklist
---------
What
----
Kafka clusters can contain multibyte characters on their names and that's why this needs to be fixed.
References
----------
Test & Review
-------------
Unit test.

fix/ KFS-1705 USE now works with multibyte chars

---

.github/dependabot.yml

What
----
When dependabot opens PRs for confluentinc/ccloud-sdk-go-v2 and other similar repositories, a PR usually already exists for integrating the updates, or a team plans to integrate them soon.

Block dependabot updates for confluentinc dependencies

---

internal/kafka/command_cluster_describe.go
internal/kafka/command_consumer_group_lag.go
internal/kafka/command_consumer_group_lag_describe.go
internal/kafka/command_consumer_group_lag_list.go
internal/kafka/command_consumer_group_lag_summarize.go
test/fixtures/output/kafka/consumer/group/lag/basic.golden
test/fixtures/output/kafka/consumer/group/lag/describe-json.golden
test/fixtures/output/kafka/consumer/group/lag/describe.golden
test/fixtures/output/kafka/consumer/group/lag/list-json.golden
test/fixtures/output/kafka/consumer/group/lag/list.golden
test/fixtures/output/kafka/consumer/group/lag/summarize-json.golden
test/fixtures/output/kafka/consumer/group/lag/summarize.golden
test/kafka_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- Improve error message when running `confluent kafka consumer group lag` commands without a dedicated Kafka cluster
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Look up if Kafka cluster is dedicated before running consumer group lag commands
Test & Review
-------------
Integration tests

[CLI-3110] Error on `kafka consumer group lag` commands when cluster is not dedicated

---

pkg/flink/internal/results/materialized_results_test.go
pkg/flink/types/materialized_results.go

Release Notes
-------------
Checklist
---------
What
----
This seems more resilient, since we could still recover from cases where we missed the initial insert event for some reason. The subsequent UpdateAfter events, would lead to the row being inserted eventually.
References
----------
Test & Review
-------------

fix: treat Insert and UpdateAfter both as upsert events

---

test/flink_test.go

Release Notes
-------------
Checklist
---------
What
----
Tests are broken because of daylight savings time. To avoid this, we set the TZ to be UTC. This should unblock https://github.com/confluentinc/cli/pull/2699
References
----------
Test & Review
-------------

fix: set timezone to UTC for flink shell tests

---

internal/connect/command.go
internal/connect/command_plugin.go
internal/connect/command_plugin_install.go
pkg/cmd/authenticated_cli_command.go

Release Notes
-------------
- PLACEHOLDER
New Features
- `confluent connect plugin install` no longer requires users to log in
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Not all on-premises users have MDS set up. This PR removes the login requirement so all on-premises users can use this command.
References
----------
Test & Review
-------------
Manual testing: checked that this command can be used when logged out and when logged in to on-prem.

[CLI-3048] Remove login requirement for `confluent connect plugin install`

---

pkg/flink/types/application_options.go
pkg/flink/types/application_options_test.go

Checklist
---------
What
----
Adds a function to parse app options from slices using reflections. This will enable us to overwrite the ApplicationOptions with special config flags that will only be available behind a feature flag. We can then use this to run the CLI against a local k8s instance of the flink system
References
----------
Test & Review
-------------

feat: add function to parse app options from slices

---

internal/flink/command_statement_describe.go
pkg/output/table.go
test/fixtures/output/flink/statement/describe-yaml.golden
test/fixtures/output/flink/statement/describe.golden
test/test-server/flink_gateway_router.go

Release Notes
-------------
- PLACEHOLDER
New Features
- [Early Access] Add "Properties" and "Principal" fields to `confluent flink statement describe`
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Add both fields and wrote a map printer, to be added to other commands in v4.
References
----------
https://confluentinc.atlassian.net/browse/CLI-3115
Test & Review
-------------
Integration tests

Add "Properties" and "Principal" fields to `flink statement describe`

---

internal/flink/command_shell.go
pkg/flink/app/application.go
pkg/flink/lsp/lsp_completer_ws.go
pkg/flink/types/application_options.go
pkg/flink/types/application_options_test.go

Checklist
---------
What
----
This adds two flags behind a feature flag which will only be enabled for internal orgs. With these flags we can overwrite the ApplicationOptions the shell uses. This enables us to run the flink shell with a local instance of the Flink system.
References
----------
Test & Review
-------------

[KFS-1863] add local mode to flink shell

---

.github/dependabot.yml

What
----
I realized we haven't seen Dependabot PRs in over a month. Turns out I misread the documentation and 0 does not signify infinity. Instead, replace with a large number.
References
----------
Test & Review
-------------

Set Dependabot PR limit to a large number

---

test/local_test.go

What
----
Same logic as https://github.com/confluentinc/cli/pull/2711, `main` is broken again due to a GitHub rate limit
References
----------
Test & Review
-------------

Remove local kafka test (part 2)

---

internal/flink/command_compute_pool_delete.go
test/fixtures/output/flink/compute-pool/delete-multiple-refuse.golden
test/fixtures/output/flink/compute-pool/delete-multiple-success.golden

Release Notes
-------------
New Features
- Added warning with statement retention time for `confluent flink compute-pool delete`
Checklist
---------
What
----
References
----------
Test & Review
-------------

feat/KFS-1891 KFS-1881 warning and new retention for compute pool deletion msg

---

internal/iam/command_rbac_role_binding_list.go
test/fixtures/output/iam/rbac/role-binding/list-user-orgadmin-cloud.golden
test/test-server/iam_handlers.go

Checklist
---------
What
----
It's possible for the role binding API to return a specific role binding even though its resource has been deleted. We want to align with the UI and print the role binding in that case.
Test & Review
-------------
Added integration test, will manually test before merging.

CLI-3124: Print role bindings with deleted resources

---

internal/flink/command_compute_pool_delete.go

Release Notes
-------------
Checklist
---------
What
----
We want to toggle the change with the new statement retention time message with a feature flag
References
----------
Test & Review
-------------

refactor: KFS-2060 put new retention time behind feature flag

---

internal/connect/command_offset_status_describe.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Prevent `confluent connect offset delete`, `confluent connect offset update`, and `confluent connect offset status describe` from crashing
Checklist
---------
What
----
`IsSet()` in ccloud-sdk-go-v2 doesn't guarantee that a nullable field is actually non-nil, so we need to check directly that it isn't nil.
References
----------
Test & Review
-------------

[CLI-3126] Fix panic in Connect offset commands

---

internal/kafka/kafka_rest_onprem.go
test/fixtures/output/kafka/broker/list-warning-cloud-url.golden
test/kafka_test.go

Release Notes
-------------
New Features
- Print a warning when a Confluent Cloud Kafka REST URL is passed to Confluent Platform Kafka REST
Checklist
---------
What
----
Warn on bad URLs such as `confluent kafka broker list --url https://pkc-12345.us-west-2.aws.confluent.cloud:443`
Test & Review
-------------
Added integration test

CLI-3118: Print warning when Cloud URL is passed to CP Kafka REST

---

go.mod
go.sum
internal/connect/command_cluster_create.go
internal/connect/command_cluster_update.go
internal/connect/utils.go
pkg/ccloudv2/connect.go
test/connect_test.go
test/fixtures/input/connect/config-new-format.json
test/fixtures/input/connect/config.yaml
test/fixtures/input/connect/update-config-malformed.json
test/fixtures/input/connect/update-config-new-format.json
test/fixtures/input/connect/update-config.yaml
test/fixtures/output/connect/cluster/create-help.golden
test/fixtures/output/connect/cluster/update-error.golden

Release Notes
-------------
New Features
- Support passing offsets to `confluent connect cluster create` as part of the configuration file
What
----
Updated Connect create cluster command to include offsets
References
----------
Test & Review
-------------
Updated unit tests to include offsets

Updated Connect create cluster command to include offsets

---

internal/iam/command_rbac.go
internal/iam/command_rbac_role_describe.go
internal/iam/command_rbac_role_list.go

What
----
Adds the Flink model roles to the list and describe roles commands to support the Flink Model EA. 
References
----------
Test & Review
-------------

[AM-4684] Add Flink model roles to CLI list/describe commands

---

pkg/config/config.go
pkg/config/config_test.go
test/cli_test.go

Release Notes
-------------
- CLI text highlighting is now enabled by default for new users
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Set text highlighting to true by default instead of false. This doesn't affect existing users (unless they delete their config file for some reason)
References
----------
Test & Review
-------------
Manual testing:
- checked that this change doesn't have an effect if `enable_color: false` is already set
- deleted my config file to start over and checked that text highlighting was enabled without having to use `confluent configuration update enable_color true`

[CLI-2996] Enable CLI color by default

---

internal/plugin/command.go
internal/plugin/command_install.go
internal/plugin/command_install_test.go
internal/plugin/command_list.go
internal/plugin/command_search.go
internal/plugin/command_search_test.go
internal/plugin/command_uninstall.go
pkg/plugin/bash_plugin_installer.go
pkg/plugin/go_plugin_installer.go
pkg/plugin/python_plugin_installer.go
pkg/resource/resource.go
test/fixtures/output/plugin/help-onprem.golden
test/fixtures/output/plugin/help.golden
test/fixtures/output/plugin/list.golden
test/fixtures/output/plugin/uninstall-help-onprem.golden
test/fixtures/output/plugin/uninstall-help.golden
test/fixtures/output/plugin/uninstall.golden
test/plugin_test.go

Release Notes
-------------
- The "name" field in in the `confluent plugin search` has been renamed to "id"; a new "name" field has been added in its place
New Features
- Added `confluent plugin uninstall` command for Confluent Platform
Checklist
---------
What
----
Added plugin uninstall command to remove the plugins that are no longer needed for a user. Also added the ID for a particular plugin in the command plugin list (which can be used as the flag in uninstall) and changed the one of the column names in plugin search for the sake of consistency with list command
References
----------
https://confluentinc.atlassian.net/browse/CLI-2908
Test & Review
-------------
Created a new function in the TestPluginUninstall in the plugin_test.go class to test the unistall …

[CLI-2908] Add plugin uninstall command

---

test/fixtures/output/kafka/client-config/java-no-sr-keypair.golden

What
----
These were accidentally deleted from the confluentinc/examples repo. When they were added back, a trailing space was stripped, so it also needs to be stripped from the expected output
References
----------
Test & Review
-------------

Fix `kafka client-config` tests

---

internal/kafka/kafka_rest_onprem.go
pkg/auth/auth.go
pkg/auth/sso/auth_state.go
pkg/linter/command_rules.go

Release Notes
-------------
Bug Fixes
- Trim custom Kafka REST `--url` values properly
Checklist
---------
What
----
Make sure URL suffixes are being trimmed properly.
Test & Review
-------------
Manually tested login with `--no-browser` and trailing "/"

Trim URL suffixes properly

---

pkg/flink/config/local_statements.go
pkg/flink/internal/store/store_utils.go
pkg/flink/internal/store/store_utils_test.go

Release Notes
-------------
Bug fix
- [Early Access] Prevent persistent user secret in CLI history
Checklist
---------
What
----
We don't want to store any secrets set using 'sql.secrets.*' to history . Same as https://github.com/confluentinc/cli/pull/2776 but that PR has branch naming issue. Can't have `'` in the branch name. https://confluent.slack.com/archives/C09EP1SS3/p1716916913343059
References
----------
Test & Review
-------------
unit tests

Feat/KFS-2159 don't store secrets to history

---

pkg/cmd/prerunner.go
pkg/cmd/run_requirements.go
pkg/config/config.go
pkg/errors/typed.go
test/fixtures/output/kafka/broker/list-cloud-login.golden
test/fixtures/output/kafka/broker/list-not-logged-in.golden
test/kafka_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Some commands set `c.PersistentPreRunE = prerunner.InitializeOnPremKafkaRest(c.AuthenticatedCLICommand)`, which overwrites the usual `PersistentPreRunE`.
However, doing this causes the error from the call to `ErrIfMissingRunRequirement` in `AuthenticatedWithMDS` to not be returned. This means that using `InitializeOnPremKafkaRest` causes annotations to be ignored. This results in misleading errors or even panics if users try to run the commands that the annotations were supposed to prevent them from running.
As a quick fix, I've added the `ErrIfMissingRunRequirement` requirement check to `InitializeOnPremKafkaRest` itself.
References
----------
Test & …

Fix missing checks on command run requirements

---

internal/kafka/command_topic_produce.go
internal/kafka/command_topic_produce_test.go
test/fixtures/output/kafka/topic/produce-help-onprem.golden
test/fixtures/output/kafka/topic/produce-help.golden

Release Notes
-------------
New Features
- Add `--headers` to `confluent kafka topic produce` for specifying headers manually when producing messages
Checklist
---------
What
----
What?
The `confluent kafka topic produce` command has been changed to accept the `--headers` flag to specify the headers manually in the below format `key1:value1,key2:value2`.
The headers values are then parsed to the Kafka headers type.
Why?
When the messages are produced from CLI, currently it is not possible to set the headers and this changes allows it.
References
----------
Resolves #2768 
Test & Review
-------------
Currently, it has been tested with local build of Confluent CLI together with the [confluentinc/cp-server](https://hub.docker.com/r/confluentinc/cp-kafka) & …

Add kafka message headers with --headers flag

---

docker/Dockerfile

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Installing bash and/or bash-completions in the latest version of the `alpine` dockerfile now creates `/etc/bash_completion.d`, which causes `mkdir -p /etc/bash_completion.d` to fail.
Fix is to add `-p` so that mkdir doesn't error if the folder already exists.
References
----------
Test & Review
-------------
Tested manually with dry run.

Fix Alpine dockerfile build issue

---

internal/connect/command_plugin_install.go
internal/kafka/command_broker.go
internal/kafka/command_consumer.go
internal/kafka/command_link.go
internal/kafka/command_partition.go
internal/kafka/command_replica.go
internal/secret/command.go
pkg/cmd/run_requirements.go
pkg/config/config.go
test/fixtures/output/kafka/broker/list-cloud-login.golden
test/fixtures/output/kafka/broker/list-not-logged-in.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug requiring an on-premises login to use the on-premises `confluent kafka` commands
Checklist
---------
What
----
Fixing the run requirement bug where `InitializeOnPremKafkaRest` caused all run requirements to be ignored surfaced this issue, where incorrect run requirements were put on various on-prem kafka commands.
References
----------
Test & Review
-------------

Fix on-prem kafka rest bug

---

internal/cluster/command_describe.go
internal/login/command.go
internal/logout/command_test.go
pkg/auth/auth.go
pkg/auth/login_credentials_manager.go
pkg/auth/login_credentials_manager_test.go
pkg/cmd/authenticated_cli_command.go
pkg/cmd/prerunner.go
pkg/errors/warning_message.go

Release Notes
-------------
- The following deprecated environment variables are no longer supported: "CCLOUD_EMAIL", "CCLOUD_PASSWORD", "CONFLUENT_USERNAME", "CONFLUENT_PASSWORD", "CONFLUENT_MDS_URL", and "CONFLUENT_CA_CERT_PATH"
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

[CLI-2351] Remove deprecated env vars

---

internal/schema-registry/command_schema_list.go
test/fixtures/output/schema-registry/schema/list-schemas-default.golden
test/fixtures/output/schema-registry/schema/list-schemas-subject.golden

Release Notes
-------------
- Renamed `Schema ID` to `ID` in `schema-registry schema list`
Checklist
---------
What
----
Renamed `Schema ID` to `ID` in `schema-registry schema list`
References
----------
https://confluentinc.atlassian.net/browse/CLI-2696
Test & Review
-------------

[CLI-2696] In `schema-registry schema list`, rename "Schema ID" to "ID"

---

internal/schema-registry/command_dek_create.go
internal/schema-registry/command_dek_delete.go
internal/schema-registry/command_dek_describe.go
internal/schema-registry/command_dek_subject_list.go
internal/schema-registry/command_dek_undelete.go
internal/schema-registry/command_dek_version_list.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Allow `confluent schema-registry dek create` to be called without specifying `--algorithm`
Checklist
---------
What
----
If `--algorithm` was omitted, we previously would pass `""` to the backend which resulted in:
```
Error: Cannot coerce empty String ("") to `DekFormat` value (but could if coercion was enabled using `CoercionConfig`)
```
Now, we do not pass that field.
Test & Review
-------------
Manually tested

Do not pass `""` to backend if `--algorithm` is unspecified

---

internal/kafka/command_region_list.go
test/fixtures/output/kafka/10.golden
test/fixtures/output/kafka/11.golden
test/fixtures/output/kafka/14.golden
test/fixtures/output/kafka/15.golden
test/fixtures/output/kafka/16.golden
test/fixtures/output/kafka/9.golden

Release Notes
-------------
- Changed column "Region Name" to "Name", "Cloud ID" to "Cloud ", "Region ID" to "Region" and removed "Cloud Name" in the output of `confluent kafka region list`
Checklist
---------
What
----
`kafka region list` output should match `flink region list`
References
----------
https://confluentinc.atlassian.net/browse/CLI-2851
Test & Review
-------------
Updated Integration tests.

[CLI-2851] `kafka region list` output should match `flink region list`

---

internal/kafka/command_topic.go
internal/kafka/command_topic_produce.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix missing `--headers` flag error in `confluent local kafka topic produce`
Checklist
---------
What
----
The `--headers` flag was missing in `confluent local kafka topic produce` but trying to be accessed due to the changes from #2775. Ignore this flag if it is not specified.
References
----------
Test & Review
-------------
Manually tested

Fix `--headers` flag bug in `local kafka topic produce`

---

internal/environment/command_use.go
internal/flink/command_region_use.go
internal/iam/command_service_account_use.go
internal/kafka/command_cluster_use.go
test/fixtures/output/environment/use-help.golden
test/fixtures/output/flink/region/use-help.golden
test/fixtures/output/iam/service-account/use-help.golden
test/fixtures/output/kafka/cluster/use-help.golden

Release Notes
-------------
- The `--context` flag has been removed from `confluent environment use`, `confluent flink region use`, `confluent service-account use`, and `confluent kafka cluster use`
- The `--environment` flag has been removed from `confluent flink region use` and `confluent kafka cluster use`
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------

[CLI-2853] Remove `environment` and `context` flags from various `use` commands

---

pkg/auth/auth_token_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix an issue preventing on-premises users from refreshing SSO logins more than once
Checklist
---------
What
----
On-prem refresh tokens remain valid after login extension requests. They still expire, and their expiration is set on the IDP side.
References
----------
Test & Review
-------------
TODO: manual testing

[CLI-3140] Allow multiple onprem SSO login refresh

---

internal/schema-registry/command_schema_compatibility_validate.go
test/fixtures/output/schema-registry/schema/compatibility/validate-help-onprem.golden
test/fixtures/output/schema-registry/schema/compatibility/validate-help.golden
test/schema_registry_test.go

Release Notes
-------------
- The `--schema` flag for `confluent schema-registry schema compatibility validate` has been replaced with a required argument
- The `--subject` flag is now required for `confluent schema-registry schema compatibility validate`; the `--type` flag is additionally required for the Cloud version of this command
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
- Make `--schema` a required argument instead of a flag
- Make `--subject` required
- Make `--type` required for Cloud
The Cloud backend returns an unprocessable entity error when the `--type` isn't specified. Schema type is optional for on-prem according to the on-prem API docs, though (since it defaults to AVRO).
The ticket also mentions making `--version` …

[CLI-2622] Update flags for `schema-registry schema compatibility validate`

---

internal/kafka/command_quota.go
internal/kafka/command_quota_create.go
internal/kafka/command_quota_describe.go
internal/kafka/command_quota_list.go
internal/kafka/command_quota_update.go
test/fixtures/output/kafka/quota/create-default-yaml.golden
test/fixtures/output/kafka/quota/create.golden
test/fixtures/output/kafka/quota/describe-json.golden
test/fixtures/output/kafka/quota/describe.golden
test/fixtures/output/kafka/quota/list-json.golden
test/fixtures/output/kafka/quota/list-yaml.golden
test/fixtures/output/kafka/quota/list.golden
test/fixtures/output/kafka/quota/update.golden

Release Notes
-------------
- The serialized field `principals` in `confluent kafka quota` commands is now an array
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
I also moved the `B/s` bit in the human output from the value to the field label.
This makes it easier to remove the code duplication when https://confluentinc.atlassian.net/browse/CLI-3013 is done.
References
----------
Test & Review
-------------

[CLI-2826] Use array for `principals` in serialized output of `confluent kafka quota` commands

---

pkg/flink/internal/store/store_utils.go
pkg/flink/internal/store/store_utils_test.go

Release Notes
-------------
Bug Fixes
- `confluent flink shell`: The `USE <catalog>.<database>` command previously set an incorrect key/value pair in the config (`catalog: database`). Now it sets the proper key/value pairs (`sql.current-catalog: catalog, sql.current-database: database`)
Checklist
---------
What
----
We were setting the wrong key in the config
References
----------
Test & Review
-------------

[KFS-2294] set correct key/value pairs in USE catalog.database cmd

---

test/fixtures/output/flink/compute-pool/create-region-autocomplete.golden
test/fixtures/output/flink/compute-pool/describe-after-use.golden
test/fixtures/output/flink/compute-pool/describe.golden
test/fixtures/output/flink/compute-pool/list-after-use.golden
test/fixtures/output/flink/compute-pool/list-region-autocomplete.golden
test/fixtures/output/flink/compute-pool/list-region.golden
test/fixtures/output/flink/compute-pool/list.golden
test/fixtures/output/flink/compute-pool/update-after-use.golden
test/fixtures/output/flink/compute-pool/update.golden
test/fixtures/output/flink/region/list-cloud.golden
test/fixtures/output/flink/region/list-json.golden
test/fixtures/output/flink/region/list.golden
test/fixtures/output/flink/statement/list-cp-incorrect-region.golden
test/flink_test.go
test/test-server/fcpm_handlers.go

Release Notes
-------------
Checklist
---------
What
----
[Last PR](https://github.com/confluentinc/cli/pull/2846) broke tests on master. The failure came from the fact that we had an inconsistent usage of regions across tests. Gateway test handlers were assuming things to be in `eu-west-1` but then the compute pool handlers returned `us-west-1/us-west-2` regions. This PR aligns the regions between those two test backends 
References
----------
Test & Review
-------------
It looks like the integration tests do not run on PRs anymore, so this time I ran them locally to confirm they all pass
EDIT: actually, the integration tests _do_ run on PRs. The failure happened because of a semantic merge conflict with [this PR](https://github.com/confluentinc/cli/pull/2850). The new tests were merged …

chore: consistent usage of regions across tests

---

debian/Makefile
debian/patches/standard_build_layout.patch

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The binary packaged with Platform should have the update command disabled, because each release of Confluent Platform has a fixed CLI version. Even if customers do want to upgrade it, they should do so through package managers.
We upload archives, but not binaries, with updates disabled. This PR corrects a bug that tries to pull the binary by instead pulling the archive and extracting the binary from it.
References
----------
Test & Review
-------------
I tested the updated for loop locally on my machine.

Update packaging script

---

pkg/docs/doc_page.go

This requirement only applies to confluent local kafka commands, and particularly to `confluent local kafka start`, so adding a note specific to that command.
What
----
`confluent local kafka start` requires Docker to be running as a prerequisite, added a new note that describes this and the test pre-production caveat that's in all the other `confluent local` command descriptions
References
----------
- JIra: https://confluentinc.atlassian.net/browse/CLI-3149
- PR for the `docs-common` update: https://github.com/confluentinc/docs-common/pull/1383
- Airlock PR: https://github.com/confluentinc/airlock-cli/pull/27 ([These commits](https://github.com/confluentinc/airlock-cli/pull/27/commits) were made on that airlock branch.)
Test & Review
-------------
Run `make docs` locally.

CLI-3149 confluent local kafka start requires Docker to be running as a prerequisite (#27)

---

pkg/docs/doc_page.go

Release Notes
-------------
Docs improvement
- Adds explanatory notes at the top of commands affected by the CLI v4 update command renaming, whose names stayed the same, but have new functionality
What
----
Added notes to some commands (these notes were previously added to the generated output files during the v4 CLI release. We needed to get them into the CLI source code.
References
----------
https://confluentinc.atlassian.net/browse/DOCS-30090
Test & Review
-------------
Built docs locally

Add notes to CLI reference source re: renamed commands (#44)

---

cmd/docs/main.go
test/fixtures/output/local/services/help-onprem.golden
test/fixtures/output/local/services/help.golden
test/help_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The confluent local services command only shows control-center commands if it detects a Platform installation on the machine.
The TestHelp golden files for local services do not include control-center, which causes TestCLI/TestHelp/local_services_--help and TestCLI/TestHelp/local_services_--help#01 to fail when running the tests locally if you have Platform installed.
This PR uses a temporary file and a temporary change to $CONFLUENT_HOME to force docs and tests to include control center, even if you don't have it installed locally.
References
----------
Test & Review
-------------
I removed all installations of Confluent Platform from my local …

Make tests not depend on whether or not Confluent Platform is installed

---

internal/iam/command_rbac_role_binding_delete.go
test/fixtures/output/iam/rbac/role-binding/delete-help-onprem.golden
test/fixtures/output/iam/rbac/role-binding/delete-missing-role-onprem.golden
test/iam_test.go

* DOCS-29556 , DOCS-29555  Add a CP on-prem example for `confluent iam rbac role-binding delete` to show `--kafka cluster` is a required flag for this action
* Update internal/iam/command_rbac_role_binding_delete.go
* add test for new on-prem example in confluent iam rolebinding delete, per Steven's comment
* Update test/fixtures/output/iam/rbac/role-binding/delete-help-onprem.golden
* Add updates to golden file based on generated output of make integration test command
---------------
Release Notes
---------------
- No release notes needed
What
-----
- Added a CP on-prem example for `confluent iam rbac role-binding delete` to show --kafka cluster is a required flag 
References
----------
- Related Airlock PR: https://github.com/confluentinc/airlock-cli/pull/41
- Jira ticket: …

DOCS-29556, DOCS-29555 Add a CP on-prem example for confluent iam rbac role-binding delete to show --kafka cluster is a required flag (retry) (#41)

---

internal/secret/command_file_rotate.go
test/fixtures/output/secret/file/rotate-help-onprem.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- The `--passphrase-new` flag in `confluent secret file rotate` is no longer required
Checklist
---------
What
----
This flag was marked as required in v4.0.0, which is a bug, because this flag is only required for rotating master keys, but not data keys.
References
----------
Test & Review
-------------

`passphrase-new` shouldn't be required

---

internal/kafka/command_cluster.go
internal/kafka/command_cluster_configuration.go
internal/kafka/command_cluster_list_onprem.go
test/kafka_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Allow `confluent kafka cluster configuration` commands to be used while logged out
Checklist
---------
What
----
Fix incorrect annotations after splitting this functionality off of `kafka broker`.
References
----------
Test & Review
-------------

Fix bug preventing `confluent kafka cluster configuration` from being used while logged out

---

go.mod
go.sum
internal/kafka/command_link.go
internal/kafka/command_mirror.go
internal/kafka/command_mirror_resume.go
internal/kafka/command_mirror_truncate_and_restore.go
pkg/ccloudv2/kafkarest.go
test/fixtures/output/kafka/mirror/help.golden
test/fixtures/output/kafka/mirror/truncate-and-restore-help.golden
test/fixtures/output/kafka/mirror/truncate-and-restore-mirror-json.golden
test/fixtures/output/kafka/mirror/truncate-and-restore-mirror-with-partition-data-json.golden
test/fixtures/output/kafka/mirror/truncate-and-restore-mirror-with-partition-data-yaml.golden
test/fixtures/output/kafka/mirror/truncate-and-restore-mirror-with-partition-data.golden
test/fixtures/output/kafka/mirror/truncate-and-restore-mirror-yaml.golden
test/fixtures/output/kafka/mirror/truncate-and-restore-mirror.golden
test/kafka_test.go
test/test-server/kafka_rest_router.go

Release Notes
-------------
New Features
- Add `confluent kafka mirror truncate-and-restore`
Checklist
---------
What
----
Added new functionality for Confluent CLI via `truncate-and-restore` command. 
References
----------
https://confluentinc.atlassian.net/browse/KGLOBAL-5237 and https://confluentinc.atlassian.net/browse/KGLOBAL-5410
Also supersedes https://github.com/confluentinc/cli/pull/2859.
Test & Review
-------------
Has been tested via new test cases and with manual e2e testing.

KGLOBAL-5237: Implement Confluent CLI for TRUNCATE_AND_RESTORE

---

pkg/flink/cmf_rest_client.go

Release Notes
-------------
```
$ ./confluent_4.7.0_darwin_arm64 flink environment list --url http://localhost:8080/
Error: failed to list environments: {"errors":[{"message":"No static resource cmf/api/v1/environments."}]}
```
doesn't work but
```
$ ./confluent_4.7.0_darwin_arm64 flink environment list --url http://localhost:8080
None found.
```
works
This PR ensures that both the ways of specifying the URL work
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
References
----------
Test & Review
-------------
`make test` passes

Fix URL generation with trailing backspaces

---

go.mod
go.sum
internal/flink/command_statement.go
internal/flink/command_statement_create.go
internal/flink/command_statement_describe.go
internal/flink/command_statement_list.go
test/fixtures/output/flink/connectivity-type/list-public.golden
test/fixtures/output/flink/statement/describe-yaml.golden
test/fixtures/output/flink/statement/describe.golden
test/fixtures/output/flink/statement/list-completed.golden
test/fixtures/output/flink/statement/list-yaml.golden
test/fixtures/output/flink/statement/list.golden
test/test-server/flink_gateway_router.go

Release Notes
-------------
New Features
- Added `LatestOffsets` and `LatestOffsetsTimestamp` fields to the `flink statement describe` and `flink statement list` commands
Checklist
---------
What
----
Flink carry over offset onboarding in Flink Statement API
References
----------
https://confluentinc.atlassian.net/browse/CLI-3262
Test & Review
-------------
Wrote integration tests and tested it manually

[CLI-3262] - CLI: Flink carry over offset onboarding in Flink Statement API

---

go.sum
internal/asyncapi/command_export.go
internal/kafka/command_topic_produce.go
internal/kafka/confluent_kafka.go

Release Notes
-------------
Bug Fixes
- Fix a bug preventing `confluent kafka topic consume` from consuming Avro, Protobuf, and JSONSchema messages correctly produced with CLI version 4.7.0 or earlier
Checklist
---------
What
----
References (Confluent Only)
----------
https://confluentinc.atlassian.net/browse/CLI-3315
Test & Review (Confluent Only)
-------------
https://docs.google.com/document/d/1GwXz9hNOkub_Br-2nssoYWCf6elZBvwo7TMhCNYinwE/edit?tab=t.0#heading=h.xl87olcgrdxf

[CLI-3315] Panic: confluent kafka topic consume v4.8.0

---

internal/flink/command_application_webui.go
pkg/cmd/cli_command.go

Release Notes
-------------
We want to be able to pass the CLI version information to the backend server for CMF to perform compatibility checks.
All the commands except `web-ui-forward` use a SDK which sets up the `UserAgent` header. We simply pass the value of the version to the same header.
In case of `web-ui-forward`, since the origin of the calls will be from user's browser, we did not want to override the user agent header as it might be used by browsers for checks of their own, we have introduced a new header for just that API. 
Validation
- I have verified that the version is being propagated into the request by using `ldflags` and validating that it has the same behaviour for the flink commands as the base `version` command 
```
> go run -ldflags "-X main.version=1.2.0" …
```

Passes CLI version info to flink APIs

---

internal/flink/command_application_delete.go
internal/flink/command_application_webui.go
internal/flink/command_environment_delete.go
pkg/flink/cmf_rest_client.go
test/fixtures/input/flink/application/update-with-get-failure.json
test/fixtures/output/flink/application/delete-mixed.golden
test/fixtures/output/flink/application/delete-non-existent-app.golden
test/fixtures/output/flink/application/delete-non-existent-env.golden
test/fixtures/output/flink/application/forward-get-failure.golden
test/fixtures/output/flink/application/forward-nonexistent-application.golden
test/fixtures/output/flink/application/forward-nonexistent-environment.golden
test/fixtures/output/flink/application/update-with-get-failure.golden
test/fixtures/output/flink/environment/delete-mixed.golden
test/fixtures/output/flink/environment/delete-non-existent-env.golden
test/fixtures/output/flink/environment/update-get-failure.golden
test/flink_onprem_test.go
test/test-server/flink_onprem_handler.go

Release Notes
-------------
Till now, for the following API calls:
- Delete environment/Delete Application 
- Update environment/Update application
- Forward web-ui
We used to give `not found` even if it has any other issue. 
This PR handles those case and gives more info about the error
Since the delete API depends on the existence check same as other commands, we haven't changed the behaviour there, just that we have added another line of suggestion to the error:
```
Error: Flink application "default-application-1" not found
Suggestions:
List available Flink applications with `confluent flink application list`.
Check that CMF is running and accessible.
```
In case of connectivity issues with CMF: 
```
> go run cmd/confluent/main.go flink environment update ralo
Error: failed to update …
```

Handles not found errors with more suggestions

---

go.mod
go.sum
internal/kafka/command_link_describe.go
test/fixtures/output/kafka/link/describe-bidirectional-link.golden
test/test-server/kafka_rest_router.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Temporarily reverting to unblock release while we resolve the naming mismatch for
```
CategoryCounts string `human:"Mirror Partition States Count,omitempty" serialized:"category_counts,omitempty"`
```
References
----------
Test & Review
-------------

Revert "KGLOBAL-5675: Add support for mirror partition state summery for link describe  (#2920)"

---

go.mod
go.sum

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The previous PR changed the version in .go-version, but did not change the version in go.mod.
This PR updates the flink-artifact SDK to a new version that doesn't require 1.22.8, and removes the 1.22.9 toolchain requirement.
References
----------
Test & Review
-------------

Switch back to 1.22.7 in go.mod

---

docker/Dockerfile_linux_repos

Release Notes
-------------
- PLACEHOLDER
New Features
- General updates and improvements
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The base image for the Dockerfile_linux_repos dockerfile is currently unavailable, so this PR modifies Dockerfile_linux_repos to account for it.
References
----------
Test & Review
-------------
Ran `VERSION=v4.10.0 scripts/build_linux.sh` to verify that it builds correctly.

Remove dependence on remote docker image

---

.gitignore
internal/flink/command_statement.go
internal/flink/command_statement_resume.go
internal/flink/command_statement_update.go
test/fixtures/output/flink/statement/help.golden
test/fixtures/output/flink/statement/resume-help.golden
test/fixtures/output/flink/statement/resume-invalid-compute-pool.golden
test/fixtures/output/flink/statement/resume-invalid-principal.golden
test/fixtures/output/flink/statement/resume-valid.golden
test/fixtures/output/flink/statement/update-invalid-compute-pool.golden
test/fixtures/output/flink/statement/update-invalid-principal.golden
test/flink_test.go
test/test-server/flink_gateway_router.go

Release Notes
-------------
This PR supports resume the Flink statement with below different valid scenarios:
- Resume under the original `computePool` and `principalId`.
- Resume under a different `computePool` but original `principalId`.
- Resume under a different `principalId` but original `computePool`.
- Resume under a different `computePool` and different `principalId`.
And invalid scenarios:
- Resume under an invalid computePool, the UPDATE request will fail immediately.
- Resume under an invalid user account principalId, the UPDATE request will fail immediately.
- Resume under an invalid service account principalId, the UPDATE request will pass but the statement itself will fail subsequently, and the failed statement can be resumed later.
New Features
-------------
- The Flink …

This PR reapplies the reverted PR(#2922)

---

internal/kafka/command_cluster.go
internal/kafka/command_cluster_create.go
test/fixtures/output/kafka/cluster/create-freight-low.golden
test/kafka_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
For freight clusters, `LOW` and `SINGLE_ZONE` are not the same. `LOW` is acceptable but `SINGLE_ZONE` is not. For freight clusters only, we want to map single-zone and multi-zone to low and high.
References
----------
Test & Review
-------------

[CLI-3337] Map single-zone and multi-zone to high and low for freight clusters

---

internal/api-key/command_describe.go
internal/api-key/command_list.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix a bug in non-prod environment for `confluent api-key describe [API_KEY]` where api key is not correctly displayed
Checklist
---------
What
----
The `confluent api-key describe` command always returns “None found.” in stag environment. The root cause is that in stag the feature flag is enabled, while in prod it's disabled, and in stag the resource gets override during describe, which is unexpected. This fix is to workaround the "None found." issue by following the same coding pattern in command_list.go.
References
----------
Test & Review
-------------
Tested using a stag org and a prod org.

[CLI-3342] Fix issue of describe command return none found in staging

---

internal/local/command_kafka_start.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix an architecture CLI error for `confluent local kafka start` command  
Checklist
---------
What
----
The CLI outputs an `Error: binary architecture "arm64" does not match system architecture "aarch64"` error when user has a system architecture of aarch64. This change adds a mapping from aarch64 to arm64. 
References
----------
Test & Review
-------------

[APIT-2655] Unable to start Kafka local with CLI

---

internal/update/command.go
pkg/cmd/prerunner.go
pkg/update/check.go
pkg/update/check_test.go

Release Notes
-------------
Bug Fixes
- Do not notify of major version updates when there are only minor version updates
Checklist
---------
What
----
* Do not notify of major version updates when there are only minor version updates 
* Make code more readable (and slightly less efficient, but that's ok) by always choosing to split version list into minor+major
References
----------
https://confluentinc.atlassian.net/browse/CLI-3312
Test & Review
-------------
Unit test, manual verification

CLI-3312: Fix major version notification when none exist

---

.semaphore/semaphore.yml
docker/Dockerfile_build_linux_amd64
docker/Dockerfile_build_linux_arm64

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Since the Darwin and Windows tests already build for amd64, this PR adds builds for the other five:
- Darwin arm64
- Linux GLIBC amd64 & arm64
- Linux Alpine amd64 & arm64
Even though the current Linux test builds a GLIBC version, this PR re-builds it in a docker image to enforce the required GLIBC version
References
----------
Test & Review
-------------
New pipeline passed. Overall runtime looks like the same as before, because the new tasks run in parallel to the old ones.

[CLI-3288] Build all OS/Arch combinations in pipeline

---

internal/kafka/command_topic_update.go
test/test-server/kafka_rest_router.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- CLI shows the correct partition count on confluent `kafka topic update my-topic --config num.partitions=X` command
Checklist
---------
What
----
Poll for updates or print warning on `kafka topic update --config num.partitions=XXX`
References
----------
https://confluentinc.atlassian.net/browse/CLI-3095
Test & Review
-------------
Updated the integration tests.

[CLI-3095] On kafka topic update --config num.partitions=XXX, poll for updates or print warning

---

pkg/config/api_key_pair.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix an issue causing `confluent kafka topic [produce | consume]` to fail on Windows when using the `--api-key` and `--api-secret` flag
Checklist
---------
What
----
When selecting an api key with the `confluent api-key use` command, API keys are only decrypted once. This is also what should happen when providing the key/secret with flags to `confluent kafka topic produce | consume`, but on Windows, the CLI would attempt to decrypt them a second time, leading to the following Windows DPAPI error
```
Error: failed to create consumer: decryptbytes: procdecryptdata: The parameter is incorrect
```
where the incorrect parameter is actually the already decrypted key (or secret).
References …

[CLI-2969] Prevent double decryption on Windows

---

internal/command.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Stack traces for some errors are now included in the output of the `-vvvv` debug flag
Checklist
---------
What
----
For Cloud users, the CLI collects and reports panic stack traces and hides them from the user. However, no stack traces are collected for users logged out or logged into on-prem. Those users have no way to access the panic trace, which makes it harder for support to help debug the issue.
This PR adds panic traces to the `-vvvv` trace flag when users aren't logged into Cloud.
We also don't send reports when `cfg.HasGovHostname()` is true, so this PR also adds local `-vvvv` output for this case.
References
----------
Test & Review
-------------
Manually tested by adding a …

[CLI-3272] Add panic stack trace to `-vvvv` output for non-Cloud users

---

internal/flink/command_connection_list.go

Release Notes
-------------
Bug Fixes
- Check env before getting gateway client so env not found error can pop first
Checklist
---------
What
----
Check env before getting gateway client so env not found error can pop first
References
----------
Test & Review
-------------
Manual test
```
haoli@FX2J5RXQ21 ~/projects/flink/cli$ dist/confluent_darwin_arm64/confluent flink connection list  --cloud GCP --region us-central1 --environment abcd
Error: Resource Not Found
Suggestions:
Failed to get environment 'abcd'. List available environments with confluent environment list.
```
Otherwise, it outputs like this:
```
haoli@FX2J5RXQ21 ~/projects/flink/cli$ dist/confluent_darwin_arm64/confluent flink connection list  --cloud GCP --region us-central1 --environment abcd
Error: Forbidden Access
```

[hotfix] validate env before getting gateway client

---

README.md

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
N/A, this is only a change to the README file and not a code change.
What
----
Update stale GLIBC requirements in the README.
The correct version is now 2.28. The 2.31 requirement mentioned in the comments was a bug that has been fixed.
References
----------
https://docs.confluent.io/confluent-cli/current/overview.html#gnu-c-library-glibc
Test & Review
-------------
N/A

Update glibc requirements in the README

---

internal/flink/command_artifact_create.go
test/fixtures/output/flink/artifact/create-azure.golden
test/fixtures/output/flink/artifact/create-python-azure.golden
test/fixtures/output/flink/artifact/delete-azure.golden
test/fixtures/output/flink/artifact/delete-prompt-azure.golden
test/fixtures/output/flink/artifact/describe-azure.golden
test/fixtures/output/flink/artifact/list-azure.golden
test/flink_test.go
test/test-server/flink_artifact_handler.go

Release Notes
-------------
- PLACEHOLDER
New Features
https://confluentinc.atlassian.net/wiki/spaces/CPU/pages/3147269264/BYOC+User+Guide+of+Custom+Plugin+API Step 2 says how to upload to AWS or Azure
The way to upload file via presigned url to AWS/Azure is a bit different. Azure is easier where you just do curl PUT $link
AWS needs to fill up a upload form based on x-amz-algorithm/x-amz-credential/x-amz-date...etc and it's using POST.
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
We need to support flink on Azure. Modify the uploadFile to support PUT method.
Presigned url API failed initially and works after we support PUT method.
```
dist/confluent_darwin_arm64_v8.0/confluent  flink artifact create juyin-azure-1 --artifact-file ~/Downloads/3KB.jar --cloud azure …
```

SCP-3176 support flink artifact on azure

---

internal/iam/command_ipfilter_create.go
internal/iam/command_ipfilter_list.go
test/fixtures/output/iam/ip-filter/create-help.golden
test/fixtures/output/iam/ip-filter/list-help.golden

Checklist
---------
- [N/A] I have verified this PR in Confluent Platform on-premises environment, if applicable.
What
----
Two changes
- Description for the --environment flag 
- Description for the --include-parent-scopes flag: the default for this one shouldn't really matter since it's evaluating if the flag changed (added vs. removed): https://github.com/confluentinc/cli/blob/main/internal/iam/command_ipfilter_list.go#L55 but the description should reflect it correctly. 
Blast Radius
----
All the flags modified here are behind a feature flag which is not turned on in production so there should be no impact if any issues arise. 
References
----------
https://confluentinc.atlassian.net/wiki/spaces/SECENG/pages/4025123742/IP+Filtering+for+SR+CLI+Quality+Review
Test & Review
------------- …

fix: ip filtering description fixes

---

internal/command.go
internal/flink/command.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- On-premises `confluent flink` commands are no longer incorrectly gated behind a feature flag
Checklist
---------
Tested the interface after logging into Cloud
Tested the interface after logging out of Cloud (these on-prem commands are available on cloud logout).
N/A: tests bypass feature flags
What
----
Currently, the entire `confluent flink` command group is behind the `cli.flink` feature flag. However, this flag should only apply to Cloud Flink commands.
On-premises environments often do not have network access to `confluent.cloud`, and so they cannot retrieve the feature flags. The result is the on-prem only `confluent flink application` and `confluent flink environment` commands are not …

[CLI-3385] Fix on-prem Flink dependence on feature flag

---

pkg/flink/app/application.go
pkg/flink/lsp/completer_test.go
pkg/flink/lsp/lsp.go
pkg/flink/lsp/lsp_completer_ws.go
pkg/flink/lsp/lsp_handler.go

Release Notes
-------------
Checklist
---------
What
----
Updated the lsp client to expose the document uri opened. We can now log this value and use it for debugging. Also complemented an old error message with a common private networking issue.
Blast Radius
----
Only debugging, no impact.
References
----------
FSE-215
Test & Review
-------------
Since only refactoring/logs, I've manually tested the changes with the -vvvv flag

[FSE-215] Update lsp client and expose documentUri

---

internal/flink/command_artifact_list.go

Release Notes
-------------
Bug Fixes
- Artifacts are already returned in DESC order from the endpoint, so we want to avoid extra sorting on the CLI side
Checklist
---------
What
----
Blast Radius
----
No impact, only the order of the list results chandes
References
----------
Test & Review
-------------
```
❯ dist/confluent_$(go env GOOS)_$(go env GOARCH)/confluent  flink artifact list --cloud AWS --region us-west-2 --environment env-devc33qr20
ID       |                         Name                         | Cloud |  Region   |  Environment   |           Timestamp              --region us-west-2 --environment env-devc33qr20                                                                                    ✔  14s  1.22.7   16:57:42 …
```

[FRT-918] Flink artifact cli should return artifact by created desc order

---

cmd/lint/main.go
pkg/flink/utils.go
test/fixtures/output/flink/connection/create-help.golden
test/fixtures/output/flink/connection/create/create-couchbase.golden
test/fixtures/output/flink/connection/create/create-wrong-type.golden
test/fixtures/output/flink/connection/list-help.golden
test/fixtures/output/flink/connection/list/list-failure.golden
test/fixtures/output/flink/connection/update-help.golden
test/flink_test.go

Release Notes
-------------
New Features
- Add "couchbase" as a new Flink connection type
Checklist
---------
What
----
Add couchbase as a new flink connection type for Confluent Cloud.
Blast Radius
----
will affect flink connection subcommand.
References
----------
Test & Review
-------------
```
dist/confluent_darwin_arm64_v8.0/confluent flink connection list --cloud aws --region us-west-2 --type couchbase --environment <REDACTED>
Creation Date          |         Name         |  Environment   | Cloud |  Region   |   Type    |                       Endpoint                       |    Data    | Status | Status Detail  
---------------------------------+----------------------+----------------+-------+-----------+-----------+------------------------------------------------------+------------ …
```

[MATRIX-611] feat: add couchbase connection

---

internal/flink/command.go
internal/flink/command_application_create.go
internal/flink/command_application_delete.go
internal/flink/command_application_describe.go
internal/flink/command_application_list.go
internal/flink/command_application_update.go
internal/flink/command_application_webui.go
internal/flink/command_environment_create.go
internal/flink/command_environment_delete.go
internal/flink/command_environment_describe.go
internal/flink/command_environment_list.go
internal/flink/command_environment_update.go
test/fixtures/output/flink/environment/list-cloud.golden
test/flink_onprem_test.go
test/test-server/flink_onprem_handler.go

What we've tested:
* Unit tests added for all the commands.
* Manual testing for environment and application related commands.
This PR is ready to be merged after the review. 
Release Notes
-------------
New Features
- Allow on-premises Flink commands to work with MDS authentication. 
Checklist
---------
- [*] I have successfully built and used a custom CLI binary, without linter issues from this PR.
- [*] I have clearly specified in the `What` section below whether this PR applies to Confluent Cloud, Confluent Platform, or both. 
- [*] I have added appropriate CLI integration or unit tests for any new or updated commands and functionality.
- [*] I confirm that this PR introduces no breaking changes or backward compatibility issues.
- [*] I have indicated the potential customer impact if …

Allow flink onprem commands to work with MDS auth

---

internal/iam/command_rbac_role_list.go
test/fixtures/output/iam/rbac/role/list-cloud.golden
test/test-server/cloud_mds_handlers.go

Release Notes
-------------
This PR will not introduce any changes to a user of the Confluent CLI. This only updates one of our integration tests.
Checklist
---------
What
----
The `confluent rbac role list` test was improperly formatted. This test was setup in a way to call multiple namespaces containing different roles in a single test. Over time, this test degraded and was setup to call the same namespace multiple times, resulting in the test showing a duplicated list of roles. This initial testing strategy came from a concept that customers could query our list endpoint for different role namespaces. The two issues with this are:
1. We have migrated from this strategy, and now the default call to our RBAC list API returns all production roles across *all* namespaces
2. The CLI did not …

AM-5152: Update `confluent rbac role list` integration test format to reflect a real API call

---

cmd/lint/main.go
go.mod
go.sum
internal/iam/command.go
internal/iam/command_pool.go
internal/iam/command_pool_create.go
internal/iam/command_provider_update.go
internal/iam/command_service_account.go
internal/iam/command_service_account_create.go
internal/iam/command_service_account_update.go
pkg/ccloudv2/iam.go
pkg/ccloudv2/identity_provider.go
test/fixtures/output/iam/pool/create-help.golden
test/fixtures/output/iam/service-account/create-help.golden
test/iam_test.go
test/test-server/iam_handlers.go

Checklist
---------
- [N/A] I have verified this PR in Confluent Platform on-premises environment, if applicable.
What
----
Exactly the same as this PR: https://github.com/confluentinc/cli/pull/3005 which we reverted so as not to release these features immediately. 
Added a launchdarkly flag to gate the changes so it doesn't get released immediately. 
Blast Radius
----
Unreleased, no impact. 
References
----------
https://github.com/confluentinc/cli/pull/3005
https://confluentinc.atlassian.net/browse/AM-5025
Test & Review
-------------
Flag enabled in stag, but not in devel. 
**In Devel:** 
**In Stag (You can see the additional resource owner flag)** 
**In Devel:** 
**In stag:**

feat(AM-5025): workload identity additional resource owner flag 

---

go.mod
go.sum
internal/iam/command_certificate_pool.go
internal/iam/command_certificate_pool_create.go
pkg/ccloudv2/certificate_authority.go
test/fixtures/output/iam/certificate-pool/create-help.golden

Checklist
---------
- [N/A] I have verified this PR in Confluent Platform on-premises environment, if applicable.
What
----
This PR adds the resource owner flag option on create for certificate pools. The flag is optional and currently hidden by a feature flag. 
Blast Radius
----
Since this feature is not yet released, there should be no impact to the customer. 
References
----------
https://confluentinc.atlassian.net/browse/AM-5170 
Test & Review
-------------
Additional resource owner flag shown below 
```
Usage:
confluent iam certificate-pool create <name> [flags]
Examples:
Create a certificate pool named "pool-123".
$ confluent iam certificate-pool create pool-123 --provider provider-123 --description "new description"
Flags:
--provider string              REQUIRED: ID of this pool's …
```

feat(am-5157): certificate pool resource owner 

---

.gitignore
internal/schema-registry/command.go
internal/schema-registry/command_cluster.go
internal/schema-registry/command_configuration.go
internal/schema-registry/command_dek.go
internal/schema-registry/command_exporter.go
internal/schema-registry/command_kek.go
internal/schema-registry/command_schema.go
internal/schema-registry/command_subject.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Allow `schema-registry` commands to be used without login
Blast Radius
----
Users trying to run the schema-registry command without logging in
References
----------
https://confluentinc.atlassian.net/browse/CLI-3283
Test & Review
-------------
Tested manually
Output for the schema registry command (not logged in):
Output for the schema registry DEK command (not logged in):

[CLI-3283] Allow schema-registry commands to be used without login

---

internal/asyncapi/account_details.go
internal/asyncapi/command_export.go

Release Notes
-------------
Bug Fixes
- `confluent asyncapi export` flag `--consume-examples` outputs as YAML to match asyncapi documentation
- `confluent asyncapi export` flag `--consume-examples` works with multiple topics
Checklist
---------
What
----
Asyncapi is only CP currently
- Previously we output examples from --consume-examples flag as a string instead of YAML format, which makes it incompatible with asyncapi documentation. Brought up by a customer https://confluentinc.atlassian.net/browse/DGS-19545
- Also previously we are only storing 1 example even if they have multiple topics? Now stores an example per topic
Blast Radius
----
If something goes wrong, --consume-examples flag may not work correctly. But its currently rather broken due to the bugs being fixed 😄 
References …

DGS-19545 Output asyncapi examples as yaml instead of string

---

.semaphore/semaphore.yml

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
The GLIBC builds in the pipeline are currently using unauthenticated Docker calls, and we're hitting the rate limit for that.
This PR comments out those builds to unblock pipelines while we put in a more proper fix.
At the moment I think there are 3 options for fixing this.
Blast Radius
----
N/A: not a code change
References
----------
Ticket for proper fix: https://confluentinc.atlassian.net/browse/CLI-3314
Test & Review
-------------
N/A: not a code change

Remove rate limited pipeline builds for now

---

internal/kafka/command_cluster.go
internal/kafka/command_cluster_create.go
internal/kafka/command_cluster_describe.go
internal/kafka/command_cluster_test.go
internal/kafka/command_cluster_update.go
pkg/kafka/utils.go
test/fixtures/output/kafka/1.golden
test/fixtures/output/kafka/cluster/create-availability-zone-error.golden
test/fixtures/output/kafka/cluster/create-freight-low.golden
test/fixtures/output/kafka/cluster/create-freight.golden
test/fixtures/output/kafka/cluster/create-help.golden
test/fixtures/output/kafka/create-availability-autocomplete.golden

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fixed "For `confluent kafka cluster create command`, it showed as single-zone/multi-zone availability instead of high/low for Freight clusters"
Checklist
---------
What
----
DOCS-28660: Add new availability type attribute value options (LOW/HIGH) for Enterprise clusters
Done
The availability attribute of multi-tenant clusters was changed to LOW/HIGH , and earlier it used to be SINGLE_ZONE, & MULTI_ZONE 
Different cluster types have different valid options and even the same cluster type might have different valid options based on when the org was created.
LOW/HIGH options for Standard and Enterprise clusters created after 4/16
LOW option only for Basic clusters created after 4/16
The CLI and …

Add options for LOW/HIGH availability in cluster create CLI commands

---

internal/ksql/command_cluster_create.go
test/fixtures/output/ksql/cluster/create-result-sr-fail.golden
test/ksql_test.go
test/test-server/ksql_handlers.go
test/test-server/srcm_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
This is a temporary change to PLSR LA logic before PLSR goes GA. The ksql cluster creation needs to use the schema registry cluster ID instead of kafka cluster ID to ensure it doesn't break. 
This LA logic will completely be removed  once PLSR goes GA.
Blast Radius
----
ksql cluster users.
References
----------
Test & Review
-------------

Update ksql Create - PLSR

---

internal/billing/command_payment_describe.go
internal/login/command.go
pkg/cmd/ANNOTATIONS.md
pkg/errors/error_message.go
test/login_test.go
test/test-server/ccloud_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Several commands still reference `confluent admin ...` which has moved to `confluent billing ...`. This PR is to update the references of `confluent admin ...`  to `confluent billing ...`.
Blast Radius
----
References
----------
https://confluentinc.atlassian.net/browse/CLI-3486
Test & Review
-------------
- `make build` and `make lint` succeeded 
- `make unit-test` passed

[CLI-3486] Update references of 'confluent admin ...' to 'confluent billing ...'

---

pkg/ccloudv2/flink.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Fix an issue causing `confluent flink compute-pool list` to sometimes not display all compute pools
Checklist
---------
What
----
Add missing pagination support for flink compute pools.
Blast Radius
----
The `confluent flink compute-pool list` and `confluent flink region list` commands would be impacted.
References
----------
Test & Review
-------------
Listing compute pools with a page size of 2 (I modified the hardcoded value from 100 to 2 for this test):
```
confluent flink compute-pool list               
Current |     ID      |       Name        | Environment | Current CFU | Max CFU | Cloud |  Region   |   Status     
----------+-------------+-------------------+-------------+------------ …
```

[CLI-3499] Add pagination for compute pools

---

go.mod
go.sum

This PR resolves Dependabot alert 33.
Fixing the other alert requires updating golang to 1.23.7:
```
go get golang.org/x/net@v0.36.0
go: downloading golang.org/x/net v0.36.0
go: golang.org/x/net@v0.36.0 requires go >= 1.23.0; switching to go1.23.7
go: downloading go1.23.7 (darwin/amd64) ...
```
We created CLI-3405 to track these changes.

Resolve Dependabot alert 33

---

internal/asyncapi/command_export.go

Release Notes
-------------
Bug Fixes
- `asyncapi export` correctly handles Avro union types in examples output
Checklist
---------
What
----
CC only
If you use consume example flag in asyncapi and have a union type defined in avro, the resulting example will likely not match the asyncapi expected format.
For example, here is a union type definition (meaning it can be of multiple types):
```
- default: null
name: exampleField
type:
- "null"
- string
```
Here is what we put in the example:
```
exampleField:
string: "exampleString"
```
Asyncapi syntax checker will mark this invalid because of the `string:` part being present. This PR removes all maps which use an avro type as the key, which in this case means just outputting `exampleField: "exampleString"`
There is also a block to deal with …

DGS-20003 Asyncapi correctly parse union avro types

---

pkg/ccloudv2/kafka_quotas.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- `confluent kafka quota list` now works when a cluster has more than 100 quotas
Checklist
---------
What
----
For Confluent Cloud.
The `req.PageToken(pageToken)` function call returns a new request with the page token set. The current code discards this value, which means that we send requests without the page token.
If the initial response contains a next page token, this causes an infinite loop where we continuously call the first page of results.
Blast Radius
----
`confluent kafka quota list` would be affected
References
----------
Test & Review
-------------
https://docs.google.com/document/d/1Xy7HLe7Sc5BMLuEJ7NPGvGgfe6dFyf2f3Ycr738elKo/edit?usp=sharing

[CLI-3542] Fix infinite page token loop for `confluent kafka quota list`

---

internal/local/command_services.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- `confluent local services` no longer sets `consumer.interceptor.classes` and `producer.interceptor.classes` configuration options by default when used with Confluent Platform 8.0
Checklist
---------
What
----
For Confluent Platform.
These configs rely on a jar file that ships with Control Center, so we need to remove these configs when running with 8.0 (but keep them when running in 7.9 or lower).
Since we're using ZK for 7.9 or lower and KRaft for 8.0 and above, this PR implements this change by only setting these configs when running in ZK mode.
Blast Radius
----
This change is applied to the following local services: connect, kafka rest, ksql, and schema registry.
Blast radius should be …

[CLI-3544] Only set `consumer.interceptor.classes` and `producer.interceptor.classes` for Confluent Platform 7.9 or lower

---

cmd/lint/main.go
internal/flink/command_connection.go
pkg/flink/utils.go
test/fixtures/output/flink/connection/create-help.golden
test/fixtures/output/flink/connection/create/create-confluent_jdbc.golden
test/fixtures/output/flink/connection/create/create-wrong-type.golden
test/fixtures/output/flink/connection/list-help.golden
test/fixtures/output/flink/connection/list/list-failure.golden
test/fixtures/output/flink/connection/update-help.golden
test/flink_test.go

Release Notes
-------------
New Features
- Add new flink connection type `confluent-jdbc`.
Checklist
---------
What
----
Add confluent-jdbc as a new flink connection type for Confluent Cloud.
Blast Radius
----
Confluent Platform customers using `confluent flink connection `  subcommand would be affected 
References
----------
JIRA ticket: https://confluentinc.atlassian.net/browse/ORC-8867
Test & Review
-------------
Creating connection of type confluent-jdbc
```
dist/confluent_darwin_arm64/confluent flink connection create mysql-customer-db1 \
--cloud gcp \
--region us-central1 \
--type confluent_jdbc \
--endpoint 'jdbc:mysql://customer-db.example.com:3306/customerdb' \
--username 'readonly_user' \
--password 'secret123'
+---------------+---------------------------------------------------- …
```

[ORC- 8867]feat: add confluent-jdbc connection 

---

go.mod
go.sum

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- Support `PRIVATE_NETWORK_INTERFACE` network type for `confluent kafka region list` command
Checklist
---------
What
----
Error was being thrown when  we run `kafka region list` command due to  unknown value "PRIVATE_NETWORK_INTERFACE" for enum ccloud.scheduler.NetworkType. Fixed the issue.
Blast Radius
----
None
References
----------
https://confluentinc.atlassian.net/browse/INC-2165
https://github.com/confluentinc/ccloud-sdk-go-v1-public/pull/43
Test & Review
-------------

[INC-2165] Add support for PRIVATE_NETWORK_INTERFACE

---

internal/kafka/command_link_create_onprem.go
internal/kafka/command_link_describe_onprem.go
internal/kafka/command_link_list_onprem.go
test/fixtures/output/kafka/link/create-destination-link-onprem.golden
test/fixtures/output/kafka/link/create-help-onprem.golden
test/fixtures/output/kafka/link/describe-error-onprem.golden
test/fixtures/output/kafka/link/describe-onprem.golden
test/fixtures/output/kafka/link/list-error-onprem.golden
test/kafka_test.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
Re-implement the block on destination links, but don't remove the flags (because the common functions will still call these flags before the code reaches the destination link block), so that we surface the correct error. So instead, this PR hides those flags.
Also roll back the addition of all new output fields for describe and link except for "Remote Cluster" (used by bidirectional link).
Blast Radius
----
Zero, this is rolling back an addition that hasn't made it into a release yet.
References
----------
Test & Review
-------------
https://docs.google.com/document/d/1aHcFoNgZaOrFQH2ZKgxvMmMGyT_ugMRe5U9cmwxdhW8/edit?usp=sharing

Roll back destination link from on-prem `kafka link create`

---

internal/iam/command_ipfilter.go
internal/iam/command_ipfilter_create.go
internal/iam/command_ipfilter_describe.go
internal/iam/command_ipfilter_list.go
internal/iam/command_ipfilter_update.go
pkg/cmd/flags.go
test/fixtures/output/iam/ip-filter/create-help.golden
test/fixtures/output/iam/ip-filter/update-add-kafka-operation-group.golden
test/fixtures/output/iam/ip-filter/update-help.golden
test/fixtures/output/iam/ip-filter/update-remove-kafka-operation-group.golden
test/iam_test.go
test/test-server/iam_handlers.go

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
- Added support for Kafka IP Filter operation groups, KAFKA_MANAGEMENT and KAFKA_DATA (this is for Confluent Cloud).
- Removed SR and Flink IP Filter flags as they are GA'ed
Blast Radius
----
Confluent Cloud customers who are using confluent ip filter commands could be impacted. (Note that the changes are behind an LD flag and are not on in prod)
References
----------
https://confluentinc.atlassian.net/wiki/spaces/~785802079/pages/3703473045
Test & Review
-------------
Create
```
» dist/confluent_darwin_arm64/confluent iam ip-filter create demo-ip-filter-kafka --operations KAFKA_MANAGEMENT --ip-groups ipg-wng6n …
```

[AM-5230] Add support for kafka IPF CRUD

---

Makefile
debian/patches/standard_build_layout.patch

Release Notes
-------------
- PLACEHOLDER
New Features
- PLACEHOLDER
Bug Fixes
- PLACEHOLDER
Checklist
---------
What
----
It turns out that makefile doesn't like nested ifs using tabs instead of spaces, which was causing `make build` to not work on Linux.
Blast Radius
----
N/A, not a customer facing change.
References
----------
Test & Review
-------------
Tested in an Ubuntu 24.04 docker image.
Before:
```
make build
ifneq (,) # linux (musl)
/bin/bash: -c: line 1: syntax error near unexpected token `,'
/bin/bash: -c: line 1: `ifneq (,) # linux (musl)'
make: *** [Makefile:10: build] Error 2
```
After:
```
make build
CC=gcc CXX=g++ make cli-builder
make[1]: Entering directory '/cli'
GOOS="" GOARCH="" CC="" CXX="" CGO_LDFLAGS="" go install …
```

Fix `make build` on Linux

---

service.yml

Release Notes
-------------
This PR does not introduce any user-facing changes.
Checklist
---------
NA, as this PR only disables further automatic updates for the Makefile.
What
----
This PR fixes a typo in service.yml. To be more specific, we should be using:
```
sonarqube:
enable: true
languages: ["go"]
```
instead of a bare string here to resolve the unexpected comma.
Blast Radius
----
NA, as this PR only disables further automatic updates for the Makefile.
References
----------
* https://confluentinc.atlassian.net/browse/APIE-552
* https://confluent.slack.com/archives/C9Y6NAM6X/p1754954119343639?thread_ts=1754326052.344299&cid=C9Y6NAM6X
Test & Review
-------------
We will need to wait for the next service bot update.

Fix a typo in service.yml.
